### ISSUE TITLE
Information personalized

### ISSUE THREAD

**Issue by AldoVitale83** [Stellarium/stellarium#4008] opened 2024-12-15 17:05 UTC
Stellarium won't save personalized choices in information and in every restart the information is set on all informations
Please help me and give me a solution. I just disinstalxled and reinstalled twice; I have MacBook Air 13 M3 Sequoia 15.2

**Comment by alex-w** [comment] 2024-12-15 18:09
Duplicate of #3910

**Closed by alex-w** 2024-12-15 18:09 UTC
