### ISSUE TITLE
Adding deep space probes to Stellarium

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#447] opened 2018-09-26 06:30 UTC
_Original report by ironman:_ https://bugs.launchpad.net/stellarium/+bug/1485343

This is just an idea, not a bug. Would it be possible to add the deep space probes Voyager s 1 & 2, Pioneers 1 & 2, and along with the latest probe New Horizons to Stellarium, by displaying their locations and giving information about there distances and on where there positions are in our sky just like the satellites around the Earth?

NOTE: I accidentally placed this post in the blue prints area, I thought this area was for ideas for Stellarium. My mistake, so please forgive me for this error.

**Comment by gzotti** [comment] 2018-09-26 10:31
Duplicate of #259.

**Closed by gzotti** 2018-09-26 10:31 UTC
Labels: duplicate, wishlist
