### ISSUE TITLE
Stellarium 0.21.2 Flicker on Fedora 35

### ISSUE THREAD

**Issue by Amanda-M-UK** [Stellarium/stellarium#2127] opened 2021-12-24 21:01 UTC
Running Stellarium 0.21.2 on Ferdora 35 (all updates applied) with an Intel GPU causes dreadful flicker. The machine is using a i7-9750H CPU with a UHD Graphics 630 GPU. Stellarium was working correctly until about two weeks but after updates to mesa it started to flicker.  I have also tried building Stellarium with source downloaded from github but this has the same problem.

A similar machine which uses a GeForce GTX 165 GPU and running Fedora 35 (all updates applied) works correctly.

I am attaching the log.txt and hope that somebody would be able to help with this problem. If you require further information then please let me know. 

[log.txt](https://github.com/Stellarium/stellarium/files/7775131/log.txt)

EDIT:

This problem is fully reproducible on both the GNONE (wayland and xorg) and XFCE desktop environments.

**Comment by gzotti** [comment] 2021-12-24 21:05
#2077?

**Comment by alex-w** [comment] 2021-12-25 08:15
> #2077?

Maybe. Both systems have Intel GPU and uses i915 driver. 

@Amanda-M-UK could you attach the log from x11 session also?

**Comment by alex-w** [comment] 2021-12-25 08:17
@Amanda-M-UK please check our AppImage also

**Comment by Amanda-M-UK** [comment] 2021-12-25 14:56
I've done more testing for this problem. 

I setup a fresh Fedora 35 system on another laptop (7 gen Intel). The specs for this machine are: Intel i7-7700 with an HD Graphics 630 (rev 04) GPU.  I ran Stellarium without updating and there was no flicker. I then updated Fedora and ran Stellarium again. This time, the flicker problem was evident. The following mesa packages were updated:

`
Upgrade  mesa-dri-drivers-21.3.2-1.fc35.x86_64                        @updates
Upgraded mesa-dri-drivers-21.2.5-2.fc35.x86_64                        @@System
Upgrade  mesa-filesystem-21.3.2-1.fc35.x86_64                         @updates
Upgraded mesa-filesystem-21.2.5-2.fc35.x86_64                         @@System
Upgrade  mesa-libEGL-21.3.2-1.fc35.x86_64                             @updates
Upgraded mesa-libEGL-21.2.5-2.fc35.x86_64                             @@System
Upgrade  mesa-libGL-21.3.2-1.fc35.x86_64                              @updates
Upgraded mesa-libGL-21.2.5-2.fc35.x86_64                              @@System
Upgrade  mesa-libgbm-21.3.2-1.fc35.x86_64                             @updates
Upgraded mesa-libgbm-21.2.5-2.fc35.x86_64                             @@System
Upgrade  mesa-libglapi-21.3.2-1.fc35.x86_64                           @updates
Upgraded mesa-libglapi-21.2.5-2.fc35.x86_64                           @@System
Upgrade  mesa-libxatracker-21.3.2-1.fc35.x86_64                       @updates
Upgraded mesa-libxatracker-21.2.5-2.fc35.x86_64                       @@System
Upgrade  mesa-vulkan-drivers-21.3.2-1.fc35.x86_64                     @updates
Upgraded mesa-vulkan-drivers-21.2.5-2.fc35.x86_64                     @@System
`

This problem is fully reproducible on a 10th gen and 7th gen Intel GPU laptop but not on a laptop with a GeForce GTX 165 GPU . It certainly looks like an issue with i915 GPUs. 

Here's a log.txt created from running Gnome with xorg.
[log.txt](https://github.com/Stellarium/stellarium/files/7775968/log.txt)

If you need any further information then please let me know.

**Comment by tuxedotje** [comment] 2021-12-25 22:30
$ stellarium (first startup of stellarium)
QSocketNotifier: Can only be used with threads started with QThread
Empty translation file for language  "en_US" in section "stellarium-scripts"
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  88 for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Oculars::validateAndLoadIniFile() found existing ini file version  3.1
Satellite has invalid orbit: "KESTREL EYE IIM (KE2M)" "42982"
Satellite has invalid orbit: "1998-067PN" "43638"
Satellite has invalid orbit: "CREW DRAGON DEMO-1 DEB" "44064"
Satellite has invalid orbit: "ENTRYSAT" "44429"
Satellite has invalid orbit: "STARLINK-1023" "44728"
Satellite has invalid orbit: "STARLINK-1044" "44749"
Satellite has invalid orbit: "STARLINK-1064" "44769"
Satellite has invalid orbit: "STARLINK-1097" "44916"
Satellite has invalid orbit: "STARLINK-1163" "45069"
Satellite has invalid orbit: "STARLINK-1632" "46170"
Satellite has invalid orbit: "STARLINK-1662" "46369"
Satellite has invalid orbit: "STARLINK-1745" "46377"
Satellite has invalid orbit: "STARLINK-1824" "46721"
Satellite has invalid orbit: "STARLINK-1897" "46761"
Satellite has invalid orbit: "STARLINK-1935" "46771"
Satellite has invalid orbit: "STARLINK-1937" "46773"
Satellite has invalid orbit: "STARLINK-1943" "46795"
Satellite has invalid orbit: "STARLINK-1787" "47125"
Satellite has invalid orbit: "STARLINK-1836" "47127"
Satellite has invalid orbit: "STARLINK-1855" "47142"
Satellite has invalid orbit: "STARLINK-2312" "47980"
Satellite has invalid orbit: "CYGNUS NG-16" "49064"
Satellite has invalid orbit: "ANTARES R/B" "49065"
Satellite has invalid orbit: "SL-8 R/B" "7004"

On Fdora 35 Gnome 41.

**Comment by uli13** [comment] 2021-12-26 22:20
I have the same flickering for some time using openSUSE Tumbleweed. System is regularly updated. However when I open stellarium from commandline with the following command it works OK: LIBGL_ALWAYS_SOFTWARE=1 stellarium

**Comment by gzotti** [comment] 2021-12-27 10:15
Thanks @uli13 for that tip. It apparently switches off hardware acceleration, but low framerate is better than flicker. This goes into the FAQ.

**Comment by alex-w** [comment] 2021-12-30 10:05
Duplicate of #2077

**Closed** 2021-12-30 10:06 UTC
Labels: duplicate

**Comment by alastair87** [comment] 2021-12-31 18:06
If you have a secondary nVidia GPU in the laptop, i.e. PRIME, you can also work around the issue by running it using that. E.g. on Manjaro I can do:

`prime-run stellarium`

**Comment by alex-w** [comment] 2022-01-04 07:05
@Amanda-M-UK would you try the patch from [issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/5731)?
