### ISSUE TITLE
Laggy Performance on Windows 11 Pro

### ISSUE THREAD

**Issue by psmelo1975** [Stellarium/stellarium#3675] opened 2024-03-19 16:02 UTC
Hi.

I installed the Stellarium 23.4 version on a Dell Latitude 7390. 8GB Ram, GPU UHD620, CPU I8350, outputting to an external monitor 2.5k resolution. Running Windows 11 Pro updated.

My problem is the very low frame rate. The best I can get is around 4 to 5 fps. With the CPU barely touched, and the GPU running at around 30%. 

I tested the other modes, like Single Buffer, Angle mode and so on. The results were the same or much worse, adding some issues with the DSO labels. 

Here is the log:
```
2024-03-19T15:42:32
Operating System: Windows 11 Version 21H2
Compiled using MSVC++ 16.10, 16.11 (Visual Studio 2019)
Qt runtime version: 6.5.3
Qt compilation version: 6.5.3
Addressing mode: 64-bit
Total physical memory: 8047 MB
Available physical memory: 1926 MB
Physical memory in use: 76%
Processor speed: 1896 MHz
Processor name: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
Processor speed: 1896 MHz
Processor name: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
Processor speed: 1896 MHz
Processor name: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
Processor speed: 1896 MHz
Processor name: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
Processor speed: 1896 MHz
Processor name: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
Processor speed: 1896 MHz
Processor name: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
Processor speed: 1896 MHz
Processor name: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
Processor speed: 1896 MHz
Processor name: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
C:\Program Files\Stellarium\stellarium.exe 
 -------------------------------------------------------------
[ This is Stellarium 23.4 (v23.4.0) - https://stellarium.org/ ]
[ Copyright (C) 2000-2023 Stellarium Developers               ]
 -------------------------------------------------------------
Writing log file to: C:\Users\Windows\AppData\Roaming\Stellarium\log.txt
File search paths:
 [0]: C:\Users\Windows\AppData\Roaming\Stellarium
 [1]: .
Config file: C:\Users\Windows\AppData\Roaming\Stellarium\config.ini
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
OpenGL module type: desktop OpenGL
Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
Default surface format:  QSurfaceFormat(version 3.3, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::CoreProfile)
OpenGL module type: desktop OpenGL
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL(windowWidth = 1834, windowHeight = 1012)
OpenGL supported version:  "3.3.0 - Build 31.0.101.2115"
Current Format:  QSurfaceFormat(version 3.3, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::CoreProfile)
Initialization StelMainView
Luminance textures are not supported
Maximum texture anisotropy: 16
Maximum 2D texture size: 16384
Detected: OpenGL 3.3
Driver version string: 3.3.0 - Build 31.0.101.2115
GL vendor: Intel
GL renderer: Intel(R) UHD Graphics 620
GL Shading Language version: 3.30 - Build 31.0.101.2115
GLSL Version Number detected: 3.3
GLSL version is fine, we should not see a graphics problem.
stel.OpenGLArray: Vertex Array Objects are supported
Detected a high resolution device! Device pixel ratio: 1.39583
Sky language: pt_PT
Empty translation file for language  "pt_PT" in section "stellarium-planetary-features"
Planetary features language: pt_PT
Application language: en
Scripts language: en
Cache directory: C:\Users\Windows\AppData\Local\stellarium\stellarium\cache
Loaded 252 countries
Loaded 193 regions
Loading Solar System data (1: planets and moons) ...
Loading from: ./data/ssystem_major.ini
Solar System has 83 entries.
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies) ...
Loading from: C:\Users\Windows\AppData\Roaming\Stellarium/data/ssystem_minor.ini
Solar System has 359 entries.
Loaded 276 Solar System bodies
File ssystem_minor.ini is loaded successfully...
qt.gui.imageio: libpng warning: iCCP: profile 'ICC profile': 'RGB ': RGB color space not permitted on grayscale PNG
Loading nomenclature for Solar system bodies ...
qt.gui.imageio: libpng warning: iCCP: profile 'icc': 'GRAY': Gray color space not permitted on RGB PNG
Loaded 15933 / 15946 items of planetary surface nomenclature
INFO: Cannot find these planetary objects to assign nomenclature items: "Dactyl, Dimorphos"
Loading star data ...
Loading star catalog: .\stars\default\stars_0_0v0_8.cat - 0_0v0_8; 4979 entries
Loading star catalog: .\stars\default\stars_1_0v0_8.cat - 1_0v0_8; 21806 entries
Loading star catalog: .\stars\default\stars_2_0v0_8.cat - 2_0v0_8; 150826 entries
Loading star catalog: .\stars\default\stars_3_1v0_4.cat - 3_1v0_4; 425807 entries
Finished loading star catalogue data, max_geodesic_level: 3
Loading scientific star names from .\stars\default\name.fab
Loaded 4942 / 4942 scientific star names
Loading scientific star extra names from .\stars\default\extra_name.fab
Loaded 26200 / 26200 scientific star extra names
Loading variable stars from .\stars\default\gcvs_hip_part.dat
Loaded 6862 / 6862 variable stars
Loading double stars from .\stars\default\wds_hip_part.dat
Loaded 22992 / 22992 double stars
Loading cross-identification data from .\stars\default\cross-id.dat
Loaded 108378 / 108378 cross-identification data records for stars
Loading parallax errors data from .\stars\default\hip_plx_err.dat
Loaded 117703 / 117703 parallax error data records for stars
Loading proper motion data from .\stars\default\hip_pm.dat
Loaded 117955 / 117955 proper motion data records for stars
navigation/preset_sky_time is a double - treating as jday: 2451514.25001
Loading DSO data ...
[...] Stellarium DSO Catalog, version 3.20 (standard edition)
Loaded 94660 DSO records
Loading DSO outline data ...
Loaded 98 DSO outline records successfully
Loading DSO discovery data ...
Loaded 183 / 183 DSO discovery records successfully
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from .\skycultures\modern\star_names.fab
Loaded 1104 / 1104 common star names
Loading DSO name data ...
Loaded 1338 / 1363 DSO name records successfully
WARNING - No position data for 25 objects: PGC 2798, PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 44750, PGC 54559, PGC 59117, PGC 59858, PGC 59953, PGC 69018, PGC 69877, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230, PGC 1000714, PGC 1436754, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124
Loaded 88 / 88 constellation records successfully for culture "modern"
Loaded 85 / 85 constellation art records successfully for culture "modern"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Error in asterism "TA6" - can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  88 for culture "modern"
Loaded 83 / 84 asterism records successfully for culture "modern"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
Loaded 73 / 74 asterism names
Initializing basic GL shaders... 
Creating GUI ...
Loading style file: :/graphicGui/normalStyle.css
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: C:\Users\Windows\AppData\Roaming\Stellarium\modules\Exoplanets\exoplanets.json
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: C:\Users\Windows\AppData\Roaming\Stellarium\modules\MeteorShowers\MeteorShowers.json
[MeteorShowersMgr] Version of the format of the catalog: 2
Loaded plugin "MissingStars"
[MissingStars] Loaded 56 extra stars (missing in main catalogs)
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] Loading catalog file: C:\Users\Windows\AppData\Roaming\Stellarium\modules\Novae\novae.json
Loaded plugin "Oculars"
Oculars::validateAndLoadIniFile() ocular.ini exists at: C:\Users\Windows\AppData\Roaming\Stellarium\modules\Oculars\ocular.ini . Checking version...
Oculars::validateAndLoadIniFile() found existing ini file version 3.1
Loaded plugin "Satellites"
[Satellites] loading catalogue file: "C:\\Users\\Windows\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
SSE: Comet cross-index data: Overwriting entry for "453P"
Creating scene FBO with size 2559.96x1412.58
Creating scene FBO with size 2559.96x1351.17
Initializing planets GL shaders... 
Dubious result: Landscape  "Guereins"  not calibrated. Opacity test represents mathematical horizon only.
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile

```

**Comment by 10110111** [comment] 2024-03-19 16:21
> Detected a high resolution device! Device pixel ratio: 1.39583

> Creating scene FBO with size 2559.96x1412.58

This is quite an odd ratio, which resulted in a strange FBO size. What is the exact physical resolution of your screen? What if you set the scaling factor to something nicer, like 150%?

**Comment by psmelo1975** [comment] 2024-03-19 19:09
> > Detected a high resolution device! Device pixel ratio: 1.39583
> 
> > Creating scene FBO with size 2559.96x1412.58
> 
> This is quite an odd ratio, which resulted in a strange FBO size. What is the exact physical resolution of your screen? What if you set the scaling factor to something nicer, like 150%?

I set the scale to 100%, restarted, and the frame rate raised to around 8.6 fps with the Atmosphere and the Artificial SAtellites disabled. When zoom in, the frame rate increases to 10 fps.





> Is it also 5fps when moving the scene by mouse dragging? Configure in the settings dialog.
> 
> Maybe it's just too many pixels for the Intel GPU? Try reducing resolution (https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#windows-gui-scaling)

Dragging the mouse doesn't affect the frame rate. 
Reducing the Stellarium resolution increased a little bit the frame rate, but not that much. 

The odd thing is that the GPU doesn't pass the 40% of use.

**Comment by gzotti** [comment] 2024-03-19 22:11
What about the CPU load caused by Stellarium? Is it much higher than 12,5% (indicating main thread occupying one core)? I mean, my really terrible 1GHz dual-core netbook from 2013 has 8fps (on a 1366 screen). If you don't need them, disable satellites. Use only few text labels (you mentioned DSO labels), these are surprisingly costly.

**Comment by psmelo1975** [comment] 2024-03-20 14:35
> What about the CPU load caused by Stellarium? Is it much higher than 12,5% (indicating main thread occupying one core)? I mean, my really terrible 1GHz dual-core netbook from 2013 has 8fps (on a 1366 screen). If you don't need them, disable satellites. Use only few text labels (you mentioned DSO labels), these are surprisingly costly.

The CPU is under 4%.

Disabling DSO Labels doesn't change the frame rate.

**Comment by gzotti** [comment] 2024-03-20 14:52
Switching between 5000 DSO labels and none has a high impact. 2-5 DSOs of course is not perceivable.
If this means 1 core is working at 1/3 load, no other component is maxed out, and you have not limited frame rate in the settings dialog, I am out of ideas currently. Did you try 150% scaling in addition to the 100% run?

**Comment by 10110111** [comment] 2024-03-21 09:26
Does this happen on a clean install with the default settings?

Intel UHD Graphics 620 is what I have on my laptop, and it doesn't seem too slow (though I'm using it on a FullHD screen). But, what if you try `--low-graphics` command-line option available in the latest weekly build?

Also, please tell the exact physical resolution (or model) of your monitor.

**Comment by psmelo1975** [comment] 2024-03-21 23:36
> Did you try 150% scaling in addition to the 100% run?

Yes, but the difference is barely visible. 

> Intel UHD Graphics 620 is what I have on my laptop, and it doesn't seem too slow (though I'm using it on a FullHD screen). But, what if you try `--low-graphics` command-line option available in the latest weekly build?

How do I install the weekly build in Windows?



> Also, please tell the exact physical resolution (or model) of your monitor.
It is an AOC 32 2560x1440 pixels 75Hz

**Comment by 10110111** [comment] 2024-03-22 06:58
> How do I install the weekly build in Windows?

Get an installer [here](https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot) and install it as usual.

**Comment by psmelo1975** [comment] 2024-03-24 17:48
OK, some interesting news.

Firstly, I installed the weekly build qt5 version. On this one, I got spikes of around 28 fps when dragging the mouse, and after, a steady 17,9 fps.  

Secondly, I installed the qt6 version, and the performance was pretty much the same I got with the stable version. 

So, I reinstalled the qt5 version and launched. And I got, more or less, the not so good performance of the qt6 version... I closed and opened again, and the performance recovered, with 17,9 fps and spikes of around 28fps when dragging the mouse. 

On both versions, the CPU is around 3-4%, and the GPU around 40% of use.

So, this looks a bit weird...

**Comment by gzotti** [comment] 2024-03-24 18:19
That indicates you have native 28fps when interacting, which is adequate for the Intel GPU, and idle rate of 18fps which is probably default. You can set the latter in the Configuration/Tools dialog.

**Comment by psmelo1975** [comment] 2024-03-24 18:45
> That indicates you have native 28fps when interacting, which is adequate for the Intel GPU, and idle rate of 18fps which is probably default. You can set the latter in the Configuration/Tools dialog.

I searched over the config.ini file, but couldn't find the idle rate or any frame rate related parameter. What am I missing?

**Comment by gzotti** [comment] 2024-03-24 18:52
You did not read instructions properly.
>You can set the latter in the Configuration/Tools dialog.

**Comment by psmelo1975** [comment] 2024-03-24 20:05
> You can set the latter in the Configuration/Tools dialog.

OK, sorry, I got it know. But the settings are 18 fps minimum and 1000 maximum.

**Comment by gzotti** [comment] 2024-03-24 20:13
Yes, _intents_. Low to conserve energy, high for fluid display. 18 can usually be met, 1000 usually won't (just means as fast as system can go).

**Comment by gzotti** [comment] 2024-05-11 15:01
@psmelo1975 does it work OK for you now, can we close this?

**Comment by gzotti** [comment] 2024-06-21 19:50
Apparently we can close this.

**Closed by gzotti** 2024-06-21 19:50 UTC
Labels: state: waiting feedback
