### ISSUE TITLE
Red Sky at day

### ISSUE THREAD

**Issue by GeoGeorge200** [Stellarium/stellarium#924] opened 2020-01-09 19:00 UTC
### Expected Behaviour
Earth's daytime sky to be blue
### Actual Behaviour
Sky is pink/red 
![Stellarium Daylight Red](https://user-images.githubusercontent.com/59703561/72095704-990b3b00-32de-11ea-91b6-bc8a7cff72e2.png)

### Steps to reproduce
start the program. changing the landscape to any other of the default location results in pink sky during the day. 

### System
*Stellarium 0.19.3

* Operating system: Linux Mint 19.3 Cinnamon

* Graphics Card: 
          Device-1: NVIDIA GF119 [GeForce GT 610] vendor: eVga.com. driver: nouveau v: kernel 
           bus ID: 01:00.0 chip ID: 10de:104a 
           
           Device-2: NVIDIA GK208B [GeForce GT 710] vendor: Micro-Star MSI driver: nouveau 
           v: kernel bus ID: 02:00.0 chip ID: 10de:128b 
           
           Device-3: AMD Cedar [Radeon HD 5000/6000/7350/8350 Series] vendor: ASUSTeK 
           driver: radeon v: kernel bus ID: 09:00.0 chip ID: 1002:68f9 
           Display: x11 server: X.Org 1.20.4 driver: ati,modesetting,radeon unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: NVD9 v: 4.3 Mesa 19.0.8 direct render: Yes 

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/4042009/log.txt)

If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by A-j-K** [comment] 2020-01-09 19:17
I note Mint Linux released its 19.3 version within days of Stellarium releasing 0.19.3, co-incidence?

**Comment by gzotti** [comment] 2020-01-09 19:57
For some time, we we have been following a scheme:
"0" while Stellarium is not yet accurate enough for us.
"19" derives from the calendar year 2019.
"3" is the fourth release in that year, around Winter solstice.

I cannot speak for Linux Mint, but my guess is that 19 also derives from the year.
Else, a temporal coincidence is ... coincidential.

**Comment by A-j-K** [comment] 2020-01-09 20:15
@gzotti  I wasn't referring to the release numbers but the dates. Two things have potentially changed at a similar time which always makes it more awkward to figure out where the problem is.

**Comment by gzotti** [comment] 2020-01-09 20:46
We had a pink sky report in #6 already. I can only guess the problem is in the GPU driver and the particular GPU model. 
I just realized you have 3 GPUs, mixed Geforce and AMD. I have never tried mixing vendors. Maybe using the binary NVidia drivers work?

**Comment by GeoGeorge200** [comment] 2020-01-10 03:54
Using the NVIDIA driver resolved the problem. Thank you. I never thought to use proprietary drivers. I've used Linux Mint for more than 10 years using noveau for the graphics driver and never had problems, even when playing opengl games. Also, Stellarium seemed to render the landscapes in the correct colors. I figured that in my noobness I had somehow misconfigured something without realising it. Again a hearty THANK YOU!

**Comment by sebalis** [comment] 2020-03-19 23:14
I’ve just seen the same problem on my Dell Latitude E6420 running Arch Linux. The graphics card is given by lspci as “NVIDIA Corporation GF119M [NVS 4200M]” and I was trying to see how my system would run using nouveau rather than the non-free nvidia-390xx package. I’d be happy to see this resolved because the NVIDIA driver has issues beyond being non-free and it would be great to have the option of removing it. But I can’t do that while Stellarium shows me a pink sky, that’s scary. :-) I’d be very glad if this issue could be reopened and not regarded as “done” while the nouveau driver has this issue.

**Comment by gzotti** [comment] 2020-03-20 08:30
If you can develop a solution yourself or find an expert for issues related to the nouveau driver and GF119 chip to do it, we could add it. None in our huge team of 2 has this expertise.

**Comment by sebalis** [comment] 2020-03-20 18:22
Thanks for the response. Unforttunately I don’t think I can contribute to solving this. Perhaps the bug should be kept open because the move to the non-free driver is more of a workaround, but I’m in no position to tell you how to administrate your project. Stellarium is a wonderful piece of software, I am more than grateful for its existence and to everyone who works on it.

**Comment by alex-w** [comment] 2020-03-20 18:26
The issue can be reproduced on nouveau drivers only and I think it’s bug in drivers - the bad guy is not Stellarium

**Comment by sebalis** [comment] 2020-03-20 18:34
Would it help if I filed a very simple issue at https://gitlab.freedesktop.org/xorg/driver/xf86-video-nouveau/issues pointing to this one? The issues there seem rather lower-level than mentioning that a certain piece of software has a problem.

**Comment by alex-w** [comment] 2020-03-20 18:59
Why not, go ahead!

**Comment by sebalis** [comment] 2020-03-20 19:01
Done: https://gitlab.freedesktop.org/xorg/driver/xf86-video-nouveau/issues/524

**Comment by 10110111** [comment] 2020-12-09 16:14
Actually, I wouldn't pay too much attention to `nouveau`. I have experienced too many issues with it—not only in OpenGL implementation quality, but also simply HW stability—to even give it a chance on any new OS install.

The choice is like this: if you want adequate performance, power efficiency,  and general stability, use the non-free `nvidia` blob. It does have its issues, but they are usually not show stoppers.

If you want the supposed freedom, try `nouveau`. But beware of the fact that this freedom is very limited: the only docs available to nouveau developers are the ones they generated by reverse engineering, plus [a handful of data points](https://github.com/nvidia/open-gpu-doc) given officially by Nvidia—and even this little amount of official docs (most of them) appeared [not too long ago](https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-Open-GPU-Docs). The result is poor stability (hangs, screen corruption etc.), [lack of proper power management](https://wiki.archlinux.org/index.php/nouveau#Power_management) leading to high battery use, and bad rendering in OpenGL apps.

The worst thing Stellarium could do here, IMHO, is insertion of some kludge to its codebase to work around the driver issues.

**Comment by gzotti** [comment] 2020-12-09 16:28
Since March we actually don't pay much attention to this :-) This is what we are saying. Driver issues should be fixed by the vendors, not by us.

**Comment by 10110111** [comment] 2020-12-09 16:30
Yeah, I just noticed the `help wanted` tag and expressed my opinion about potential kludge that could enter Stellarium by this "help" :)

**Comment by gzotti** [comment] 2020-12-09 16:36
If somebody *really* happens to know what to do, easily... like flip any OpenGL variable which usually causes no harm, or such. (something around RGB/BGR order?) 
Same goes for the planet shader problem which fails to compile on some systems and then shows black planets.

**Comment by 10110111** [comment] 2020-12-09 16:43
Well, here the problem is that the whole red channel of the sky is blown to 0xFF, which doesn't look like any kind of the application problem.

And this:

> like flip any OpenGL variable which usually causes no harm, or such

is definitely a bad fix: it will break back, possibly in a different way, when you change something else. Working around driver bugs is a thankless work.

**Comment by sebalis** [comment] 2020-12-09 16:55
Let me make you aware of one potential showstopper of the nvidia driver: It might not be available. The nvidia-390xx package on Arch Linux is practically unmaintained at the moment. It was moved to the AUR [in March](https://lists.archlinux.org/pipermail/arch-dev-public/2020-March/029895.html) and lost its AUR maintainer [in October](https://aur.archlinux.org/pkgbase/nvidia-390xx/). There is what you call an emergency maintainership by an Arch developer who does not have a device with that hardware himself. With every move to a new minor kernel version there is the risk that the package will not work anymore.

Obviously this is nothing I can hold you responsible for (and I did try to help by filing the issue at the nouveau project, see earlier comment) but it’s just to make you see what the issue might be. I may have to choose between switching hardware or giving up on Stellarium altogether, which I’d be very sad about.

**Comment by gzotti** [comment] 2020-12-09 18:10
I did not investigate if red=0xFF. If yes, it's not RGB/BGR order. So we cannot do anything, really, as sad as it may be. Some people still complain about Stellarium's (actually: Qt5's) min hardware requirements. Likewise, for good contemporary graphics you may need one PC per decade. (Or a Raspberry Pi...)

**Comment by gzotti** [comment] 2022-09-17 11:04
Is this still open with nouveau systems?

**Comment by sebalis** [comment] 2022-10-09 03:11
Stellarium looks fine for me now on Arch with the nouveau driver – both on the Dell Latitude E6420 where I originally saw this issue, and on an even older E6510 where the non-free replacement would be nouveau-340xx.

**Comment by gzotti** [comment] 2022-10-09 08:28
Thank you for this info update. We may close it then!

**Closed by gzotti** 2022-10-09 08:28 UTC
Labels: help wanted, importance: medium

**Comment by sebalis** [comment] 2022-10-09 11:04
I have passed this information on at https://gitlab.freedesktop.org/xorg/driver/xf86-video-nouveau/-/issues/524 (the issue I had opened).
