### ISSUE TITLE
What quantity is actually meant by "light pollution luminance"?

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#1586] opened 2021-04-04 18:09 UTC
Working on integrating light pollution model into Stellarium, I'm struggling to understand the API of `LandscapeMgr`. Namely, there's a function, [`LandscapeMgr::setAtmosphereBortleLightPollution(int)`](https://github.com/Stellarium/stellarium/blob/8a4dc037de3515354a9f8a9ab322c953454cb05c/src/core/modules/LandscapeMgr.cpp#L1147), which calls [`LandscapeMgr::setAtmosphereLightPollutionLuminance(float)`](https://github.com/Stellarium/stellarium/blob/8a4dc037de3515354a9f8a9ab322c953454cb05c/src/core/modules/LandscapeMgr.cpp#L1135) with the argument that apparently converts Bortle index into some kind of luminance:
```cpp
qMax(0.f,0.0004f*powf(bIndex-1, 2.1f))
```
In math form it'd be

4×10<sup>-4</sup>(*n*-1)<sup>2.1</sup>,

where *n* is the Bortle index.

But when I take the "Approx. SQM" values from the [Wikipedia article on Bortle scale](https://en.wikipedia.org/wiki/Bortle_scale) and convert them to cd/m<sup>2</sup> using the formula [at this page](http://unihedron.com/projects/darksky/magconv.php), I get the following results (assuming the formula above yields value in cd/m<sup>2</sup>, which is expected due to [this comment](https://github.com/Stellarium/stellarium/blob/8a4dc037de3515354a9f8a9ab322c953454cb05c/src/core/modules/Atmosphere.hpp#L79)):

![plot](https://user-images.githubusercontent.com/6376882/113517297-bbdeda80-9587-11eb-8fcc-e5b634751906.png)

Here the gray area is the expected range of luminances from the table in Wikipedia, and the blue curve is the output of the above expression from `LandscapeMgr`.

As you can see, the line doesn't really match the area. Even if I try multiplying the `LandscapeMgr`'s expression by a constant (assuming it's just some proportional units that are wrong), it obviously won't fit in the expected area, here's an example of the factor 0.2:

![plot](https://user-images.githubusercontent.com/6376882/113517254-70c4c780-9587-11eb-9ed6-8da418096251.png)

OK, SQM includes some background luminance, so we might want to subtract the minimum value of luminance corresponding to magnitude 22 to get light pollution itself. Here's the result:

![plot](https://user-images.githubusercontent.com/6376882/113517508-12004d80-9589-11eb-8f43-0b196691225a.png)

This still doesn't look quite correct. Even if I try to fit a multiplicative constant, the result is unsatisfactory:

![plot](https://user-images.githubusercontent.com/6376882/113517543-3b20de00-9589-11eb-8ec7-62ee01f88bbb.png)

So what is the quantity that `LandscapeMgr::setAtmosphereLightPollutionLuminance()` actually expects, and what units should it use? Does the code in `LandscapeMgr::setAtmosphereBortleLightPollution()` make any sense?

**Comment by gzotti** [comment] 2021-04-04 18:34
Good questions. It seems this code is unchanged since 2007, and was never properly documented. :-( Welcome to the reverse-engineering staff...

**Comment by 10110111** [comment] 2021-04-04 21:53
Hmm, given fb4e01ff129d79f58bb362312eda2ebfdfa0e37c and 75169948964cc3592f191075b81bfd486d4b0fc5, this seems to have been manually tuned to achieve _something_...
Maybe it should be simply replaced with a physically-sensible formula (or simply a table) matched to the expected magnitudes.

**Comment by gzotti** [comment] 2021-04-04 22:08
@xalioth ?
I am in contact with an LP expert who has some reservation against the Bortle scale. But I don't find time to do anything about it now.

**Comment by xalioth** [comment] 2021-04-05 06:29
Hi, sorry I missed this message before, thanks Georg for the reminder! 
I kind of remember having created the simple formula originally based on the expected luminance values for each step, but at the end the complex feedbacks between sky brightness/eye adaptation/tone mapping/gamma made it look not as it was expected from the description of the Bortle scale, and I basically had to manually tune everything, because it the end it has to look good also.. 

This hand-tuning may well have come from one or more errors burried in the sky brightness/eye adaptation/tone mapping so as Ruslan says, you should definitely try to start from a physically-sensible formula and keep hand tuning as a last resort solution..

I also always wondered, but never really found out what effect the "light pollution" has on the incoming light from stars. Is it only an extra luminance added to the stars light, or is is also extinction ? I.e when zooming in with a good telescope, should a faint star still be visible even with a lot of light pollution or does it really disappear (poisson noise ?).

**Comment by 10110111** [comment] 2021-04-05 09:36
> I also always wondered, but never really found out what effect the "light pollution" has on the incoming light from stars. Is it only an extra luminance added to the stars light, or is is also extinction ?

Light pollution is not a kind of aerosol—it's just scattered light from street lighting. So it doesn't add to extinction.
Now, being in a city doesn't add _only_ light pollution. Of course you'll have urban aerosols, which will affect both extinction and scattering coefficient. But this is quite separate, although correlated to light pollution, kind of effect.

> I.e when zooming in with a good telescope, should a faint star still be visible even with a lot of light pollution or does it really disappear

If we ignore urban aerosols, then this will work pretty much the same way as with scattered moonlight, just with different background brightness (and spectrum) depending on the place.

> you should definitely try to start from a physically-sensible formula and keep hand tuning as a last resort solution..

Do you think we can safely start with making a physically-sensible implementation of `setAtmosphereBortleLightPollution`? Or is there something we should fix to compensate the reduction of light pollution that will happen?

BTW, Bortle scale is rather coarse, giving a _range_ of magnitudes rather than a value. In Stellarium what should be taken as the luminance at each index? middle of the range? a smooth fitting curve?

**Comment by alex-w** [comment] 2021-04-05 09:46
>BTW, Bortle scale is rather coarse, giving a range of magnitudes rather than a value. In Stellarium what should be taken as the luminance at each index? middle of the range? a smooth fitting curve?

I think we should switch to physical model for light pollution and add Bortle index for backward compatibility with middle of the range (NELM as primary luminosity scale?).

**Comment by 10110111** [comment] 2021-04-05 10:31
> I think we should switch to physical model for light pollution and add Bortle index for backward compatibility with middle of the range (NELM or SQM as primary "luminosity scale"?).

OK, I guess it's the same idea as expressed by @Atque in https://github.com/Stellarium/stellarium/issues/624#issuecomment-810961413.

I'm not sure how to organize the GUI though. Would this be good enough:

![Screenshot - 050421 - 13:28:59](https://user-images.githubusercontent.com/6376882/113565068-12ddc180-9613-11eb-94e5-37ee0446aa22.png)

Or should the Bortle index be shown somewhere?

**Comment by xalioth** [comment] 2021-04-05 11:03
I think most users are guided by the little description text associated
with each of the steps rather than a Bortle index or exact luminance value,
so my 2 cents is that a slider with this info should be preserved, and the
rest is just extra.

**Comment by Atque** [comment] 2021-04-05 14:04
@10110111 Keep in mind that the SQM values give the zenithal brightness, so horizons will be brighter.

**Comment by gzotti** [comment] 2021-04-05 18:50
There are several scales possible. mag/arcsec^2, cd/m^2, Bortle index, ... To catch all, conversion and display from the actually stored (continuous, float/double) value to the others would be great. Or a switch to configure one as user preference. Not sure if cd/m^2 or mag/arcsec^2 is the better or wider used one.

**Comment by 10110111** [comment] 2021-04-05 20:13
OK, here's my proposal for the GUI. The style in the screenshots is non-Stellarium, because it's just a preview from Qt Designer, but I hope you won't be disoriented :) .

* Automatic is automatic, no additional controls

![Screenshot - 050421 - 23:01:32](https://user-images.githubusercontent.com/6376882/113620901-9a532100-9663-11eb-846a-af754a3c4212.png)

* Manual is an "analogue" slider, i.e. not limited to integral Bortle classes, but the tooltip does show the Bortle classification of the analogue value chosen, with the NELM being calculated for this exact value instead of range

![Screenshot - 050421 - 22:52:38](https://user-images.githubusercontent.com/6376882/113621038-cbcbec80-9663-11eb-9245-d28fbc2442ac.png)

* SQM-read value is just entered in the units chosen

![Screenshot - 050421 - 22:58:09](https://user-images.githubusercontent.com/6376882/113621048-d090a080-9663-11eb-94d1-7e05a19633c4.png)

Wording of the options might be not perfect, I'm open to suggestions. Of course, better proposals for the GUI layout are also welcome.

**Comment by axd1967** [comment] 2021-04-06 18:17
I'm just playing with light pollution in landscapes, and have the impression that the parameter is not taken into account?

```
[location]
planet = Earth
country = Belgium
state = 
name = Campus Schoonmeersen Zuid

timezone = Europe/Brussels

latitude = +51.027716 
longitude = +3.704905
altitude = 10

light_pollution = 9

```

![image](https://user-images.githubusercontent.com/3529789/113758840-ab0f9f80-9714-11eb-8316-b07d33b02bc7.png)

**Comment by alex-w** [comment] 2021-04-06 18:36
@axd1967 why you expect something else if you have disabled the option to use location settings from the landscape (hint: see "Position from landscape" setting in Landscape tab)?

P.S. After a series of renaming of this setting we missed info that we are using definition of the light pollution from landscape settings when this option is enabled. :(

**Comment by axd1967** [comment] 2021-04-06 19:26
disregard, my mistake - I was using the wrong landscape.ini file. the feature works fine.

**Comment by 10110111** [comment] 2021-04-07 13:39
This does remind me though, that landscapes can also set light pollution level, and currently do it via the Bortle scale.

Is it very important to keep backwards compatibility here, or can a newer version of landscape config require another key for light pollution — e.g. `light_pollution_cdm2`, or `light_pollution_mas2`, and ignore `light_pollution` (possibly with a warning printed to the log)?

**Comment by gzotti** [comment] 2021-04-07 13:54
We can keep the light_pollution=<bortleindex>, but translate to a value which should fit to the corrected real world values. And for future use, add another (or even both!) config entries with double values. 

if cdm2 available use cdm2, 
else if mas2 available use cdm2(double mas2), 
else if bortle available use cdm2(int bortle) 
else don't change current setting.

**Comment by 10110111** [comment] 2021-04-09 16:40
NELM is a mess, see [my post at Astronomy.StackExchange](https://astronomy.stackexchange.com/q/43313/735). I don't know what to use for the calculations. Currently I'm leaning towards equation (18) from [1], because it at least can handle Bortle class 1, but I don't really know how valid it is.

If anyone can answer there, please do.

#### References
1. Schaefer, B. E.. [_"Telescopic limiting magnitudes"_](http://adsbit.harvard.edu/cgi-bin/nph-iarticle_query?bibcode=1990PASP..102..212S&db_key=AST&page_ind=0&plate_select=NO&data_type=GIF&type=SCREEN_GIF). Astronomical Society of the Pacific, Publications (ISSN 0004-6280), vol. 102, Feb. 1990, p. 212-229.

**Comment by RebBlumstein** [comment] 2021-04-21 21:35
(Thanks to @gzotti for making that connection!)

Could the datasets used at www.lightpollutionmap.info be useful, or do you guys already have this data?

My only concern (after what feels like a partial waste of a few hours) as of now was that if you use the checkbox to override light pollution ("take from locations database") then it only does so for locations in the database already (it looks like the number defaults to 2 when you use a custom set of coordinates).

There should be enough data to make a rough approximation no matter where they select on the map. Otherwise, when you select a new location you'll get the (_unexpected_) default sky brightness.

But, given other people's comments here, perhaps the Bortle class isn't enough to go on. If you want Stellarium's sky to look like my sky, then you have to use some sort of function that maps the sky-brightness to Altitude/Elevation angle (theoretically also Azimuth, for example if there's a much brighter city in the distance then it will add brightness in only one direction, although I imagine modeling _that_ would be beyond the project's scope). The math seems out of my domain, so maybe I'm missing something...

**Comment by gzotti** [comment] 2021-04-21 22:21
The location database is a text list of point data. There is no interpolation between coordinates within that list, and connection to any global map of light pollution at this time. Your map is interesting. As said, this is a feature for the future. As you found, the default Bortle value if you just click on the map is 2, assuming that you usually try to find a dark location to observe. 
It may be possible to develop even a website that serves the LP map and then sets the correct location and Bortle value in a Stellarium running on localhost via RemoteControl (HTTP) API. However this is currently out of scope for us.

**Comment by RebBlumstein** [comment] 2021-04-21 23:54
I get the justification for the default value, but it looks like anyone who lives in a metropolitan area is going to have a major difficulty getting to a location far enough away for the number to go back to 2. In fact, based on that map, I think most people in the developed world would find it difficult to reach a location that scores below a 4. The problem is that more and more people live within the growing urban sprawls, and the pockets of less light pollution are fewer and farther between.

A noteworthy exception at present would be if you live in the Western half of the USA, where even city-dwellers will usually be able to drive 1–2 hours to find a really dark Bortle-2 place. This is also true in some regions in Europe (e.g. Spain or Southern France), whereas almost every citizen in my country would need to travel 3+ hours to get to a Bortle-2. I can't imagine many Londonites driving 4 hours to Wales, or Parisians travelling 3 hours to Morvan Regional Natural Park. I'm sure most serious astonomers _will_, of course, but I don't think everyone has that option (I can count on one hand the number of times I've been to a Bortle-3 or less).

Based on that, I would suggest these one-liner code changes:
- Set the default light pollution to 4 if you're not going to make an estimate (an estimate that's admittedly expensive code-wise and data-wise, and not used that much by an end user, since their city is probably already in the list).
- Make the "take from locations database" override the default.

And this slightly longer one:
- There should really be a way of saving the light pollution setting for a given location (but I'm not sure where you'd enter that in terms of UI).


I'm not making up the numbers above, take a look at these:
(Roughly: Light Blue is a Bortle-3; Dark Blue is a Bortle-2; most people can't get to Dark Blue very easily)
![asia-south](https://user-images.githubusercontent.com/32102773/115635488-7efb3d80-a314-11eb-953a-4ef15212cd2b.jpeg)
![eu](https://user-images.githubusercontent.com/32102773/115635493-815d9780-a314-11eb-9c64-cf51afc19ed4.png)
![usa](https://user-images.githubusercontent.com/32102773/115635506-87ec0f00-a314-11eb-8924-169a394cbc1f.png)

**Comment by gzotti** [comment] 2021-04-22 00:20
I have seen these frightening maps of energy waste and human stupidity. However, Stellarium wants to show a good sky by default, not a ruined one. It would make a nice contribution if somebody with enough free time would add some interface to improved maps to this open-source project. These maps may have various themes (topography, elevation, roadmap, light pollution, ...), some vector shapes to identify the correct time zone, and a few other niceties. These can be further discussed in your issue #1619, not this one which is about LP units.

**Closed** 2022-02-12 11:36 UTC
Labels: in progress
