### ISSUE TITLE
help dialog does not take alternative shortcuts into account

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#2944] opened 2022-12-28 11:51 UTC
### Expected Behaviour
Dynamic list is shown in the Help dialog; alternatively, the dialog is simplified

### Actual Behaviour
Hardcoded: 
https://github.com/Stellarium/stellarium/blob/647b3f2e6f4583bd890604a5facfbae8dbcea1a4/src/gui/HelpDialog.cpp#L282-L483

### Proposition

1. Refer to the Shortcut Editor F7 (e.g. add a button?) rather than copy everything; the Shortcut Editor provides in itself quite some documentation to the user
2. Document only those actions that cannot be edited by the user (or presented in the Shortcut Editor), such as mouse actions, special actions

**Comment by gzotti** [comment] 2022-12-28 12:16
What is hardcoded? Refer to the line number in code.

**Comment by 10110111** [comment] 2022-12-28 12:39
I changed "Add one solar day" from the default <kbd>+</kbd> to <kbd>=</kbd>, and this got reflected in the _Help_ dialog. What actual problem do you experience?

**Comment by axd1967** [comment] 2022-12-28 13:20
> I changed "Add one solar day" from the default + to =, and this got reflected in the _Help_ dialog. What actual problem do you experience?

Me? 
None. I have been using Stellarium for many years. I just notice a bug; and it's not because it doesn't do anything that it can't be a bug.

But I put myself in the shoes of less experienced users, that might get confused.
And I notice useless code. I notice a relatively easy to solve issue, ideal for new developers.

_And every time the word "you" creeps in, a conversation risks to degenerate into name calling and personal attacks. That's where the conversation ends._

**Comment by 10110111** [comment] 2022-12-28 13:34
> Me? None. I have been using Stellarium for many years. I just notice a bug

Well, if you notice a bug but don't experience (and apparently refuse to check for) any problems caused by it, how are we expected to reproduce this?

> And every time the word "you" creeps in, a conversation risks to degenerate into name calling and personal attacks.

This depends on the attitude of the actual actors of the conversation. 'You' is not a curse word to avoid in polite conversations.

**Comment by gzotti** [comment] 2022-12-28 13:38
Easy to solve what? A non-problem? Show the live-edit page of all possible actions with their hotkeys (a configuration option for pretty advanced users) to first-time users is certainly not a solution over presenting the existing list in a well-structured page. 

Please report actual errors in the existing program, not what you would change in code or UI. We really have seriously not enough time to permanently get bombarded with these distracting suggestions, even if you think they are meaningful. 

From https://en.wikipedia.org/wiki/Troll_(slang):

> In slang, a troll is a person who posts or makes inflammatory, ... digressive, extraneous, or off-topic messages online ... or in real life, with the intent of provoking others into displaying emotional responses, or manipulating others' perception. The behavior is typically for the troll's amusement, or to achieve a specific result such as disrupting a rival's online activities or purposefully causing confusion or harm to other users online.


Does anybody see a connection here?

**Comment by 10110111** [comment] 2022-12-28 13:55
So far, the title:

> help dialog does not take actual shortcuts into account

appears to be wrong, and the expected behavior:

> Dynamic list is shown in the Help dialog

is exactly what I observe.

If the OP can't prove that the bug actually exists, this issue should be closed as invalid.

**Comment by axd1967** [comment] 2022-12-28 14:33
**This is outrageous. Not only is this a bug, but the suggestions are also thrown away.**

Here is illustrated one example: the user shortcut is not in the dialog. Not even when restarting the app.

![image](https://user-images.githubusercontent.com/3529789/209827585-826294fc-e8db-459a-8daf-778834792a73.png)

@xalioth

**Comment by alex-w** [comment] 2022-12-28 15:09
> **This is outrageous. Not only is this a bug, but the suggestions are also thrown away.**
> 
> Here is illustrated one example: the user shortcut is not in the dialog. Not even when restarting the app.
> 
> ![image](https://user-images.githubusercontent.com/3529789/209827585-826294fc-e8db-459a-8daf-778834792a73.png)

When you using own terms and redefine the standard definitions of existing words please share new definitions and explanations of your terms to ability understanding you for everybody. Please learning writing texts for all people, not for you only. 

When 2 developers clarified what exactly works wrong with you, they received only a mocking text in response. If you take the trouble to read the text of your first and last message (which I have quoted here), you will see that these are completely different problems.

**Comment by 10110111** [comment] 2022-12-28 15:17
So, is the lack of the alternative shortcut in the _Help_ dialog the whole point of this issue? If so, the whole OP should be rewritten, because it describes a different—non-existing—problem.

**Comment by gzotti** [comment] 2022-12-28 16:16
The current implementation is not bugged. Actual issue: "Add secondary keyboard shortcut to keyboard shortcut list in help dialog."

**Comment by axd1967** [comment] 2022-12-28 16:19
> So, is the lack of the alternative shortcut in the _Help_ dialog the whole point of this issue? 

Yes. 

The fact that the actual shortcuts are not shown in the Help dialog is a **bug**, even if that dialog correctly shows other shortcuts. 

More specifically, the **primary** shortcuts are dynamically taken into account.

It appears to happen for the **alternative** shortcuts, which also are actual shortcuts. Actual, as in "currently active".

Issue title rephrased accordingly.

**Closed** 2022-12-28 17:44 UTC
Labels: enhancement, importance: low
