### ISSUE TITLE
Info display setting not saved in 24.3 on Windows

### ISSUE THREAD

**Issue by EricMyers47** [Stellarium/stellarium#3961] opened 2024-10-25 13:53 UTC
### Expected Behaviour

If I change the Information display in the upper left corner to Short or Customized and then press "Save settings" I expect to have that same display of information when I start a new session.  That is how it's worked in the past and that is how it works even now with 24.3 on a Mac.

### Actual Behaviour
In Stellarium 24.3 on Windows  even if I use "Save settings", the next time I start Stellarium the Information display shows Everything.   If I then change to Custom the previous configuration I had set is still there, it just was not used at startup. 

Not an issue with 24.2 on Windows.

### Steps to reproduce

Change the Information display to anything other than Everything, press "Save settings", quit Stellarium and then start it up again.  The Information display is back to Everything.

Tested on 24.3 and 24.2 and only appears in 24.3.

Saving the View does not have a problem, so I think this is different from #3959 

### System
* Stellarium version: 24.3. (not a problem in 24.2)
* Operating system: Windows 10 (not a problem on Mac). Not yet able to test on Windows 11.
* Graphics Card:  various
* Screen type (if applicable): N/A

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment] 2024-10-25 14:19
Duplicate of #3910

**Closed** 2024-10-25 14:20 UTC
Labels: duplicate, state: published
