### ISSUE TITLE
Unable to add asteroid from MPC

### ISSUE THREAD

**Issue by evaldasgr** [Stellarium/stellarium#3885] opened 2024-09-06 13:53 UTC
Hello. I'm attempting to add asteroid 697402 Ao, but I'm unable to do so. The data is from [MPCORB.DAT](https://www.minorplanetcenter.net/iau/MPCORB/MPCORB.DAT), but since Stellarium hangs when loading this large file, I'm trying to load a separate file with just the data for this asteroid. After specifying the file and pressing "Get orbital elements" nothing happens, and the following error is logged:
`readMpcOneLineMinorPlanetElements(): "~0K8Q" is not a valid number or packed IAU designation`
"~0K8Q" is indeed the correct packed designation for this asteroid, and can be decoded by tools such as [Pack and unpack MPC designations](https://www.projectpluto.com/packed.htm).

### Expected Behaviour
Import data dialog is opened containing the asteroid

### Actual Behaviour
Nothing happens, the following error is logged:
`readMpcOneLineMinorPlanetElements(): "~0K8Q" is not a valid number or packed IAU designation`

### Steps to reproduce
Copy the line for asteroid (697402) Ao from MPCORB.DAT and save to a separate file
Go to Configuration -> Plugins -> Solar System Editor -> Configure -> Import orbital elements in MPC format...
Select "A file containing a list of objects", choose the file, press "Get orbital elements"

### System
* Stellarium version: Stellarium-24.2-qt5-x86_64.AppImage
* Operating system: Ubuntu 22.04

### Logfile 
[log.txt](https://github.com/user-attachments/files/16908878/log.txt)

**Comment by alex-w** [comment] 2024-09-06 14:07
Duplicate of #3882

**Comment by alex-w** [comment] 2024-09-06 14:08
The fix will be available in next weekly snapshot and in next release

**Closed** 2024-09-06 14:09 UTC
Labels: duplicate
