### ISSUE TITLE
Telescope Control hangs Stellarium at startup

### ISSUE THREAD

**Issue by astange2** [Stellarium/stellarium#2717] opened 2022-10-04 08:15 UTC
### Expected Behaviour
The Telescope Control Dialog titled "Slew telescope to"  opens when pressing the Telescope icon on the Main Tool Bar with the telescop connected.

###  Actual Behaviour
Stellarium freezes and needs to be restarted

### Steps to reproduce
1. Start Stellarium
2. Press the telescope Icon on the Main Tool Bar

The telescope control plugin is set to "load at startup" and the telescope configuration set to "start/connect at startup".  Configuation is using ASCOM.
![bild](https://user-images.githubusercontent.com/92911534/193765968-c8332070-9748-4de9-b42e-9b48138c1ad6.png).
A workaround is to start Stellarium and first go into Plugin configurations and disconnect the telescope.
Then select the telescope icon on the Main Tool Bar and reconnect the telescope.
A related issue is that Telescope configuration dialog does not accept changes. The OK button does not respond.

The problem disappear when reinstalling the previous Stellarium version(0.22.2)
  
### System
* Stellarium version: stellarium-1.22.3-win64
* Operating system: Windows 10 Pro 19044.2006
* Graphics Card:Intel, UHD Graphics 630
* Screen type (if applicable): 100% at 3480x2160

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by kantn8r** [comment] 2022-10-06 17:44
Issue #2717 looks to be very similar. Telescope Control does not hang at startup for me. Stellarium starts up and I can connect to Gemini Telescope.net. It does not hang up until the following steps are completed:

Select an object > click the Telescope icon in the menu bar (Control+O) > set coordinates >  click slew /go to.

As soon as you click the slew / go to button Stellarium hangs and must be restarted.

Windows 10 64-bit, Stellarium 1.22.3, Gemini.NET ASCOM Driver Version 1.0.75 

HP Pavilion 15 Laptop, Intel® Core™ i7-1165G7, 16 GB DDR4-3200 SDRAM (2 x 8 GB), Intel® Iris® X Graphics

**Comment by markmac99** [comment] 2022-10-10 10:17
Additionally if adding a new connection then on the "Configure Telescope" dialog, clicking "Ok" has no effect, settings cannot be saved. see #2743 for more detail

**Comment by gzotti** [comment] 2022-10-10 11:05
The "additional" issue is a duplicate of #2713 and has been addressed in #2714.

**Comment by markmac99** [comment] 2022-10-10 13:12
Thanks George. I could not find any mention of the issue with the ok button when i searched earlier. Glad its being addressed.

**Comment by alex-w** [comment] 2023-07-05 19:53
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by gzotti** [comment] 2023-09-13 09:17
Several Qt6/TelescopeControl issues have been solved before 23.3. We tentatively close this as member of a large group of related issue reports for now. In case of re-occurrence of this issue in V23.3, please create a new report with very clear description of circumstances.

**Closed by gzotti** 2023-09-13 09:17 UTC
Labels: help wanted, good first issue
