### ISSUE TITLE
Stellarium 1.1.1 (Mac version) has incorrect Bundle versions in Info.plist

### ISSUE THREAD

**Issue by stevemaser** [Stellarium/stellarium#2813] opened 2022-11-02 15:15 UTC
Version 1.1 has these bundle versions:

	<key>CFBundleVersion</key>
	<string>1.22.4</string>
	<key>CFBundleShortVersionString</key>
	<string>1.22.4</string>

Version 1.1.1 has these BundleVersions:

	<key>CFBundleVersion</key>
	<string>0.22.4-8cc1565</string>
	<key>CFBundleShortVersionString</key>
	<string>0.22.4-8cc1565</string>

Neither of these actually reflect that the app version is now 1.1.x and it makes deploying updates through Munki based on checking BundleVersion values somewhat difficult.

We suggest that the BundleVersion actually reflect the version number of the Application going forward.   Thanks!

- Steve

**Comment by alex-w** [comment] 2022-11-02 15:39
Duplicate of #2805

**Closed** 2022-11-02 15:40 UTC
Labels: duplicate
