### ISSUE TITLE
Cannot update catalog 5 of 9 in Stellarium 0.18.2 #260 rehash

### ISSUE THREAD

**Issue by lukesms** [Stellarium/stellarium#377] opened 2018-09-20 01:53 UTC
### Expected Behaviour
Download extra star catalogues

### Actual Behaviour
Star catalog download fails exactly as in issue #260 as per issue title, guillaumechereau said he pushed a fix but I'm still having the checksum fail, nothing about the ssl error just the mismatched hashes

### Steps to reproduce
Every time I hit download start catalog

### System
* Stellarium version: 18.2 win x64
* Operating system: Win 10
* Graphics Card: Intel, Model N/A

### Logfile 
2018-09-19T18:48:43
Operating System: Windows 10
Product Name: Windows 10 (10.0)
Compiled using MSVC++ 14.0 (Visual Studio 2015)
Qt runtime version: 5.9.5
Qt compilation version: 5.9.5
Addressing mode: 64-bit
Total physical memory: 24456 MB
Available physical memory: 20592 MB
Physical memory in use: 15%
Processor speed: 2195 MHz
Processor name: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
Processor speed: 2195 MHz
Processor name: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
Processor speed: 2195 MHz
Processor name: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
Processor speed: 2195 MHz
Processor name: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
Processor speed: 2195 MHz
Processor name: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
Processor speed: 2195 MHz
Processor name: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
Processor speed: 2195 MHz
Processor name: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
Processor speed: 2195 MHz
Processor name: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
C:\Program Files\Stellarium\stellarium.exe 
 -------------------------------------------------------
[ This is Stellarium 0.18.2 - http://www.stellarium.org ]
[ Copyright (C) 2000-2018 Fabien Chereau et al.         ]
 -------------------------------------------------------
Writing log file to: "C:\\Users\\micha\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\micha\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file  "C:\\Users\\micha\\AppData\\Roaming\\Stellarium\\config.ini"  does not exist. Copying the default file.
Config file is:  "C:\\Users\\micha\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "4.3.0 - Build 10.18.15.4248"
Current Format:  QSurfaceFormat(version 4.3, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))
StelMainView::init
Detected: OpenGL "4.3"
Driver version string: "4.3.0 - Build 10.18.15.4248"
GL vendor is "Intel"
GL renderer is "Intel(R) HD Graphics 4600"
GL Shading Language version is "4.30 - Build 10.18.15.4248"
GLSL Version Number detected:  4.3
GLSL version is fine, we should not see a graphics problem.
Cache directory is:  "C:\\Users\\micha\\AppData\\Local\\stellarium\\stellarium\\cache"
Sky language is  "en_US"
Planetary features language is  "en_US"
Application language is  "en_US"
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
Loaded 77 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "./data/ssystem_minor.ini"
Loaded 102 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15505 / 15510 items of planetary surface nomenclature
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_7.cat: 0_0v0_7; 4979"
"Loading .\\stars\\default\\stars_1_0v0_7.cat: 1_0v0_7; 21806"
"Loading .\\stars\\default\\stars_2_0v0_7.cat: 2_0v0_7; 150850"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
Finished loading star catalogue data, max_geodesic_level:  3
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4506 / 4506 scientific star names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6916 / 6916 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.6 (standard edition)"
Loaded 94077 DSO records
Loading DSO outline data ...
Loaded 63 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 860 / 860 common star names
Loading DSO name data ...
Loaded 1041 / 1055 DSO name records successfully
WARNING - No position data for 14 objects: "PGC 2906, PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 54559, PGC 59117, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  63 for culture "western"
Loaded 53 / 54 asterism records successfully for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
Loaded 43 / 44 asterism names
stel.OpenGLArray: Disabling VAO usage because of Intel driver bugs
stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "Exoplanets"
[Exoplanets] No Exoplanets section exists in main config file - creating with defaults
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\micha\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "FOV"
FOV: no fov section exists in main config file - creating with defaults
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: "C:\\Users\\micha\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
Loaded plugin "Novae"
[Novae] no Novae section exists in main config file - creating with defaults
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\micha\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Oculars"
Ocular plugin - press Command-O to toggle eyepiece view mode. Press ALT-o for configuration.
Oculars::validateIniFile ocular.ini exists at:  "C:\\Users\\micha\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateIniFile found existing ini file version  3.1
Loaded plugin "Satellites"
[Satellites] loading catalog file: "C:\\Users\\micha\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Satellite has invalid orbit: "MOLNIYA 3-3" "08425"
Satellite has invalid orbit: "IRIDIUM 6" "24794"
Satellite has invalid orbit: "IRIDIUM 19" "24965"
Satellite has invalid orbit: "IRIDIUM 34" "24969"
Satellite has invalid orbit: "IRIDIUM 43" "25039"
Satellite has invalid orbit: "IRIDIUM 40" "25041"
Satellite has invalid orbit: "GRACE-1" "27391"
Satellite has invalid orbit: "GRACE-2" "27392"
Satellite has invalid orbit: "ORS 1" "37728"
Satellite has invalid orbit: "TIANGONG 1" "37820"
Satellite has invalid orbit: "EAGLE 2" "39436"
Satellite has invalid orbit: "AGGIESAT 4" "41313"
Satellite has invalid orbit: "FLOCK 2E'-1" "41479"
Satellite has invalid orbit: "FLOCK 2E'-3" "41480"
Satellite has invalid orbit: "FLOCK 2E'-2" "41481"
Satellite has invalid orbit: "FLOCK 2E-2" "41484"
Satellite has invalid orbit: "FLOCK 2E-4" "41487"
Satellite has invalid orbit: "FLOCK 2E-6" "41563"
Satellite has invalid orbit: "FLOCK 2E-7" "41565"
Satellite has invalid orbit: "FLOCK 2E'-8" "41569"
Satellite has invalid orbit: "FLOCK 2E-9" "41571"
Satellite has invalid orbit: "FLOCK 2E-10" "41572"
Satellite has invalid orbit: "FLOCK 2E-12" "41573"
Satellite has invalid orbit: "FLOCK 2E-11" "41574"
Satellite has invalid orbit: "FLOCK 2E'-9" "41575"
Satellite has invalid orbit: "FLOCK 2E'-10" "41576"
Satellite has invalid orbit: "FLOCK 2E'-11" "41577"
Satellite has invalid orbit: "FLOCK 2E'-12" "41578"
Satellite has invalid orbit: "FLOCK 2E'-13" "41761"
Satellite has invalid orbit: "FLOCK 2E'-17" "41776"
Satellite has invalid orbit: "STARS-C" "41895"
Satellite has invalid orbit: "OSNSAT" "41939"
Satellite has invalid orbit: "LEMUR-2-TRUTNA" "42067"
Satellite has invalid orbit: "Columbia" "42702"
Satellite has invalid orbit: "SGSAT" "42703"
Satellite has invalid orbit: "Atlantis" "42737"
Satellite has invalid orbit: "ISS DEB (ROSA)" "42813"
Satellite has invalid orbit: "TECHEDSAT 6" "43026"
Satellite has invalid orbit: "DRAGON CRS-13 DEB" "43061"
Satellite has invalid orbit: "DRAGON CRS-13 DEB" "43062"
Satellite has invalid orbit: "SL-4 R/B" "43064"
Loaded plugin "SolarSystemEditor"
Trying to copy ssystem_minor.ini to "C:\\Users\\micha\\AppData\\Roaming\\Stellarium\\data\\ssystem_minor.ini"
Got location "Vancouver, British Columbia, Canada (49.2795, -123.067; America/Vancouver)" for IP "69.172.147.17"
Dubious result: Landscape  "Guereins"  not calibrated. Opacity test represents mathematical horizon only.
Initializing planets GL shaders... 
  OpenType support missing for "Verdana", script 11
  OpenType support missing for "MS Shell Dlg 2", script 11
  OpenType support missing for "Arial", script 11
  OpenType support missing for "MS UI Gothic", script 11
  OpenType support missing for "SimSun", script 11
  OpenType support missing for "Verdana", script 12
  OpenType support missing for "MS Shell Dlg 2", script 12
  OpenType support missing for "Arial", script 12
  OpenType support missing for "MS UI Gothic", script 12
  OpenType support missing for "SimSun", script 12
  OpenType support missing for "Verdana", script 13
  OpenType support missing for "MS Shell Dlg 2", script 13
  OpenType support missing for "Arial", script 13
  OpenType support missing for "MS UI Gothic", script 13
  OpenType support missing for "SimSun", script 13
  OpenType support missing for "Verdana", script 14
  OpenType support missing for "MS Shell Dlg 2", script 14
  OpenType support missing for "Arial", script 14
  OpenType support missing for "MS UI Gothic", script 14
  OpenType support missing for "SimSun", script 14
  OpenType support missing for "Verdana", script 16
  OpenType support missing for "MS Shell Dlg 2", script 16
  OpenType support missing for "Arial", script 16
  OpenType support missing for "MS UI Gothic", script 16
  OpenType support missing for "SimSun", script 16
  OpenType support missing for "Verdana", script 17
  OpenType support missing for "MS Shell Dlg 2", script 17
  OpenType support missing for "Arial", script 17
  OpenType support missing for "MS UI Gothic", script 17
  OpenType support missing for "SimSun", script 17
  OpenType support missing for "Verdana", script 18
  OpenType support missing for "MS Shell Dlg 2", script 18
  OpenType support missing for "Arial", script 18
  OpenType support missing for "MS UI Gothic", script 18
  OpenType support missing for "SimSun", script 18
  OpenType support missing for "Verdana", script 19
  OpenType support missing for "MS Shell Dlg 2", script 19
  OpenType support missing for "Arial", script 19
  OpenType support missing for "MS UI Gothic", script 19
  OpenType support missing for "SimSun", script 19
  OpenType support missing for "Verdana", script 20
  OpenType support missing for "MS Shell Dlg 2", script 20
  OpenType support missing for "Arial", script 20
  OpenType support missing for "MS UI Gothic", script 20
  OpenType support missing for "SimSun", script 20
  OpenType support missing for "Verdana", script 32
  OpenType support missing for "MS Shell Dlg 2", script 32
  OpenType support missing for "Arial", script 32
  OpenType support missing for "MS UI Gothic", script 32
  OpenType support missing for "SimSun", script 32
  OpenType support missing for "Verdana", script 10
  OpenType support missing for "MS Shell Dlg 2", script 10
  OpenType support missing for "Arial", script 10
  OpenType support missing for "MS UI Gothic", script 10
  OpenType support missing for "SimSun", script 10
Downloading file "https://github.com/Stellarium/stellarium-data/releases/download/stars-2.0/stars_4_1v0_2.cat"
Found file  "C:\\Users\\micha\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_4_1v0_2.cat" , checking md5sum..
Error: File  "stars\\default\\stars_4_1v0_2.cat"  is corrupt, MD5 mismatch! Found  "d41d8cd98f00b204e9800998ecf8427e"  expected  "ac67dc390f9d414d61b1db76a5b820e9"
Unloaded plugin "SolarSystemEditor"
Unloaded plugin "Satellites"
Unloaded plugin "Oculars"
Unloaded plugin "Novae"
Unloaded plugin "MeteorShowers"
Unloaded plugin "FOV"
Unloaded plugin "Exoplanets"
Downloaded 2 files (16551 kbytes) in a session of 32.814 sec (average of 504.388 kB/s + 0 files from cache (0 kB)).
LandscapeMgr: Clearing cache of 0 landscapes totalling about  0 MB.

**Comment by gzotti** [comment] 2018-09-20 08:06
And, did you try with the current beta as discussed later in the thread? If problems are fixed in code in late August, this will not magically distribute to installed version 0.18.2 from earlier August.

**Comment by gzotti** [comment] 2018-09-20 21:33
Also duplicate of #269

**Comment by Vidjeane** [comment] 2018-12-17 14:18
The link https://github.com/Stellarium/stellarium-data/releases/download/stars-2.0/stars_4_1v0_2.cat does not contain catalog 4 and above.

**Comment by gzotti** [comment] 2018-12-17 14:30
Sure. A link to one file does not provide other files. Find more at

https://github.com/Stellarium/stellarium-data/releases/tag/stars-2.0

**Comment by Vidjeane** [comment] 2018-12-17 14:34
ok. got it.

**Comment by gzotti** [comment] 2018-12-22 19:05
Duplicate of solved problem. Closing.

**Closed by gzotti** 2018-12-22 19:05 UTC
Labels: duplicate, incomplete
