### ISSUE TITLE
SATELLITES  plugin- SEARCH.  23.1

### ISSUE THREAD

**Issue by JAY-Githb** [Stellarium/stellarium#3221] opened 2023-05-08 17:04 UTC
Did I forget what to do already?
In SATELLITES CONFIGURATION
When I type into the Search box, nothing happens.

Also SETTINGS OF CUSTOM FILTER doesn't seem to do anything.

Thanks for refreshing my memory.
Jay

**Comment by alex-w** [comment] 2023-05-08 18:30
Probably duplicate of #3158 - please check the report

**Comment by alex-w** [comment] 2023-05-09 14:20
Hello @JAY-Githb 

Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by JAY-Githb** [comment] 2023-05-10 04:09
Hello.
I downloaded  this version.  SEARCH is now working correctly.
Stellarium 23.1+
Version 23.1.122-7b59b0c [HEAD]
Based on Qt 5.12.6

Thank you!

**Comment by alex-w** [comment] 2023-05-10 04:15
Duplicate of #3158

**Closed** 2023-05-10 04:16 UTC
Labels: duplicate
