### ISSUE TITLE
Error with lunar eclipse texture and magnitudes

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1115] opened 2020-06-06 08:42 UTC
Using the latest beta (0.20.1.17986), we learn that a neat addition to the infostring has been added: umbral and penumbral magnitudes. Very nice.

But there is a problem. They don't get along with the eclipse texture nor the (visual) magnitudes given in the infostring.

To see what I mean, set the time to 2019-01-21, 04:41:16 (UTC) (location on earth is irrelevant), Look at the values in the infostring; the moon is supposed to be completely within the umbra, yet the texture and the visual magnitude values suggest that it is not. The time fits the "official" values on almost exactly, which means the umbral magnitude is correct.

See the screenshot:
![stellarium-012](https://user-images.githubusercontent.com/37028368/83940060-12ea1680-a7e2-11ea-8154-9762b0d75fc9.png)

The article on Wikipedia gives the total eclipse start at 04:41:17 UTC, so Stellarium is just 1 second off! 
https://en.wikipedia.org/wiki/January_2019_lunar_eclipse
But the texture and the visual magnitude gives the total eclipse start at 04:43:25 UTC, more than 2 minutes off.

**Comment by gzotti** [comment] 2020-06-06 09:46
Unlike the razor-sharp edge of the Moon during a total Solar eclipse, Earth's umbra during Lunar eclipse has no clear edge. My last round of adjustments (late 2018) pretty closely matches my own photographs. 
![TLE20180727_GZ_crop (Individuell)](https://user-images.githubusercontent.com/18099873/83941115-03220080-a7e9-11ea-8b99-da8037eaf8bc.jpg)
![TLE20180727_Stellarium_crop (Individuell)](https://user-images.githubusercontent.com/18099873/83941118-087f4b00-a7e9-11ea-9cc4-35b0b7e5e263.png)

It may be easy to define the borders geometrically, simulating the visual appearance is much more difficult. From other things like stellar or planet occultations I know that Stellarium is rather 1 minute away. When this can be solved, some further fine-tuning of the eclipse texture and other minor issues can be performed.

The magnitude during eclipse is a rough guess. Can you supply us with a comprehensible, reproducible model that fits better?

**Comment by Atque** [comment] 2020-06-06 09:55
@gzotti 
> The magnitude during eclipse is a rough guess. Can you supply us with a comprehensible, reproducible model that fits better?

No, but I think the current texture should at least agree the infostring values. I know the border is quite fuzzy in reality, but despite the texture used being sharp, it should fit so that once the infostring says "umbral eclipse magnitude: 1.00000", the texture should cover all of the lunar disk. This is not the case currently, as my screenshot shows.

To get decent magnitude values is hard, at least if you want to do it properly. If Stellarium implements a value for the Danjon scale, then magnitudes could perhaps be a little more easily approximated. But as you can see, the screenshot claims that the visual magnitude is -6.93, which suggests that some part of the moon is still lit by the sun, which the infostring says it isn't. The infostring agrees with the values on Wikipedia, which means Stellarium is only a second off, but the texture is not aligned that well.

**Comment by gzotti** [comment] 2020-06-06 10:20
OK, the line which decides total umbra coverage should and probably can quickly be harmonized with the new lines that define edge contacts with the Danjon-enlarged shadow. However, before version 1.0 you should not trust the times to the second, as there are still systematic errors. 

The texture also has no sharp edge, and we do not draw a circle that defines the geometric edge. There are other sources for that. Its re-adjustment is trickier. The next round could also slightly decrease the blue area, and there are maybe 5 other tweaks involved to balance the visual appearance. You can tweak that for weeks, and it will still not match the visual drama. Even if photos show the round edge on the Lunar disk, when observing the very edge of totality I was never able to say "NOW it's total!" 

As far as I understand the Danjon brightness is estimated during eclipse, empirically. It depends on clouds and atmospheric dust. Do you have a catalog of eclipse Danjon values of (at least) the past 70 years?

**Comment by Atque** [comment] 2020-06-06 10:28
@gzotti 
Here's an interesting link that may help if the goal is to create a hyperrealistic lunar eclipse:
https://stevealbers.net/albers/lunar/lunar.html

It really matches the visual appearance of a standard lunar eclipse. However, I don't think his code is open source so I don't know how easy it is to obtain and use.

> Do you have a catalog of eclipse Danjon values of (at least) the past 70 years?
No, sorry.

**Comment by worachate001** [comment] 2020-06-06 10:42
I noticed this discrepancy while writing and testing the code. But I decided to ignore it because, as we agree, the umbra's edge is really fuzzy. The magnitude (fraction of Moon's diameter obscured by umbra or penumbra) is almost exactly match with those predicted by NASA because we use the same method for calculations.

I observed the eclipse on 4 April 2015 which supposed to be total eclipse but bright edge of the Moon still visible during totality. So I think Stellarium is realistic enough. Anyway, if we think that this is a problem and should be fixed, enlarging the shadow should help but I'm not sure how to do it.

**Comment by Atque** [comment] 2020-06-19 08:16
Hm. After some investigation, it seems the texture is not symmetric. Compare these two screenshots:

![stellarium-015](https://user-images.githubusercontent.com/37028368/85112121-737f4780-b215-11ea-856a-e88fb3f82a3c.png)
![stellarium-016](https://user-images.githubusercontent.com/37028368/85112124-75e1a180-b215-11ea-93f4-e0c2af22cbd5.png)

It seems like the texture is offset, so that it does not completely cover the lunar disk when the moon enters an eclipse, but covers it when the moon exits it.

Also, a side note: @gzotti maybe now the brightening of the moon can be calibrated better, using the "umbral eclipse magnitude" instead of elongation? I mentioned it a few years ago here: https://github.com/Stellarium/stellarium/pull/274

**Comment by gzotti** [comment] 2020-06-19 08:32
The texture is necessarily symmetric as it is just a single line. Rather, computed times differ.

**Comment by alex-w** [comment] 2020-07-23 07:29
[AO_2008_Hernitschek_Schmidt_Vollmer.pdf](https://github.com/Stellarium/stellarium/files/4964424/AO_2008_Hernitschek_Schmidt_Vollmer.pdf)

**Comment by gzotti** [comment] 2020-07-23 08:10
Presumably depends on complete solution for aberration, or whatever also causes a 1-minute error for occultations. (#84)

**Closed** 2021-08-21 17:21 UTC
Labels: bug, medium importance

**Comment by cork124** [comment] 2021-12-20 19:07
good
