### ISSUE TITLE
stellarium flickers using hardware rendering in linux window managers such as cinnamon

### ISSUE THREAD

**Issue by joequant** [Stellarium/stellarium#2077] opened 2021-12-02 08:42 UTC
### Expected Behaviour

Stellarium should produce an non-flickering image

### Actual Behaviour

stellarium flickers on a window manager like cinnamon on linux in hardware rendering mode.  The window seems
to go black and does a redraw.  The software works fine when the window manager is in software rendering mode

### System
* Stellarium version: 0.21.2
* Operating system: Mageia linux 9
* Graphics Card: Intel using i915 driver and modesetting x11 server
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by joequant** [comment] 2021-12-02 16:12
Appears to  have something to do with this issue.

https://www.reddit.com/r/opengl/comments/moxt4v/flickering_problem_when_rendering_opengl/

somewhere a spurtious swapbuffer is being called.

**Comment by alex-w** [comment] 2021-12-25 08:23
@joequant please check our AppImage

**Comment by IvoMajic** [comment] 2021-12-29 17:58
Having the same issue on Arch Linux. Tried both the official Arch package and the AppImage.

**Comment by gzotti** [comment] 2021-12-30 10:12
A workaround is described in the duplicate https://github.com/Stellarium/stellarium/issues/2127#issuecomment-1001248810

**Comment by NigelCunningham** [comment] 2022-01-02 11:13
Hi there. I've come across this issue too, and am wondering about the policy for getting an actual fix - both issues have been closed but joequant's comment above indicates it may be possible to find a proper fix within Stellarium. If I (or someone else) can manage to track down the cause (or even want to try), should we be opening a new issue for that discussion, or reopening this issue? Thanks!

**Comment by gzotti** [comment] 2022-01-02 11:26
This issue here is open. Others which describe the same problem have been closed as duplicates. The issue only appears on some Linux systems. All of the reported systems have Intel GPUs. From these bits of information it appears very likely the problems do not lie within Stellarium's program sources but with Intel GPU drivers for Linux. You may want to report this issue to Intel or the Mesa project.  A workaround has been reported for affected users of Stellarium.

**Comment by NigelCunningham** [comment] 2022-01-02 11:32
Thanks for the reply gzotti - I was mistakenly thrown by the 'Closed' (related issue) just above; thanks.

I saw mention in the linked Reddit article of the possibility that the OpenGL queue is filling. Would you know if there's any way I could test out that theory? (I've worked on the kernel in the past so have some low level knowledge and would have no problem when it comes to changing kernel command line parameters or other config if there's some tunable related to the OpenGL queue length that I haven't found in my Googling so far).

**Comment by gzotti** [comment] 2022-01-02 11:36
Sorry, I cannot help with driver-level OpenGL or kernel debugging on Linux.

**Comment by NigelCunningham** [comment] 2022-01-02 11:38
Ok. Thanks anyway!

**Comment by El-Brujo-Manjaro** [comment] 2022-01-04 05:30
I confirm I have this issue with Stellarium 0.21.3. on Manjaro Linux, kernels 5.15 and 5.10.  Below is the data for my graphics devices:

```
Device-1: Intel HD Graphics 530 driver: i915 v: kernel
Device-2: NVIDIA GM107M [GeForce GTX 960M] driver: nouveau v: kernel
  Display: wayland server: X.org 1.21.1.2 driver:
    loaded: modesetting,nvidia
```

I was able to work around this issue either by running Stellarium on the Nvidia GPU or  by downgrading Mesa from 21.3.2 to 21.2.5., if using Intel graphics.

FYI, there is an issue already opened upstream at freedesktop.org for this. See below:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5731

**Comment by alex-w** [comment] 2022-01-04 07:02
@El-Brujo-Manjaro did you tried patch: https://gitlab.freedesktop.org/mesa/mesa/uploads/accd04634117b88139e5320482610013/mesa-21.3.3-fix-bug-5731.patch ?

**Comment by NigelCunningham** [comment] 2022-01-04 21:19
Thanks for the additional info. I realise you're not asking me, @alex-w, but I'll seek to find the time to apply the patch today (I'm on Arch Linux) too.

**Comment by NigelCunningham** [comment] 2022-01-04 22:46
I can confirm that the above patch fixes the flashing for me (just install the packages; no reboot or restart of X required). It makes Stellarium soooo much more usable!

**Comment by alex-w** [comment] 2022-01-05 03:08
> I can confirm that the above patch fixes the flashing for me (just install the packages; no reboot or restart of X required). It makes Stellarium soooo much more usable!

Well, this is definitely bug in MESA and we should close this issue.

**Closed by alex-w** 2022-01-05 03:08 UTC
Labels: medium importance, grading
