### ISSUE TITLE
Stellarium: Space probes and Crosshairs

### ISSUE THREAD

**Issue by StellariumUser** [Stellarium/stellarium#870] opened 2019-12-03 13:54 UTC
- [ ] (1.) How i can add space probes like New Horizons, Voyger, Pioneer to Stellarium ?
- [x] (2.)  How i can generate the crosshair as an result of a search / input in the Right asencion - Declination values field ?

Greetings
Dieter

**Comment by alex-w** [comment] 2019-12-03 14:18
1. No. See https://github.com/Stellarium/stellarium/issues/259
2. A quick workaround at the moment - using CCD mode in Oculars plugin. Are you really want to get a crosshair of center of the screen?

**Comment by alex-w** [comment] 2020-05-06 19:14
Second point has been implemented since version 0.20.1.17888

**Comment by gzotti** [comment] 2020-08-02 17:03
And first is a duplicate of #259. (And not related to the Satellite plugin!)

**Closed by gzotti** 2020-08-02 17:03 UTC
Labels: question
