### ISSUE TITLE
Save & Exit Observing List crashes app (ver. 0.22.2)

### ISSUE THREAD

**Issue by olduvai** [Stellarium/stellarium#2629] opened 2022-09-05 02:08 UTC
Ver. 0.22.2 (ARM-64)
OS: MacOS Monterey 12.5.1
Impact: severe
Probability: 90+%
Workaround: none

Steps to reproduce:
1. Open Observing Lists, choose any list to edit
2. In the Edit window, click either Save & Close or Exit - Stellarium crashes

This happens > 90% of time, whether you add or remove an object or do nothing. However, even when the app crashes, it does manage to save the changes if you click Save & Close, which can be observed on restarting the app.

**Comment by olduvai** [comment] 2022-09-05 02:23
Log file:

[stellarium-2022-09-04-191903.txt](https://github.com/Stellarium/stellarium/files/9486227/stellarium-2022-09-04-191903.txt)

**Comment by alex-w** [comment] 2022-09-05 03:05
Duplicate of #2437

**Closed** 2022-09-05 03:06 UTC
Labels: duplicate
