### ISSUE TITLE
Black Unresponsive window on startup

### ISSUE THREAD

**Issue by DrGregCampbell** [Stellarium/stellarium#2363] opened 2022-03-26 03:02 UTC
Stellarium has been working perfectly but after a break of a couple of months it just shows the splash screen and then throws to a small black window with no functionality. This happens with ANGLE MESA and every other option. I hadn't updated stellarium at all.

This problem happens for all versions of stellarium I've tried uninstalling and reinstalling, including the newest and a very old one, 32 bit or 64 bit. I've checked all my drivers, they are 100% up to date. So I now can't use stellarium at all :(

Original version: 0.21.0
Also tried: 0.21.3 (64 and 32 bit),  0.11.3 (32 bit)

### System
* Stellarium version: 0.21.3 (64 and 32 bit), 0.21.0,   0.11.3 (32 bit)<Name of downloaded installable file?>
* Operating system: Windows 10 Pro version 21H2. 
* Graphics Card: Intel(R) HD Graphics 520, driver version 30.0.100.9865

I can't find a log.txt
![Capture](https://user-images.githubusercontent.com/101975226/160222352-a55ae5f7-97a6-46db-b154-517d7b0c0cb3.PNG)

**Comment by gzotti** [comment] 2022-03-26 09:13
As long as we don't see the log.txt (its location is described in chapter 5 of the User Guide), we cannot do anything. For now it looks like a duplicate of several reports about graphics driver problems. Intel's Graphics drivers are updated without your explicit consent by Windows system update. Maybe Intel has yet another driver on their own download page.

**Comment by DrGregCampbell** [comment] 2022-03-26 12:09
[log.txt](https://github.com/Stellarium/stellarium/files/8355331/log.txt)

Found the log file, hope this helps. Thanks for the info so far, I suspect too it was an update done without my knowledge. I will see if downgrading the driver is possible.

**Comment by gzotti** [comment] 2022-03-26 12:28
Yes, that's a driver issue. Fetch OpenGL capable drivers from Intel. A core-i7-6xxx should definitely be capable of running Stellarium.

**Comment by alex-w** [comment] 2022-04-21 07:29
Duplicate of #2166

**Closed** 2022-04-21 07:30 UTC
Labels: duplicate
