### ISSUE TITLE
Planet surfaces not rendering in angle mode

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#387] opened 2018-09-26 04:13 UTC
_Original report by Ross:_ https://bugs.launchpad.net/stellarium/+bug/1731788

I'm using Stellarium under Windows 7 X64 on several different machines. One is an older laptop requiring Angle mode for video. Full version 0.16.1 works great, but as of beta 0.90.0.9852, planet surfaces no longer render in Angle mode. I've confirmed this on the other machines as well, so it's not a unique anomaly with the laptop or its video card/drivers. As of 0.90.0.9852, planet surface rendering in Angle mode appears to be broken across multiple platforms.

**Comment by gzotti** [comment] 2018-09-26 11:39
Duplicate of #273 (actually copy of the original report...)

**Closed by gzotti** 2018-09-26 11:39 UTC
Labels: bug, confirmed, duplicate, high importance
