### ISSUE TITLE
Stellarium 24.2 - Clicks don't find the right object after moving to a bigger screen.

### ISSUE THREAD

**Issue by Don-SkyWatcher** [Stellarium/stellarium#3790] opened 2024-06-29 14:18 UTC
When I resize from my local PC window to the larger monitor, object selection if off.  It's selecting something away from what is to be selected.  Big problem.  Noticed the issue in 23 and thought maybe it was a known bug, but it's still there in 24.
Please help.
Thanks,
Don Farage

**Comment by gzotti** [comment] 2024-06-29 21:42
Sounds very much like a duplicate of #3744. Yes, known.

**Closed by gzotti** 2024-06-29 21:42 UTC
Labels: duplicate
