### ISSUE TITLE
Searching for satellite on hyperbolic orbit (JWST) causes Stellarium to crash or turn to NaN coordinates

### ISSUE THREAD

**Issue by naavis** [Stellarium/stellarium#2131] opened 2021-12-26 18:41 UTC
### Expected Behaviour
When I fetch orbital elements for the James Webb Space Telescope and try to turn Stellarium towards it, I should find the satellite.

### Actual Behaviour
Stellarium either crashes without an error message or turns to NaN/NaN coordinates.

### Steps to reproduce
1. Go to the Satellites plugin settings
2. Go to the Sources tab of the plugin window
3. Enable the source https://celestrak.com/NORAD/elements/tle-new.txt
4. Go back to the Settings tab and click "Update Now" to fetch the latest orbital elements
5. Go to the Satellites tab and make sure JWST is there
6. Tick the "Displayed" checkbox for JWST
7. Close the Satellites plugin window
8. Press Ctrl+F and search for JWST
9. Click on the found JWST result

This either causes Stellarium to crash or to show NaN coordinates.

### System
* Stellarium version: 0.21.3
* Operating system: Windows 10 (Version 21H2, OS build 19044.1415)
* Graphics Card: MSI Geforce RTX 3070 Gaming Z Trio LHR, driver version 497.29
* Screen type (if applicable): 2560x1440, no scaling

### Logfile 
Attached the latest log file.
[log.txt](https://github.com/Stellarium/stellarium/files/7777406/log.txt)

Also attached a copy of the tle-new.txt file as it is at the time of writing, since it changes over time.
[tle-new.txt](https://github.com/Stellarium/stellarium/files/7777407/tle-new.txt)

TLE for JWST at the time of writing is:
```
JWST                    
1 50463U 21130A   21359.67000000  .00000000  00000+0  00000+0 0  9996
2 50463   4.0560  89.2250 9869375 191.8770   1.2200  0.02366270    24
```

**Comment by worachate001** [comment] 2021-12-27 02:23
It's likely that the error comes from hyperbolic orbit.

**Comment by alex-w** [comment] 2021-12-27 03:19
I cannot reproduce the crash

**Comment by worachate001** [comment] 2021-12-27 04:45
I'm using Ubuntu 20.04. The program is still running with black screen (no crash), the spacecraft was placed at the center of Earth.

**Comment by gzotti** [comment] 2021-12-27 10:13
> It's likely that the error comes from hyperbolic orbit.

The excentricity is still <1 (almost parabolic ellipse), but indeed this is where the problem may come from. 
I see no crash, but JWST is simply not centered when selected in the list.

**Comment by naavis** [comment] 2021-12-27 13:48
> I see no crash, but JWST is simply not centered when selected in the list.

Did you tick the "Displayed" checkbox for JWST in the Satellites plugin settings? I saw similar behaviour if it wasn't ticked. Nothing just happened if I selected JWST from the list when the checkbox was unticked.

**Comment by alex-w** [comment] 2021-12-27 15:49
Stellarium shouldn't display JWST, because when computing subpoint parameters (latitude, longitude, altitude) the altitude is negative - WTF?!?

**Comment by gzotti** [comment] 2021-12-27 16:34
Probably the given TLE describe the transfer orbit in a shape that comes unexpected for the gsat library which describes "regular" satellite orbits.

**Comment by alex-w** [comment] 2021-12-27 17:52
So, position vector has value (0, 0, 0) and this is very strange.

**Comment by alex-w** [comment] 2021-12-27 18:13
According to https://www.celestrak.com/software/vallado-sw.php SGP4 has changes and maybe our copy has bugs.

**Comment by gzotti** [comment] 2021-12-27 20:53
I see in the log: "Satellite has invalid orbit: "JWST" "50463"". I have not dug further, though.

**Comment by alex-w** [comment] 2021-12-27 20:57
> I see in the log: "Satellite has invalid orbit: "JWST" "50463"". I have not dug further, though.

Yes, this line is visible when altitude of satellite lower 70 km (object in atmosphere)

**Comment by worachate001** [comment] 2021-12-27 22:57
I put the TLE in Skyfield (a Python library). It gives error as well with a message --> "perturbed eccentricity is outside the range 0.0 to 1.0".

I investigated deeper by decreasing the eccentricity in TLE and it worked. It's possible that propagated orbit with original value gives e>1.0

**Comment by gzotti** [comment] 2021-12-27 23:14
Ah, that sounds reasonable. Of course, if e can become >1 something will break. It was not clear to me that e was not constant in the TLE, when there are no changes in mean motion data.

**Comment by JAY-Githb** [comment] 2021-12-31 04:13
WEBB is on a path away from earth.  It is not in stable orbit around earth so a TLE would not be accurate.
To have an idea of where it is once in final position, simply turn on ASP- Anti Solar Position.  (see the settings).

Jay

**Comment by JAY-Githb** [comment] 2022-03-04 07:21
Hello.   I suggested ASP to show the general area in the sky that Webb would be, not a specific spot to actually find it in a scope. I guess ASP would be accurate if Webb was kept  precisely in 1 spot.  However, it orbits thousands of miles around that spot so you do need some other program to accurately track it.

**Comment by gzotti** [comment] 2023-02-14 23:10
This trajectory was a one-time thing. The satellite plugin is not capable of doing it. Spacecraft trajectories are requested in another issue. We can close this.

**Closed by gzotti** 2023-02-14 23:10 UTC
Labels: importance: low
