### ISSUE TITLE
Telescope Controls not working in 23.2

### ISSUE THREAD

**Issue by PDAngilley** [Stellarium/stellarium#3305] opened 2023-07-05 03:34 UTC
I have installer 23.2, from 20.3 and now the Telescope Controls does not work.
I connect the LX200 via an RS-232 cable that works with 20.3.
Reguards Phil Angilley.

**Comment by alex-w** [comment] 2023-07-05 04:15
Please attach log.txt file from Stellarium

**Comment by alex-w** [comment] 2023-07-05 04:18
Probably duplicate of issue #2934 and fixed via PR #3301

**Comment by alex-w** [comment] 2023-07-05 15:24
Hello @PDAngilley!

Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by PDAngilley** [comment] 2023-07-05 21:58
Hi Alexander,

 

This is the log file when the Telescope Control would not connect.

 

 

Regards,
Phil Angilley
Observing Officer NSAS

PDAngilley
89 Ryan Place
Beacon Hill
2100
02 9939 7319
0448 120 178

 ***@***.***> ***@***.***

**Comment by PDAngilley** [comment] 2023-07-05 22:32
Hi Alexander,

 

The Telescope patch worked, I now have control of my LX-200.

Thank you

 

Regards,
Phil Angilley
Observing Officer NSAS

PDAngilley
89 Ryan Place
Beacon Hill
2100
02 9939 7319
0448 120 178

 ***@***.***> ***@***.***

**Closed** 2023-07-06 01:17 UTC
Labels: bug
