### ISSUE TITLE
Has satellite plugin supported 3le format?

### ISSUE THREAD

**Issue by TurnOffNOD** [Stellarium/stellarium#3239] opened 2023-05-24 14:01 UTC
**Is your feature request related to a problem? Please describe.**
Not relate to a bug or issue.

According to https://celestrak.org/NORAD/documentation/gp-data-formats.php , TLE/2le format has limitation that can't be overcome, and 3le format is the future.

**Describe the solution you'd like**
I am not sure whether satellite plugin has supported 3le format, if not, add 3le format support.

**Comment by alex-w** [comment] 2023-05-24 14:10
Duplicate of #2458

**Closed** 2023-05-24 14:12 UTC
Labels: duplicate
