### ISSUE TITLE
Pluto and Charon

### ISSUE THREAD

**Issue by kevinluhman** [Stellarium/stellarium#1021] opened 2020-03-28 23:49 UTC
I recently installed the latest version of Stellarium for Mac, and found that when planet labels are enabled and I move to a location on Pluto or Charon, the labels of other bodies in that system jitter in the sky. Also, I find that for any location on Charon, I can see Pluto in the sky at some point during Charon's day even though Charon is supposed to be tidally locked to Pluto so that it always keeps the same face toward Pluto. In that scenario, Pluto should always appear near the same location in the sky from a point of view on half of Charon, and for the other half of Charon, Pluto should never appear in the sky. The latter issue occurs for both the latest version of Stellarium and the previous version I was using (0.18.1).

**Comment by gzotti** [comment] 2020-03-29 00:09
Interesting. I remember fixing the jitter visible on a Windows system (float->double). It still does not jitter here.

**Comment by alex-w** [comment] 2020-03-29 18:31
@gzotti, are you tried reproduce the tidal lock issue?

**Comment by gzotti** [comment] 2020-03-29 18:51
I think I checked it briefly a few months ago, but the elements are from earlier times. I have no better data.

**Comment by alex-w** [comment] 2020-09-16 16:02
Duplicate of #151

**Closed by alex-w** 2020-09-16 16:02 UTC
Labels: bug, duplicate
