### ISSUE TITLE
Improve coordinate input

### ISSUE THREAD

**Issue by void4** [Stellarium/stellarium#2466] opened 2022-05-27 12:58 UTC
I'm often frustrated when inputting coordinates into the Position tab of the Search window.

Not only do right ascension and declination have to be pasted separately into the text fields, they also seem to only recognize the 12h 0m 0.00s and +0° 0' 0.00" and decimal (350.32 -23.3) formats. On many other sites and databases, coordinates are given in slightly different formats, such as:

18 10 33.94 -28 31 52.4 (no hms/dms units)
06:05:00 -23:32:01 (hms/dms separated by colons)

It would be nice to have a single text input where all these formats could be pasted (and ra+dec together), where they would then be separated and parsed and put into the existing ra/dec fields.

**Comment by alex-w** [comment] 2022-06-09 15:05
Duplicate of #701

**Closed as completed by alex-w** 2022-06-09 15:05 UTC
Labels: enhancement, community
