### ISSUE TITLE
Stars color index (B-V)

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#374] opened 2018-09-19 14:11 UTC
_Original report by Bernard Balusseau:_ https://bugs.launchpad.net/stellarium/+bug/1762194

Some stars, not all, have huge B-V color index shifts compared to classical photometric catalogs such as Ducati, 2002 or Nicolet, 1978.
Two examples on brighting stars:
* Arcturus 0.82 on Stellarium, 1.23 on Ducati, 2002
* Betelgeuse 1.52 on Stellarium, 1.85 on Nicolet, 1978.
Regards

**Comment by gzotti** [comment] 2018-09-27 08:42
(From original discussion)
Different catalog, different result...

http://vizier.u-strasbg.fr/viz-bin/VizieR-S?HIP%2027989
and even different in TYC
http://vizier.u-strasbg.fr/viz-bin/VizieR-4?-source=+I%2F239%2Ftyc_main&-from=nav&-nav=cat%3AI%2F311%26cat%3AI%2F239%26tab%3A%7BI%2F239%2Fhp_notes%7D%26key%3Asource%3D1311%2Fhip2%26key%3Asource%3D1239%2Fhip_main%26HTTPPRM%3A%26-out.add%3D.%26HIP%3D27989%26-go+%25%23Sesame%23%25%26

One task "somebody" should do in the next 5 years or so is switching to Gaia data, including correct proper motion. In this process, we should think about best non-positional data as well. Volunteers welcome.

**Comment by gzotti** [comment] 2019-12-21 16:59
This is actually a duplicate of #364 but both entries have interesting links.

**Comment by Atque** [comment] 2024-12-28 19:52
Surely solved by #3992?

**Comment by gzotti** [comment] 2024-12-28 20:27
Our B-V is created from the HIP/Gaia DR3 now. This is not necessarily the same as whatever Ducati or Nicolet have reported, but unless you can provide a cross index between those two catalogs, there is not much that can be done to reproduce anything but what's in DR3. Do not expect we use _your_ favourite catalog instead. However, now Stellarium shows 1.23 for Arcturus, and 1.85 for Beteigeuze, so the reported issue seems solved.

**Closed** 2024-12-29 05:30 UTC
Labels: duplicate, state: confirmed, importance: low, data

**Comment by henrysky** [comment] 2024-12-31 03:37
Just to add that $B-V$ index for most stars without HIP ids in the new star catalog are measured from low resolution Gaia optical spectra (so unlikely those $B-V$ will match any catalog) while stars with HIP have their $B-V$ pulled from SIMBAD whatever SIMBAD thinks is the best.

**Comment by gzotti** [comment] 2024-12-31 08:38
Ah, thanks. This info should go into the User Guide. Some people are using Stellarium for reference and may report "errors" when they find data in different catalogs. It would be fine if you name which Gaia list entries were processed with which algorithms.
