### ISSUE TITLE
rise/transit/set/day time change with the minute

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#994] opened 2020-03-11 09:50 UTC
### Expected Behaviour
fixed values throughout the day

### Actual Behaviour
values change during the day

![image](https://user-images.githubusercontent.com/3529789/76403847-d3985f00-6385-11ea-80f8-b3feda1fe2e0.png)

![image](https://user-images.githubusercontent.com/3529789/76403874-deeb8a80-6385-11ea-98f8-37cd7fa78659.png)

### Steps to reproduce
1. select Moon or Venus (probably all planets)
1. choose a time well before midnight
1. observe that rise/transit/set times are presented
1. open time dialog
1. advance a few hours

### System
* Stellarium version: 6b9e9540c73714fef545d7db917b1f9e955e8ce1
* Operating system: Kubuntu 18

**Comment by axd1967** [comment] 2020-03-11 10:06
Stars seem to have the same issue.

**Comment by gzotti** [comment] 2020-03-11 10:35
duplicate of #554

**Closed** 2020-11-16 05:41 UTC
Labels: duplicate
