### ISSUE TITLE
toolTip message duplicate

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3786] opened 2024-06-27 19:49 UTC
### Expected Behaviour
  Other message is shown.

### Actual Behaviour
  "Equatorial coordinates, equinox of date" is shown.

### Steps to reproduce

1. Show Configuration window.
2. Move mouse cursor on checkBox "Hour angle/Declination".

Same message is shown when Move mouse cursor on other checkBox "Right ascension/Declination (of date)".
(Of course, it is correct message)

![20240628_1](https://github.com/Stellarium/stellarium/assets/173982253/7a85ba37-93d9-45ce-bea6-28f6c81f9388)

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

gui\configurationDialog.ui
line 670
        &lt;string&gt;Equatorial coordinates, equinox of date&lt;/string&gt;
line 762
        &lt;string&gt;Equatorial coordinates, equinox of date&lt;/string&gt;

There are same message.
Of course, it is correct message in line762.

However, it maybe not bug.

I am Japanese.
In Japanese Language, Two checkBox's toolTip message should be different.

However, I don't know how it should be in English.

thank you.

**Comment by gzotti** [comment] 2024-06-27 21:10
It is not a bug when it comes to us. What is the best English collective term for "hour angle + declination"? These are still equatorial coordinates in some sense. One has the main label "hour angle", the other "right ascension". 
If somebody knows a better wording for the tooltip, we take suggestions. 
If nobody comes up with a better name, we close this on September 20, at the latest.

**Comment by 3domennotry** [comment] 2024-06-28 17:12
thank you for reply.

This is my personal opinion.

Two same messages is separate  by "msgctxt" if it is possible.
I (and other people) can change native message.

The English message should be decided by English speakers.
(Of cource, I am not.)

As same as, Japanese translator team(I do not belong to) will decide Japanese message.

If I dislike translated word, I can change to my own use.

thank you.

**Comment by alex-w** [comment] 2024-07-02 04:52
Context was added for both lines

**Closed** 2024-07-02 04:52 UTC
Labels: enhancement, help wanted, importance: low

**Comment by 3domennotry** [comment] 2024-07-10 05:22
I have confirmed that two messages can be defined by "msgctxt".
Thank you very much.
