### ISSUE TITLE
sat plugin: locus of antisolar cone for selected satellite

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1246] opened 2020-09-01 21:32 UTC
**Is your feature request related to a problem? Please describe.**
I'm studying geosat flares ([link](http://www.satobs.org/geosats.html), [link](http://www.satobs.org/seesat/Feb-2007/0259.html)) and want to have a better idea of the cone of darkness that is created at a given distance.

**Describe the solution you'd like**
I want to select an object (satellite, moon, even planet) and see the cone of darkness at that object, as seen from my viewpoint.

So when I select a satellite, I want to see some kind of oval:
![image](https://user-images.githubusercontent.com/3529789/91906736-fa867c80-eca8-11ea-97a6-f3a78cdfd752.png)
To simulate this, I've created a marker with the aproximate center of the cone (Marker 1), and a circular FOV with a _very_ approximate size of 16 degrees for a geosat (~37000 km).

Another (more trivial) example is a lunar eclipse:
![image](https://user-images.githubusercontent.com/3529789/91907311-e68f4a80-eca9-11ea-8a75-88b3fd079a87.png)

When I select a satellite such as the ISS, I can then see where it will enter (or leave) earth shadow (this info is already plotted as the red/invisibliity segment on the orbit line)

This would also allow me to visualise the spot where I have to point a telescope where satellites will be seen diving into the earth shadow.

**Describe alternatives you've considered**

**Additional context**

https://en.wikipedia.org/wiki/Solar_transit

**Comment by gzotti** [comment] 2020-09-15 11:34
Practically a duplicate of #430

**Comment by axd1967** [comment] 2020-10-12 09:00
to be refined: replace with concepts of umbra, penumbra, antumbra.

**Comment by axd1967** [comment] 2021-02-23 22:08
(fixed for Moon in #430)

**Comment by axd1967** [comment] 2021-05-25 15:30
> Practically a duplicate of #430

the difference is that here we want to see the cone (shadow zone) for a selected satellite; this introduces a substantial parallax issue that is less critical for distant objects such as the Moon.

**Comment by gzotti** [comment] 2021-05-25 15:36
It is technically the absolute same thing. Just that you don't have one distance (moon), but 60.000 distances to all the current and coming satellites. Copy&paste the code into the satellite plugin and invent some distance selection manipulator to show one selected satellite, or play with plotting a shadow cone.

**Comment by axd1967** [comment] 2021-05-25 18:15
Maybe there is a misunderstanding here?

It's the same physical phenomenon, but the result is not the same. That's the essence of the issue: the user has to **select** a satellite in order to see the **local** shadow (for that satellite).

The Earth shadow extends around the ASP _at infinity_, but becomes larger for closer by objects.

In following screenshots, one can see that the ISS goes in and out of the shadow while the (pen)umbra is elsewhere.

![image](https://user-images.githubusercontent.com/3529789/119546583-5becff00-bd94-11eb-8f65-9e158af0b965.png)

![image](https://user-images.githubusercontent.com/3529789/119547737-c05c8e00-bd95-11eb-8758-3ac7201482fe.png)

**Comment by axd1967** [comment] 2021-05-25 18:28
(and this is indeed a sat plugin issue, not a general issue so I don't think it is solved with #430)

**Comment by gzotti** [comment] 2021-05-25 20:14
If you want a circle of earth's shadow in XY distance, it is technically the absolute same thing as #430, just copy/paste the code with your satellite's geocentric distance. Issue 1246 is not solved by fix 430 because issue 430 introduced shadow circles in Lunar distance. The problem is that one more shadow circle will not be enough for all satellites, so you will likely be flooded with useless circles.  The visualisation with orbit parts of varying brightness is probably clear enough for all but one user. Just decrease "segment length" and increase "number of segments" in the GUI. I will therefore not add such shadow circles, and I will not further comment on this now. Somebody who is interested in it can actually provide a pull request with working code instead of adding comments.

**Closed** 2022-05-22 10:30 UTC
Labels: feature request, good first issue

**Comment by axd1967** [comment] 2022-11-06 20:32
Much ado about nothing... See #2451 
Thank you @Carz10
