### ISSUE TITLE
Création Vue Capteur

### ISSUE THREAD

**Issue by marc5078** [Stellarium/stellarium#1403] opened 2020-12-10 22:46 UTC
Bonjour,
J'ai pu créer une vue oculaire mais ...
IMPOSSIBLE de créer une vue Capteur.
Quand j'essai de rentrer des valeurs, Stellarium se ferme automatiquement.
Merci
Marc B.

**Comment by axd1967** [comment] 2020-12-10 23:38
quelle version vous employez?
pourriez-vous attacher le fichier `log.txt`? (le chemin se trouve en tapant "F1")
![image](https://user-images.githubusercontent.com/3529789/101842795-1d96b700-3b49-11eb-8ae9-ffc94a0d2bb2.png)

**Comment by marc5078** [comment] 2020-12-13 14:37
J'utilise la dernière version accessible : 0.20.3

Voici un copier du journal:
C:\Users\MARC\AppData\Roaming\Stellarium/log.txt:
2020-12-13T15:30:33
Operating System: Windows 10 (10.0)
Compiled using MSVC++ 15.9 (Visual Studio 2017)
Qt runtime version: 5.12.6
Qt compilation version: 5.12.6
Addressing mode: 64-bit
Total physical memory: 7971 MB
Available physical memory: 4561 MB
Physical memory in use: 42%
Processor speed: 2295 MHz
Processor name: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
Processor speed: 2295 MHz
Processor name: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
Processor speed: 2295 MHz
Processor name: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
Processor speed: 2295 MHz
Processor name: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
C:\Program Files\Stellarium\stellarium.exe 
 -----------------------------------------------------
[ This is Stellarium 0.20.3 - https://stellarium.org/ ]
[ Copyright (C) 2000-2020 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "C:\\Users\\MARC\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\MARC\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file is:  "C:\\Users\\MARC\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "4.4.0 - Build 20.19.15.5126"
Current Format:  QSurfaceFormat(version 4.4, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::CompatibilityProfile)
StelMainView::init
Detected: OpenGL "4.4"
Driver version string: "4.4.0 - Build 20.19.15.5126"
GL vendor is "Intel"
GL renderer is "Intel(R) HD Graphics 5500"
GL Shading Language version is "4.40 - Build 20.19.15.5126"
GLSL Version Number detected:  4.4
GLSL version is fine, we should not see a graphics problem.
Cache directory is:  "C:\\Users\\MARC\\AppData\\Local\\stellarium\\stellarium\\cache"
Sky language is  "fr_FR"
Planetary features language is  "fr_FR"
Application language is  "fr_FR"
Scripts language is  "fr_FR"
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
SolarSystem has  83 entries.
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "C:\\Users\\MARC\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"
SolarSystem has  190 entries.
Loaded 107 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15669 / 15671 items of planetary surface nomenclature
WARNING - The next planets to assign nomenclature items is not found: "Dactyl"
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading .\\stars\\default\\stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading .\\stars\\default\\stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
"Loading C:\\Users\\MARC\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_4_1v0_2.cat: 4_1v0_4; 1692779"
"Loading C:\\Users\\MARC\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_5_2v0_1.cat: 5_2v0_1; 7083058"
"Loading C:\\Users\\MARC\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_6_2v0_1.cat: 6_2v0_1; 24670782"
"Loading C:\\Users\\MARC\\AppData\\Roaming\\Stellarium\\stars\\default\\stars_7_2v0_1.cat: 7_2v0_1; 50733321"
Finished loading star catalogue data, max_geodesic_level:  7
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4507 / 4507 scientific star names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6862 / 6862 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
Loading parallax errors data from ".\\stars\\default\\hip_plx_err.dat"
Loaded 117703 / 117703 parallax error data records for stars
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.11 (standard edition)"
Loaded 94671 DSO records
Loading DSO outline data ...
Loaded 82 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
getDecAngle failed to parse angle string:  "+49d04'0''N"
getDecAngle failed to parse angle string:  "-01d13'14''O"
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 1004 / 1004 common star names
Loading DSO name data ...
Loaded 1122 / 1144 DSO name records successfully
WARNING - No position data for 22 objects: "PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 44750, PGC 54559, PGC 59117, PGC 59858, PGC 59953, PGC 69018, PGC 69877, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Loaded 82 / 82 asterism records successfully for culture "western"
Loaded 72 / 72 asterism names
stel.OpenGLArray: Disabling VAO usage because of Intel driver bugs
stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: "C:\\Users\\MARC\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
Loaded plugin "NavStars"
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\MARC\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Oculars"
Oculars::validateAndLoadIniFile() ocular.ini exists at:  "C:\\Users\\MARC\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateAndLoadIniFile() found existing ini file version  3.1
Loaded plugin "Pulsars"
[Pulsars] Version of the format of the catalog: 2
[Pulsars] Loading catalog file: "C:\\Users\\MARC\\AppData\\Roaming\\Stellarium\\modules\\Pulsars\\pulsars.json"
Loaded plugin "Quasars"
[Quasars] Version of the format of the catalog: 1
[Quasars] Loading catalog file: "C:\\Users\\MARC\\AppData\\Roaming\\Stellarium\\modules\\Quasars\\quasars.json"
Loaded plugin "Satellites"
[Satellites] loading catalogue file: "C:\\Users\\MARC\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Satellite has invalid orbit: "SIRIUSSAT-1" "43595"
Satellite has invalid orbit: "SIRIUSSAT-2" "43596"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
Initializing planets GL shaders... 

![bugstellarium](https://user-images.githubusercontent.com/75814655/102015004-26f66e00-3d59-11eb-9e4c-b377e3ac24a5.jpg)

**Comment by alex-w** [comment] 2020-12-13 14:45
Please attach oculars.ini file (I do not see any problem in the log)

**Comment by marc5078** [comment] 2020-12-13 21:19
I don't find this file.
Can you say me where is it ?

**Comment by alex-w** [comment] 2020-12-13 23:02
From the log: C:\Users\MARC\AppData\Roaming\Stellarium\modules\Oculars\ocular.ini

**Comment by marc5078** [comment] 2020-12-14 09:55
[General]
oculars_version=3.1
use_max_exit_circle=true
ocular_count=1
ccd_count=0
telescope_count=1
enable_control_panel=true
use_decimal_degrees=true
autolimit_stellar_magnitude=true
limit_stellar_magnitude_oculars=true
limit_stellar_magnitude_oculars_val=12.00
lens_count=0
require_selection_to_zoom=true
use_initial_fov=false
use_initial_direction=false
use_semi_transparency=true
transparency_mask=10
hide_grids_and_lines=true
use_mount_autoset=false
use_telrad_fov_scaling=true
use_ccd_fov_scaling=false
show_resolution_criteria=false
arrow_scale=150
show_toolbar_button=false
show_ccd_crop_overlay=false
ccd_crop_overlay_pixel_grid=false
ccd_crop_overlay_hsize=250
ccd_crop_overlay_vsize=250
show_ocular_contour=true
show_ocular_cardinals=false
align_crosshair=false
show_focuser_overlay=false
use_small_focuser_overlay=false
use_medium_focuser_overlay=true
use_large_focuser_overlay=false
ocular_index=0
telescope_index=0
ccd_index=-1
lens_index=-1
stars_scale_relative=1.00
stars_scale_absolute=1.00
stars_scale_relative_ccd=1.00
stars_scale_absolute_ccd=1.00
text_color="0.800000,0.480000,0.000000"
line_color="0.770000,0.140000,0.160000"
focuser_color="0.000000,0.670000,1.000000"

[ocular]
0\name=Evscope
0\afov=23
0\efl=10
0\fieldstop=0
0\binoculars=false
0\permanentCrosshair=false
0\reticlePath=

[telescope]
0\name=Evscope
0\focalLength=450
0\diameter=114.3
0\vFlip=false
0\hFlip=false
0\equatorial=false

**Comment by alex-w** [comment] 2020-12-14 10:01
OK, you have zero CCD - of course Stellarium will be crash because he expect at least one CCD :-/

**Comment by alex-w** [comment] 2020-12-14 10:02
Duplicate of #1407

**Closed** 2020-12-14 10:03 UTC
Labels: duplicate
