### ISSUE TITLE
Stellarium 0.19.1.17157 issue with 4k screen

### ISSUE THREAD

**Issue by kajaji** [Stellarium/stellarium#763] opened 2019-09-16 14:33 UTC
Stellarium 0.19.1.17157 on windows 10 and high dpi screen shows very small bars, windows and characters.

Log:
2019-09-16T17:18:30
Operating System: Windows 10 (10.0)
Compiled using MSVC++ 14.0 (Visual Studio 2015)
Qt runtime version: 5.9.8
Qt compilation version: 5.9.8
Addressing mode: 64-bit
Total physical memory: 32589 MB
Available physical memory: 21339 MB
Physical memory in use: 34%
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Processor speed: 2808 MHz
Processor name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
C:\Program Files\Stellarium\stellarium.exe 
 --------------------------------------------------------------------
[ This is Stellarium 0.19.1.17157 [master] - https://stellarium.org/ ]
[ Copyright (C) 2000-2019 Fabien Chereau et al.                      ]
 --------------------------------------------------------------------
Writing log file to: "C:\\Users\\aaaaa\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\aaaaa\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file is:  "C:\\Users\\aaaaa\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "4.6.0 NVIDIA 431.36"
Current Format:  QSurfaceFormat(version 4.6, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))
StelMainView::init
Detected: OpenGL "4.6"
Driver version string: "4.6.0 NVIDIA 431.36"
GL vendor is "NVIDIA Corporation"
GL renderer is "GeForce GTX 1050/PCIe/SSE2"
GL Shading Language version is "4.60 NVIDIA"
GLSL Version Number detected:  4.6
GLSL version is fine, we should not see a graphics problem.
Cache directory is:  "C:\\Users\\aaaaa\\AppData\\Local\\stellarium\\stellarium\\cache"
Sky language is  "en_US"
Planetary features language is  "en_US"
Application language is  "en_US"
Couldn't load translations for language  "en_US" in section "stellarium-scripts"
Empty translation file for language  "en_US" in section "stellarium-scripts"
Scripts language is  "en_US"
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
Loaded 82 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "C:\\Users\\aaaaa\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"
Loaded 103 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15570 / 15583 items of planetary surface nomenclature
WARNING - The next planets to assign nomenclature items is not found: "Dactyl, Puck, Ryugu"
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_7.cat: 0_0v0_7; 4979"
"Loading .\\stars\\default\\stars_1_0v0_7.cat: 1_0v0_7; 21806"
"Loading .\\stars\\default\\stars_2_0v0_7.cat: 2_0v0_7; 150850"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
Finished loading star catalogue data, max_geodesic_level:  3
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4507 / 4507 scientific star names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6916 / 6916 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
StelCore: Invalid timezone name: ""  -- not setting timezone.
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
[...] "Stellarium DSO Catalog, version 3.7 (standard edition)"
Loaded 94393 DSO records
Loading DSO outline data ...
Loaded 63 DSO outline records successfully
Failure getting IP-based location: 
	 "Error creating SSL context ()"
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 930 / 930 common star names
Loading DSO name data ...
Loaded 1070 / 1085 DSO name records successfully
WARNING - No position data for 15 objects: "NGC 7088, PGC 2906, PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 54559, PGC 59117, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  75 for culture "western"
Loaded 65 / 66 asterism records successfully for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
Loaded 55 / 56 asterism names
stel.OpenGLArray: Vertex Array Objects are supported
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\aaaaa\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: "C:\\Users\\aaaaa\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\aaaaa\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Oculars"
Ocular plugin - press Command-O to toggle eyepiece view mode. Press ALT-o for configuration.
Oculars::validateIniFile ocular.ini exists at:  "C:\\Users\\aaaaa\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateIniFile found existing ini file version  3.1
Loaded plugin "Satellites"
[Satellites] loading catalog file: "C:\\Users\\aaaaa\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
Dubious result: Landscape  "Guereins"  not calibrated. Opacity test represents mathematical horizon only.

![Stellarium_Hdpi](https://user-images.githubusercontent.com/34771982/64966631-d1a68500-d8a7-11e9-83a8-d9240ed50f78.jpg)

**Comment by kajaji** [comment] 2019-09-19 11:17
The Stellarium display in 4K, is in fact, sharp and more pleasant than last release 19.1. There is an issue with the size of the down and side bars. If fonts can be enlarged to more the maximum values of 30 and 25, it would solve the both the windows and small font issue.

**Comment by gzotti** [comment] 2019-09-21 08:31
The major problem around 4k is that no developer has a 4k screen to look at it. The icons were designed around ordinary screens and will of course look jaggy when upscaled onto a 4k screen (and, I presume, observed with magnifying glasses), and the ways how operating systems deal with 4k issues vary, i.e. settings that work on Linux may not work on Windows or Mac.

**Comment by henrysky** [comment] 2020-08-28 03:32
@alex-w I suggest Stellarium to re-enable HighDPI scaling in manifest as I don't see any issue regarding UI elements being too small by enabling it in 0.20.2

False (everything is blurry and especially orbit lines are not smooth):
![no_dpiaware](https://user-images.githubusercontent.com/28623434/91518090-5cb43b80-e8bd-11ea-87d7-13a6521a2962.png)

True (everything is clear and especially orbit lines are smooth):
![dpi_aware](https://user-images.githubusercontent.com/28623434/91518111-689ffd80-e8bd-11ea-85c9-88746b8baea1.png)

**Comment by alex-w** [comment] 2020-08-28 06:03
@henrysky are you tried switch dpiAware settings and build Stellarium from source code on HiDPI PC?

**Comment by henrysky** [comment] 2020-08-28 06:26
Yes I built it with the edited manifest and this is the screenshot with the latest commit, 4k with 200% scaling

![rebuild_dpiaware](https://user-images.githubusercontent.com/28623434/91528485-cfc9ac00-e8d5-11ea-84f0-01cccb87b2d3.png)

**Comment by alex-w** [comment] 2020-08-28 06:40
Please show screenshot with 100% scale

**Comment by henrysky** [comment] 2020-08-28 06:52
> Please show screenshot with 100% scale

![Untitled](https://user-images.githubusercontent.com/28623434/91530681-84b19800-e8d9-11ea-9a16-20f0a9295b83.png)

**Comment by alex-w** [comment] 2020-08-28 10:21
Please install this version (https://ci.appveyor.com/api/buildjobs/6fh6ixc4x5fbmlfk/artifacts/stellarium-0.20.2.18205-win64.exe) and check work of all shortcuts from Stellarium group.

**Comment by kajaji** [comment] 2020-08-28 12:58
Hello Alex. 
I installed this version.
Only one issue with Arabic (right to left language), The cardinal points are written backwards, For example, South appears as htuoS (In Arabic), but the intercardinal points (two words) are written correctly like South East etc.

In Arabic there is no  abbreviation like S W SE .. , so in translation I have to write the whole word like: South or South East.
![S20HD](https://user-images.githubusercontent.com/34771982/91563164-16a3ba00-e947-11ea-9ceb-c529de195948.png)

**Comment by alex-w** [comment] 2020-08-28 13:01
Khalid, could you check translations on transifex?

**Comment by kajaji** [comment] 2020-08-28 14:12
It looks normal on tansifex.

**Comment by alex-w** [comment] 2020-08-28 14:49
@kajaji I cannot reproduce the issue on Linux

@gzotti could you check it on Windows?

**Comment by alex-w** [comment] 2020-08-28 14:49
@kajaji @henrysky please check scale feature

**Comment by kajaji** [comment] 2020-08-28 15:08
What is the scale feature?

**Comment by henrysky** [comment] 2020-08-28 17:52
@kajaji sorry but I still do not know what language you are referring to so I check a few language and this one seems to be the same as your screenshot although left/right flipped, 0.20.2.18205

![arab](https://user-images.githubusercontent.com/28623434/91600209-92950680-e935-11ea-8371-162750eccebe.png)

**Comment by henrysky** [comment] 2020-08-28 18:05
> Please install this version (https://ci.appveyor.com/api/buildjobs/6fh6ixc4x5fbmlfk/artifacts/stellarium-0.20.2.18205-win64.exe) and check work of all shortcuts from Stellarium group.

Other shortcuts also looks fine to me (I have also checked fractional scaling 125% 150% 175% scaling too) where 125% mapped to 100% and 150% 175% mapped to 200% scaling (I think it is a feature by Qt not doing fractional scaling?)

**Comment by kajaji** [comment] 2020-08-28 18:58
Thanks.
Yes, Arabic, and the words display is right on your screen.

I have an issue only with East, South, West, North words. They are displayed in reverse. Everything else seems fine.

My system is windows 10.

**Comment by henrysky** [comment] 2020-08-28 19:06
is your system language in Arabic? I am wondering if your system flipped the words somehow and then Stellarium flips them again?

**Comment by kajaji** [comment] 2020-08-28 19:12
No, the system language is English.
The issue is only with the main four cardinal points.

**Comment by gzotti** [comment] 2020-08-28 19:40
Sounds really weird. Does Qt have a problem with translating 1-letter strings into RTL? (The original strings "N", "E", "S", "W")

**Comment by kajaji** [comment] 2020-08-28 19:47
The words are displayed correctly on @henrysky screen. 
I downloaded the translation to check for multi word translation for the four cardinal points of but the result is the same.
Older versions are fine in my windows system.

**Comment by alex-w** [comment] 2020-08-29 03:18
@henrysky could you show screenshots for "Start > Stellarium > Stellarium" and "Start > Stellarium > Stellarium (2X scale)" shotcuts?

**Comment by henrysky** [comment] 2020-08-29 03:38
![18205](https://user-images.githubusercontent.com/28623434/91627738-8d60a780-e987-11ea-9362-156e6d5fcc7c.png)


``Stellarium (2X scale)`` is  a dead .ink

![image](https://user-images.githubusercontent.com/28623434/91627698-2642f300-e987-11ea-9971-0785cb80d36a.png)

**Comment by alex-w** [comment] 2020-08-29 05:53
@henrysky Please install new snapshot (https://ci.appveyor.com/api/buildjobs/k1t5meq2wc93xaqx/artifacts/stellarium-0.20.2.18206-win64.exe) and show screenshots for both shortcuts (from my previous comment)

**Comment by alex-w** [comment] 2020-08-29 06:26
please check this snapshot also: https://ci.appveyor.com/api/buildjobs/pa4pt6i8f6obfdrj/artifacts/stellarium-0.20.2.18207-win64.exe

**Comment by kajaji** [comment] 2020-08-29 11:58
I installed 18206. with any scale less than 100% the issue in Arabic disappears.

Here is a gif of 50% 80% 90% 100% and 200% scale.
![Stellarium-Scale](https://user-images.githubusercontent.com/34771982/91636266-ecfe9780-ea07-11ea-8a7b-0bc1ce5fe33e.GIF)

**Comment by alex-w** [comment] 2020-08-29 12:00
@kajaji could you show screenshot for shortcut  "Start > Stellarium > Stellarium (2X scale)"?

**Comment by kajaji** [comment] 2020-08-29 12:07
@alex-w 
The last 2 of the gif 
Here is a screenshot:

![2XScale](https://user-images.githubusercontent.com/34771982/91636448-3996a280-ea09-11ea-969e-201568b64e16.png)
are 2X scale.

**Comment by alex-w** [comment] 2020-08-29 12:09
I need to check enabling scaling Stellarium GUI without changes properties of shortcuts

**Comment by kajaji** [comment] 2020-08-29 12:10
@alex-w 
This is the command I used:
"C:\Program Files\Stellarium_20.2_HiDPI\stellarium.exe" --user-dir=C:\Users\kj\AppData\Roaming\Stellarium_20.2_HiDPI --scale-gui 2.0 -platform windows:altgr

**Comment by alex-w** [comment] 2020-08-29 12:12
@kajaji thanks!

**Comment by kajaji** [comment] 2020-08-29 14:56
For scale 1.5 or greater star names (In Info strings) are displayed in reverse for Arabic, but setting the font size smaller for screen in the Main>Tools panels will fix the issue.
The font size for cardinal points is not controlled by the font size selected for GUI or screen. for any scale of 1 or greater the main cardinal points are displayed in reverse for RTL language. If the scale goes greater than 1.5 then all cardinal and intermediate points will be reversed. For any scale less than 1 ( I experimented with .95 and less) all cardinal points are displayed correctly.

**Comment by henrysky** [comment] 2020-08-29 14:57
stellarium
![new](https://user-images.githubusercontent.com/28623434/91639682-4e157380-e9e6-11ea-8e5a-5dfc6aaad032.png)

stellarium (2x)
![new2x](https://user-images.githubusercontent.com/28623434/91639689-553c8180-e9e6-11ea-98c3-06340f95b64c.png)

**Comment by alex-w** [comment] 2020-08-29 15:03
@henrysky please try build branch https://github.com/Stellarium/stellarium/tree/windows-hipdi

**Comment by henrysky** [comment] 2020-08-29 20:29
@alex-w it compiled successfully and things look fine

4K 200% scaling
![compiled](https://user-images.githubusercontent.com/28623434/91645627-aa8f8780-ea14-11ea-96c9-c255c14f1147.png)

4K 100% scaling with Stellarium (2X scale)
![compiled_2x](https://user-images.githubusercontent.com/28623434/91645638-bda25780-ea14-11ea-8ae7-09c821a4e4bb.png)

**Comment by alex-w** [comment] 2020-08-30 05:04
@henrysky @kajaji could you write an instructions for enable scaling application on Win 10 with screenshots?

**Comment by alex-w** [comment] 2020-08-30 08:25
@henrysky @kajaji please try build branch master and check new shortcuts

**Comment by henrysky** [comment] 2020-08-31 01:11
> @henrysky @kajaji please try build branch master and check new shortcuts

Those 200% sacling shortcuts look fine to me


> @henrysky @kajaji could you write an instructions for enable scaling application on Win 10 with screenshots?

What you mean by enable scaling application? like the whole Windows-wise scaling like this https://www.windowscentral.com/how-set-custom-display-scaling-setting-windows-10?

**Comment by alex-w** [comment] 2020-08-31 01:20
Please check version 0.20.2.18210

**Comment by henrysky** [comment] 2020-08-31 17:12
> Please check version 0.20.2.18210

Where is 18210? The one I built from master (b92f2b4c4b) is newer at 18223

**Comment by alex-w** [comment] 2020-08-31 17:31
See https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by henrysky** [comment] 2020-08-31 17:51
Nah those shortcut is not working as expected, also I think the high dpi scaling is disabled in manifest in 18210 because everything look pixelated....

**Comment by alex-w** [comment] 2020-08-31 17:56
Please show screenshot when Stellarium started through standard and scaled shortcuts

**Comment by henrysky** [comment] 2020-08-31 18:05
4K 200% scaling PC, standard and scaled shortcuts look exactly the same

![Untitled](https://user-images.githubusercontent.com/28623434/91751436-c15be880-eb92-11ea-94e1-7deab31708ab.png)


scaled shortcut

![Untitled2](https://user-images.githubusercontent.com/28623434/91751605-0a13a180-eb93-11ea-8c94-b7843896b37f.png)

**Comment by alex-w** [comment] 2020-08-31 18:13
@gzotti please check working of new shortcuts on your hardware

**Comment by alex-w** [comment] 2020-08-31 18:15
@henrysky Which version of Qt installed on your PC for development?

**Comment by henrysky** [comment] 2020-08-31 18:18
> @henrysky Which version of Qt installed on your PC for development?

Qt 5.15.0, vs2019 16.7.2

**Comment by kajaji** [comment] 2020-08-31 19:01
Same here. Scaling has no effect on 18210 and resolution is not as sharp as 18206.

**Comment by gzotti** [comment] 2020-08-31 19:03
> 
> 
> @gzotti please check working of new shortcuts on your hardware

You are publishing betas faster than I can download them...
In 18205 I saw no scaling shortcut.
In 18206 I see a 2x scaling shortcut. Huge splash, and large GUI. Pixel sharp on my system (Geforce 960M), not blurry. 
In 18210 I see no scaling shortcut.

I would have to reboot my system to try something around Windows integrated scaling. Sorry, maybe later, too many open programs right now....

**Comment by alex-w** [comment] 2020-09-01 08:42
> In 18210 I see no scaling shortcut.

This is very strange, I'll check it

**Comment by gzotti** [comment] 2020-09-04 09:35
OK, a few screenshots: (Info for other readers: a "screenshot" is not really just that. We are creating a different image, and some settings have to be applied differently.)

Build 18206 with Link "x2" and 100% display scaling shows nice sharp text and thin lines, but the menu is shifted in a screenshot.
![18206-x2_sharpText-thinLines_menuDisplaced](https://user-images.githubusercontent.com/18099873/92223338-9b8b5800-eea0-11ea-9279-a65751e7d0a8.jpg)
Build 18206 with Link "x2" and 200% display scaling starts with a splash that exceeds screen size, and then has a menu that exceeds the screen canvas. The screenshot has the menu displaced again with top-left button clipped where it is clipped on-screen. 
![18206-x2@200pct_menuDisplaced](https://user-images.githubusercontent.com/18099873/92223564-ef963c80-eea0-11ea-89cf-c5367ec32a58.jpg)

Build 18210 has no "x2" link, which I find better anyhow. Applying Windows own screen scaling at 100% is good as always:
![18210@100pct_allPerfect](https://user-images.githubusercontent.com/18099873/92223670-15bbdc80-eea1-11ea-93b8-c058a5e37d02.jpg)
Build 18210 at 150%: Menu where it belongs, just larger. Of course somewhat blurred, there is IMHO no way around that, apart from providing multiple sets of scaled icons. Stars are scaled. 
![18210@150pct_allPerfect](https://user-images.githubusercontent.com/18099873/92223756-31bf7e00-eea1-11ea-938a-2072b419c5f1.jpg)
Build 18210 at 200%: Menus where they belong, larger, and sharp again.
![18210@200pct_allPerfect](https://user-images.githubusercontent.com/18099873/92224421-15701100-eea2-11ea-84e1-c3ee35969cb3.jpg)

These tests were made on an 3440x1440 monitor, not yet 4k...

**Comment by alex-w** [comment] 2020-09-04 11:11
Please check current master - I've added few (2x) links

**Comment by alex-w** [comment] 2020-09-15 06:10
What about latest beta and last changes in the code - can we close this issue or not?

**Comment by kajaji** [comment] 2020-09-15 06:20
I'm using 18227 with --scale-gui 0.7 and windows 10 250% scaling.

No issues.

**Comment by alex-w** [comment] 2020-09-15 08:04
OK, thanks!

**Closed by alex-w** 2020-09-15 08:04 UTC
Labels: enhancement
