### ISSUE TITLE
Wrong Coordinates for High Proper Motion Stars (eg. Proxima)

### ISSUE THREAD

**Issue by spto** [Stellarium/stellarium#1061] opened 2020-04-22 17:42 UTC
I measured the location of Proxima Centauri at 2020-04-22 12:57:47 UTC and found it at 14:29:31.87 -62:40:31.28 (J2000). Yet Stellarium predicted 14:29:36.97 -62d40’24.1’’ (J2000) at that time. This is a ~36 arcsec difference. I have checked nearby (low proper motion) stars' location and they perfectly agree with Stellarium's prediction.

I'm not familiar with how Stellarium calculates high proper motion stars' location, and I have limited ability so I could only report this single case as an example. Hope some expert would know why!

Cheers
<img width="611" alt="stellarium" src="https://user-images.githubusercontent.com/20322835/80014989-b073da00-8503-11ea-9a96-eb037b26d3f2.png">

---LOG Head---
2020-04-23T01:31:24
Operating System: Darwin 18.2.0 x86_64
Compiled using Clang 9.0.0
Qt runtime version: 5.9.8
Qt compilation version: 5.9.8
Addressing mode: 64-bit
Model Name: MacBook Pro
Model Identifier: MacBookPro11,4
Processor Name: Intel Core i7
Processor Speed: 2.2 GHz
Number of Processors: 1
Memory: 16 GB
Chipset Model: Intel Iris Pro
VRAM (Dynamic, Max): 1536 MB
/Applications/Stellarium.app/Contents/MacOS/stellarium 
 -----------------------------------------------------
[ This is Stellarium 0.19.3 - https://stellarium.org/ ]
[ Copyright (C) 2000-2019 Fabien Chereau et al.       ]
 -----------------------------------------------------

**Comment by gzotti** [comment] 2020-04-22 19:57
Duplicate of #85 and several others. We know the program is not perfect. Open source means you can check and fix it. For most observers a coordinate mismatch below 1 arcminute is acceptable.

**Comment by jim77742** [comment] 2023-09-22 09:07
I independently found this problem with Proxima Centauri. The position of Proxima seems to be 10 years in error. I have a photo of the location of Proxima in a book from 1976. It matches with Stellarium when I set the date to 1986. I also compared to other photos on the internet from 2000-2010 and the 10 year error is still apparent.

I checked with Barnards's star and there is no problem with that. So I'm guessing there is a problem with the Proxima data and not the code?

I strongly disagree with above comments that this level of error is "acceptable". Proxima Centauri is the closest star and observers need to know precisely where it is. I think this important.

**Comment by Atque** [comment] 2023-09-22 11:07
Yes, a star catalog with 3D corrected proper motion is needed. Stellar proper motion is inaccurate in the far future and past for most stars, and even currently for some stars.

A few months ago, a partial fix was presented, but it caused lag for some systems and was never merged. I'm not sure if it would have fixed the Proxima Centauri position though. It seems a lot of work is needed to properly solve this.

**Comment by gzotti** [comment] 2023-09-22 11:16
Don't lament, just recreate the star catalog from 2006 properly, fixing one or two original bugs (not sure currently if Hipparcos' epoch 1991.5 is properly accounted for). The "partial fix" was a heavy kludge, not the solution we are after. Just take a month of vacation, study the catalog format and the somewhat underdocumented vector math behind it, and fix it. In the process, prefer Gaia over older positional data. Also, extract binaries in fast revolution and model them properly to avoid &alpha; Cen (and others) flying apart. And also find a solution for #348.

**Comment by jim77742** [comment] 2023-09-22 12:00
Can we avoid the snark? It's unprofessional. What is the actual problem here? 

Proxima Centauri is in error by about 10 years. Why is this happening, but yet Barnard's star is fine?

**Closed** 2024-12-25 00:43 UTC
Labels: bug, duplicate, state: confirmed, importance: low, state: in progress
