### ISSUE TITLE
Stars with altitude less than 21° disappear when zoomed in

### ISSUE THREAD

**Issue by mabatko** [Stellarium/stellarium#538] opened 2018-11-03 21:46 UTC
### Expected Behaviour
Stars are visible no matter how zoomed in you are and how high they are.

### Actual Behaviour
When you zoom in on a star as much as possible and its altitude above horizon is less than ~21° 30' it disappears. 

![stellarium-000](https://user-images.githubusercontent.com/41372990/47957553-43d7e900-dfb8-11e8-8e0c-ea1d247515ed.png)
![stellarium-001](https://user-images.githubusercontent.com/41372990/47957554-49cdca00-dfb8-11e8-942e-1d31b49f5ef0.png)

### Steps to reproduce
Pick a star which is below 21° 30' altitude and zoom in as much as possible - the star will disappear.
Stars below ~21° 25' always disappear, between 21° 25' and 21° 35' they flicker and above 21° 35' is everything OK. 

### System
* Stellarium version: stellarium-0.90.0.16375-win64.exe
* Operating system: Windows 7
* Graphics Card: Intel(R) HD Graphics Family

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/2545370/log.txt)

**Comment by gzotti** [comment] 2018-11-03 21:56
Duplicate of #365.

**Closed** 2018-12-11 22:01 UTC
Labels: duplicate
