### ISSUE TITLE
Relative brightness of planets is not realistic

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#2855] opened 2022-11-18 11:08 UTC
### Expected Behaviour

The Moon has much lower albedo than the Earth, as is demonstrated by [photos from DSCOVR](https://www.nasa.gov/feature/goddard/from-a-million-miles-away-nasa-camera-shows-moon-crossing-face-of-earth):

![](https://www.nasa.gov/sites/default/files/thumbnails/image/epicearthmoonstill.png)

Stellarium should reflect this in its render.

### Actual Behaviour

Current Stellarium shows the Moon brighter than the Earth:

![Screenshot - 181122 - 14:05:45](https://user-images.githubusercontent.com/6376882/202691351-1085bfa3-23aa-4def-908e-d442e0220cad.png)

### Steps to reproduce

1. Go to Venus
2. Set date&time to 2010-11-05 8:00:00 UTC
3. Point Stellarium to the Earth (e.g. via Search window)
4. Zoom to FOV~0.02°

**Comment by alex-w** [comment] 2022-11-18 11:13
Duplicate of #1012

**Closed** 2022-11-18 11:14 UTC
Labels: duplicate
