### ISSUE TITLE
adding national constellations of Ukraine

### ISSUE THREAD

**Issue by NataliiaZaharchuk** [Stellarium/stellarium#2526] opened 2022-07-20 17:38 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Good afternoon.  with whom you need to discuss the possibility of adding historical constellations from the territory of Ukraine to the Stelarium?  Now there is a project within the framework of which they will be drawn, placed in the appropriate places in the starry sky, and described.  I need to know how to make them public.
**Describe alternatives you've considered**

**Additional context**

**Comment by gzotti** [comment] 2022-07-20 17:44
Chapter 9 of the User Guide describes the file structure for skycultures. You can create it, and when you want to share it, decide upon a CC license to use, and contact us again. The best way is a "pull request" here on github. If you are not familiar with programming, just send the files to one of us. 

All the best in these times!

**Comment by NataliiaZaharchuk** [comment] 2022-07-20 17:52
Thank you

**Comment by alex-w** [comment] 2023-02-17 14:07
Duplicate of #2997

**Closed** 2023-02-17 14:08 UTC
Labels: duplicate
