### ISSUE TITLE
Crash when screenshoting

### ISSUE THREAD

**Issue by hflemmen** [Stellarium/stellarium#3527] opened 2023-12-01 14:01 UTC
### Expected Behaviour
Screenshot captured and saved.
### Actual Behaviour
1 second freeze and then the program exits.

### Steps to reproduce

1. Open program
2. Pres Ctrl+S to screenshot

### System
* Stellarium version: 23.3, from appimage called: "Stellarium-23.3-qt5-x86_64.AppImage" 
* Operating system: Linux Mint 21.2 (Similar to ubuntu 22.04 LTS)
* Graphics Card: Nvidia A2000, CUDA-version: 12.2 and Mesa Intel® UHD Graphics (TGL GT1).

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/13527396/log.txt)

**Comment by alex-w** [comment] 2023-12-01 16:18
@hflemmen please check this hint: https://github.com/Stellarium/stellarium/wiki/Common-problems-for-old-versions#crash-of-stellarium-on-linux-mint-when-opening-or-saving-files

**Comment by hflemmen** [comment] 2023-12-01 16:36
I missed that hint when making this issue, but the fix did not work. I tried with ubuntu 20.04 on the same hardware, and that worked, which indicates that Mint might be to blame.

**Comment by ilkant** [comment] 2023-12-02 14:02
Ctrl+S works perfect on Linux Kubuntu 23.10 and Stellarium 23.3.335 compiled with Qt6 on own computer.

**Comment by gzotti** [comment] 2023-12-02 14:07
Probably has to do with (1) being an AppImage on (2) Mint.

**Comment by alex-w** [comment] 2023-12-02 14:26
I can prepare an AppImage/Qt6 for testing

**Comment by alex-w** [comment] 2023-12-03 06:32
@hflemmen please check https://github.com/Stellarium/stellarium/suites/18704383880/artifacts/1088783766

**Comment by 10110111** [comment] 2023-12-04 09:33
> The log indicates a crash after beginning of shader compilation.

No it doesn't. This message doesn't normally end with any kind of a "closing message". So the log simply doesn't tell anything.

@hflemmen Please get a stack trace from the crash.

**Comment by 10110111** [comment] 2023-12-04 10:15
> it can be not an easy (due an AppImage architecture)

Why? Isn't it just a matter of setting `CMAKE_BUILD_TYPE` and avoiding any calls to `strip`?

**Comment by hflemmen** [comment] 2023-12-04 10:26
> P.P.S. @hflemmen do you have installed standard Linux Mint 21.2 (what about DE)?

No, I forgot. I have Linux Mint Mate, not Linux Mint Cinnamon, which is the default.

> See [this page](https://wiki.ubuntu.com/Backtrace).

I can have a look at it, but possibly not until tomorrow.

**Comment by gzotti** [comment] 2023-12-04 11:24
> > The log indicates a crash after beginning of shader compilation.
> 
> No it doesn't. This message doesn't normally end with any kind of a "closing message". So the log simply doesn't tell anything.

I wrote "after beginning", not "during". It tells us it came that far. Sure, it may be something else than shader cache accessibility. But it (and thus just configuration of that AppImage) can be one cause and (hopefully) simple item to check. I know however nothing about rules for SC locations within and outside of AppImage.

**Comment by alex-w** [comment] 2023-12-04 12:26
I've downloaded Linux Mint 21.2 and run it into VirtualBox (without installing). Next step - I've downloaded and run Stellarium 23.3. Taking a screenshot - no problems.

[linux.txt](https://github.com/Stellarium/stellarium/files/13545845/linux.txt)
[log.txt](https://github.com/Stellarium/stellarium/files/13545847/log.txt)

**Comment by alex-w** [comment] 2023-12-04 13:04
> The log ends even before zooming in to see any planet and trigger the message about planet shader compilation.

[log.txt](https://github.com/Stellarium/stellarium/files/13546230/log.txt)

![stellarium-002](https://github.com/Stellarium/stellarium/assets/88731/f600890d-e5ab-4f59-b2fd-879d12c0c594)

**Comment by alex-w** [comment] 2023-12-04 14:01
So, I can't reproduce the issue.

**Comment by 10110111** [comment] 2023-12-04 19:35
Why do we use `QGuiApplication::screenAt(halfSceneSize)` to get the screen to query geometry? Shouldn't we use the screen where our main window resides, i.e. `mainWindow->screen()`? It's completely possible that there's no screen (i.e. monitor) at particular coordinates.

**Comment by gzotti** [comment] 2023-12-04 20:50
With this we find the screen where the center of the window is. This may be helpful when moving the window from screen to screen. How does screen() determine partial visibility?

**Comment by 10110111** [comment] 2023-12-04 21:07
> With this we find the screen where the center of the window is.

The problem is that we determine the point from scene size, ignoring the position of the window. This then will bias the result towards the top-left screen.

> How does screen() determine partial visibility?

The screen returned is the one that determines widget properties like the HiDPI scaling coefficient. Usually it switches when the center of the window crosses the border between the screens (assuming they are adjacent).

**Comment by hflemmen** [comment] 2023-12-05 08:16
@alex-w I tried to do make a screenshot in window mode, but it still failed. Final output was:
```
Creating scene FBO with size 2560x1440
Initializing planets GL shaders... 
Creating scene FBO with size 1024x768
Segmentation fault (core dumped)
```
[log.txt](https://github.com/Stellarium/stellarium/files/13556983/log.txt)

I have three monitors. Two main, and one smaller.

**Closed** 2023-12-05 08:59 UTC
Labels: importance: critical, qt

**Comment by alex-w** [comment] 2023-12-05 09:52
@hflemmen please check https://github.com/Stellarium/stellarium/actions/runs/7098671881

**Comment by hflemmen** [comment] 2023-12-05 12:04
Thank you! I can confirm that it works now.
