### ISSUE TITLE
Upgrade of Stellarium from 1.0 to 1.1 on raspberry makes all graphics below horizon disappear including menus.

### ISSUE THREAD

**Issue by mgrouch** [Stellarium/stellarium#2811] opened 2022-11-02 03:45 UTC
Raspberry Pi Bullseye,
stellarium_1.1-upstream1.2~ubuntu20.04.1_arm64.deb

started using script:

```

#!/bin/bash

# hack to control Stellarium azimuth by true north heading from signalK

MESA_GL_VERSION_OVERRIDE=3.0 MESA_GLSL_VERSION_OVERRIDE=130 onlyone stellarium "$@"  &
sleep 12

i=0
while [[ -n "$(pidof stellarium)" ]]
do
  # magnetic variation
  if [[ $((i%20)) == 0 ]]; then
    MV=$(curl -s http://localhost:3000/signalk/v1/api/vessels/self/navigation/magneticVariation/value)
    i=0
  fi
  # magnetic heading
  MH=$(curl -s http://localhost:3000/signalk/v1/api/vessels/self/navigation/headingMagnetic/value)
  if [ -n "$MH" ] && [ -n "$MV" ]; then
    # true heading
    HT=$(echo "$MH" + "$MV" - 3.1415926535 | bc)
    # control Stellarium azimuth
    curl -X POST -d "az=$HT" 'http://localhost:8090/api/main/view'
  fi
  # control Stellarium location
  POS="$(curl -s http://localhost:3000/signalk/v1/api/vessels/self/navigation/position/ | jq -M -jr '"latitude=",.value.latitude,"&longitude=",.value.longitude')"
  if [ -n "$POS" ] && [ "latitude=null&longitude=null" != "$POS" ]; then
    curl -X POST -d "altitude=2&${POS}&name=Current" 'http://localhost:8090/api/location/setlocationfields'
  fi
  sleep 3
  i=$((i+1))
done

```

**Comment by mgrouch** [comment] 2022-11-02 03:55
Even if it is started like this:
`

MESA_GL_VERSION_OVERRIDE=3.0 MESA_GLSL_VERSION_OVERRIDE=130 stellarium
`

**Comment by alex-w** [comment] 2022-11-02 04:14
Please try `MESA_GL_VERSION_OVERRIDE=3.0 MESA_GLSL_VERSION_OVERRIDE=130 stellarium --opengl-compat`

**Comment by mgrouch** [comment] 2022-11-02 08:34
Still the same issue.

**Comment by alex-w** [comment] 2022-11-02 08:37
Please enable OpenGL debugging and share log from Stellarium

**Comment by mgrouch** [comment] 2022-11-02 08:40
How do I enable OpenGL debugging? Thanks

**Comment by alex-w** [comment] 2022-11-02 08:48
> How do I enable OpenGL debugging? Thanks

`stellarium --dump-opengl-details`

**Comment by mgrouch** [comment] 2022-11-02 09:00
Attaching log

[s.log](https://github.com/Stellarium/stellarium/files/9918294/s.log)

**Comment by mgrouch** [comment] 2022-11-02 09:19
Also why a previous working 1.0 .deb package is now not available for download in launchpad? Thanks

**Comment by 10110111** [comment] 2022-11-02 10:23
> makes all graphics below horizon disappear including menus

How does it look? Could you post a screenshot?

**Comment by mgrouch** [comment] 2022-11-02 10:51
> > makes all graphics below horizon disappear including menus
> 
> How does it look? Could you post a screenshot?

![expected](https://user-images.githubusercontent.com/8263013/199471451-7ce471db-1157-44de-bed6-4406b56a61cc.png)
![bad](https://user-images.githubusercontent.com/8263013/199471454-522b92e1-8067-4864-ae39-116956ab3afd.png)

**Comment by alex-w** [comment] 2022-11-02 11:41
I see in the log:
```
Xlib: sequence lost (0x101bd > 0x1bf) in reply type 0x0!
Xlib: sequence lost (0x101d4 > 0x1d6) in reply type 0x0!
Xlib: sequence lost (0x101d9 > 0x1db) in reply type 0x0!
Xlib: sequence lost (0x101de > 0x1e0) in reply type 0x0!
```
and something strange happening for initialisation of OpenGL profile - this is not very good

**Comment by gzotti** [comment] 2022-11-03 01:03
I see esp. Core 3.0 profile and Mesa. The RPi has no more, and should be forced to OpenGL ES2.0 mode. I am not available for testing this week.

**Comment by mgrouch** [comment] 2022-11-03 03:53
Why previous working version binaries were removed?

**Comment by alex-w** [comment] 2022-11-20 08:54
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by mgrouch** [comment] 2022-11-20 16:16
@alex-w 

arm64 version build is failing 

https://launchpadlibrarian.net/634918175/buildlog_ubuntu-focal-arm64.stellarium_1.0.90+202211192229~ubuntu20.04.1_BUILDING.txt.gz

thanks

**Comment by gzotti** [comment] 2022-11-20 16:42
Building master on my RPi4 (Ubuntu Mate 22.4.1, aarch64) works well, don't know what irritates the CI here.

**Comment by gzotti** [comment] 2022-12-09 15:03
> uname -a
> Linux rpi4-mate 5.15.0-1021-raspi #23-Ubuntu SMP PREEMPT Fri Nov 25 15:27:43 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
> 

[log.txt](https://github.com/Stellarium/stellarium/files/10195857/log.txt)
For me (RPi4, Ubuntu Mate 22.04.1) all looks OK with master.

**Comment by mgrouch** [comment] 2022-12-19 21:19
Doesn't look ok for me with Ubuntu 20.10.01. Everything in bottom part is missing except of background.

**Comment by alex-w** [comment] 2023-03-13 15:39
Please check packages from our PPA for beta

**Comment by gzotti** [comment] 2023-03-14 23:26
I have both `ppa.launchpadcontent.net/stellarium/stellarium-{release,beta}/ubuntu jammy InRelease` in my apt sources. I have 1.2 installed. Should there be a beta installed by a regular update?

**Comment by alex-w** [comment] 2023-03-15 09:20
> I have both `ppa.launchpadcontent.net/stellarium/stellarium-{release,beta}/ubuntu jammy InRelease` in my apt sources. I have 1.2 installed. Should there be a beta installed by a regular update?

I think - yes

**Comment by gzotti** [comment] 2023-03-15 09:57
Then something does not work around package provision in the PPA. 
Anyhow, I built from sources and still cannot reproduce the issue on RPi4/Ubuntu Mate 22.04.01/aarch64.

**Comment by alex-w** [comment] 2023-03-15 09:59
> Then something does not work around package provision in the PPA. Anyhow, I built from sources and still cannot reproduce the issue on RPi4/Ubuntu Mate 22.04.01/aarch64.

Hmm... What say `sudo apt upgrade -t stellarium-beta` ?

**Comment by gzotti** [comment] 2023-03-19 18:58
```
$ cat /etc/apt/sources.list.d/stellarium-ubuntu-stellarium-beta-jammy.list 
deb https://ppa.launchpadcontent.net/stellarium/stellarium-beta/ubuntu/ jammy main
# deb-src https://ppa.launchpadcontent.net/stellarium/stellarium-beta/ubuntu/ jammy main

```
```
$ sudo apt upgrade -t stellarium-beta
Paketlisten werden gelesen… Fertig
E: Der Wert »stellarium-beta« ist für APT::Default-Release ungültig, da solch eine Veröffentlichung in den Paketquellen nicht verfügbar ist.
```

(stellarium-beta invalid, no package available).

**Comment by gzotti** [comment] 2023-03-19 19:01
I assume a hardware/driver configuration issue. This should not block 23.1.

**Comment by alex-w** [comment] 2023-03-20 01:56
Hmm... please try use `ppa.launchpad.net` host in `sources.list` file

**Comment by gzotti** [comment] 2023-06-16 23:30
OK, finally. Did an apt update, apt dist-upgrade, and finally have 23.1.167-1671719 (tarball) on Qt6.2.4. And have 12fps of OpenGL2.1 on a smallish screen.  Note that I do not have @mgrouch 's configuration. On Ubuntu Mate it works flawlessly.

**Comment by gzotti** [comment] 2023-09-12 08:25
@mgrouch please update to Ubuntu 22.4LTS and try again. Else we close this as unreproducable on or after September 22.

**Closed** 2023-09-22 06:15 UTC
Labels: help wanted, need more info
