### ISSUE TITLE
Support FreeDesktop.org XDG basedir specification

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#461] opened 2018-09-26 06:52 UTC
_Original report by Eric Heintzmann:_ https://bugs.launchpad.net/stellarium/+bug/1088064

Please support FreeDesktop.org XDG basedir specification for stellarium

http://ploum.net/post/207-modify-your-application-to-use-xdg-folders
https://live.gnome.org/GnomeGoals/XDGConfigFolders
http://standards.freedesktop.org/basedir-spec/latest/

**Comment by gzotti** [comment] 2018-09-26 09:39
Duplicate of #76

**Closed by gzotti** 2018-09-26 09:39 UTC
Labels: duplicate, enhancement, opinion
