### ISSUE TITLE
Telescope Control: ASCOM Driver

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#406] opened 2018-09-26 05:15 UTC
_Original report by Mi.Holzner:_ https://bugs.launchpad.net/stellarium/+bug/1082196

Hi,

I would like to control differen Telescopes with Stellarium, as it is my favourite Sky-Software.
Many Drivers are available within the ASCOM project, i am sure, you know ASCOM.

So, is Stellarium TelescopeControl PlugIn would have a option for ASCOM-Driver in the telescope-Driver list - it would be possible to use it with every scope, where an Ascom driver exists.

Maybe advanced users have already written their own ascom-driver for use with different software - they would can use this driver then also with stellarium.

I saw this in the astrosurf c2a software - and it works great - but i would prefer to use Stellarium.. :-)

thanks,
Michael

**Comment by rederikus** [comment] 2019-07-18 22:02
I realize that you closed this thread but StellariumScope has not been updated for years.  ASCOM is the de-facto worldwide telescope control standard.  Yes, it only runs on Windows.  So what?  I use Cartes du Ciel on Windows and Linux, CdC uses Ascom where it is is available.  I use  Starry Night on Windows and that uses ASCOM on WIndows but not on other platforms.  Finally I use Sky Tools 3 and Virtual Moon.  Both use ASCOM only under Windows. bOviously where ASCOM is not available, it is not used.

Why oh why cannot Stellarium do the same?  Where a tool is available, USE IT.

I and I suspect many others would like the consistency of ASCOM across software platforms.  When using Stellarium I am denied focuser control, camera features and at least two of my telescopes are just not supported by Stellarium.  It NEEDS ASCOM.

Please do not get me wrong.  I love Stellarium.  However I would love it more if it supported ASCOM on Windows.

Please make this happen.

Thanks

**Comment by gzotti** [comment] 2019-07-19 16:30
I had closed this as duplicate of #271. Maybe we can close #271 instead? 

The problem is that no developer has an ASCOM controlled telescope, and no ASCOM controlled telescope owner was so far able to develop a patch and send it to us.  Stellarium has supported two widespread protocols for many years and has recently been enhanced to use RTS2 and INDI. I understand INDI as superior to ASCOM, and maybe your gear also supports INDI?

**Comment by rederikus** [comment] 2019-07-19 20:27
I am sorry I caused you to reopen a closed thread.  I was Googling the web to find an Ascom to Stellarium solution and this showed up in my search results.

I have heard of Indi but I can tell you that at the Charlotte Amateur Astronomers Club [http://charlotteastronomers.org/](url) of 200 + members almost everybody who does not have a turnkey scope or a pushto device uses Ascom.

Almost all the major manufacturers support the platform.  Regardless of whose system is the best I truly feel it is better to support common standards.  Ascom, like Stellarium is free and for different telescopes and other devices many independent developers provide enhancements and drivers.

I shall certainly look at Indi again now you have mentioned it but honestly Ascom seems the way most people have already gone.

I hope you can find a way forward.

As an aside, I have been a user of Stellarium since the mid 2000s and I have just bought Starry Night 8.  My decision to buy SN8 was based entirely upon the fact that it supported Ascom.

**Comment by gionkunz** [comment] 2019-08-06 09:04
@gzotti I understand it's sometimes difficult if your users use hardware that the developers don't have access to. However, in case of ASCOM this is not a valid excuse :-) ASCOM has the concept of simulators built into its core. Almost all devices (scopes, focuser, dome etc.) have a simulation counterpart. In the case of ASCOM Scope, this includes positions, sync and all other features that a real mount would present. I think, given the high demand of ASCOM support in Stellarium, this would be a huge benefit for your users. Stellarium Scope is a great Workaround, but it's a workaround let's face it. Also, it presents other issues and requires maintenance outside of the Stellarium release cycle.

I'm a developer myself, however, I've written my last C++ code back in the university and I think I'd introduce more anti-patterns and bugs than anything else if I'd try to contribute here. However, if I can help with anything, please tell me.

Best regards
Gion

**Comment by gzotti** [comment] 2019-08-06 10:45
@gionkunz  Having forgotten most of C++ is no excuse either -- this can be freshened up.  :-) 

Most development is driven by personal needs and interests of developers. The original developers of the telescope plugin unfortunately left the project. Two users have contributed INDI and RTS2, probably because the needed those connections themselves. My little telescope does not need ASCOM, so I have no personal ambition to spend several weekends of my spare time on this, to get a solution that does not more than the existing, and I am very sure users with advanced telescopes would then come with demands of focuser, CCD and filter wheel control (which I could not develop without the  experience about how such control program should look like!). You would "just" have to understand the plugin code and extend the code if built on Windows. If there is a library to link, there are other examples to see in the code (e.g. spout). Yes, indeed, I would welcome an ASCOM solution contributed by somebody. Unfortunately that somebody has not volunteered yet.

**Comment by gionkunz** [comment] 2019-08-06 12:27
Well, if you help me with testing the code and help me check that I don't
cross any boundaries, I'd love to check if I could contribute from myside.
Are there any guides how to start development / architecture docs or
anything similar?

Cheers
Gion

Georg Zotti <notifications@github.com> schrieb am Di., 6. Aug. 2019, 12:46:

**Comment by gzotti** [comment] 2019-08-06 12:56
Great! The wiki here includes startup guides (Compilation on Windows), and https://stellarium.org/doc/head/ is the Doxygen documentation. You cannot break the program, as development will be done in your private clone. When you have something to show, you make a "pull request" on github. All you need to edit is inside plugins/TelescopeControl, and maybe some cmake config files. If you come across other issues, please don't try to silently add them with this branch.

I cannot promise permanent and immediate availability for testing, though, it may take a few weeks sometimes. And I am afraid I cannot answer too detailed questions related to the code of that plugin, as it is not my code and I hardly use the plugin myself. I guess @alex-w will have more insight, although he mostly uses Linux, not sure if he would be willing/able to test... In any case all ASCOM-related code must be excluded from build on non-Windows systems.

**Comment by gionkunz** [comment] 2019-08-07 22:28
Okay, guys, I've started this journey 😄 

![image](https://user-images.githubusercontent.com/2203704/62662183-7497e500-b973-11e9-9c25-309177c120f5.png)

**Comment by YahaGr** [comment] 2019-08-27 00:25
Good luck! Thousands of Amateur astronomers are hoping for you!

**Comment by gionkunz** [comment] 2019-08-27 07:20
I'm having slow but steady progress ;-)

YahaGr <notifications@github.com> schrieb am Di., 27. Aug. 2019, 02:26:

**Comment by rederikus** [comment] 2019-10-07 23:34
I am amazed.  My request has been answered.  Thank you.  Now, where can I get my hands on this to test it.

Thank you guys.  You have just done the whole world of amateur astronomers a HUGE favour.

Wonderful

**Comment by rederikus** [comment] 2019-10-08 01:05
I'll help anyway I can.  I have ASCOM telescopes available and so do some of my fellow astronomers at our club.  I am pretty much a hardware guy and an old one at that.  With regards to writing code I am like a fish with a bicycle so to test I really would like a Windows executable if I am to help out which, I would really like to do.

Again thanks you very much for this.

**Comment by gzotti** [comment] 2019-10-08 11:52
I feel there is lots of demand, and many voluteers to test this.
 
Not sure if @gionkunz can provide installers. Maybe you can try building his repository from sources. This does not require you to write code, just follow the instructions in our wiki: Install Cmake, MS Visual C (free community edition), install Qt 5.13 (OpenSource version, free; don't forget to install the deprecated QtScript module!), git, clone Gion's repository, load in QtCreator, build, and execute. If you are generally OK with operating a Windows system, this should work within a few hours or maybe days. And whoever is able to help Gion with coding can try to fix what does not work on his/her particular equipment.

**Comment by gionkunz** [comment] 2019-10-09 09:32
Okay, I think I'm nearly done with implementing the feature. I have tested it already with two different Simulators and with my EQ6-R mount. However, more sophisticated testing is required for testing the ASCOM coordinate systems and Stellariums way of calculating atmospheric refraction when using JNow and the mount does not do it by itself. This Saturday, it looks like there's a Starry Night (pardon the pun), and I'll take my scope for a detailed pointing test including the new sync functionality (ctrl + shift + <scope#>).

I never built the installer, but I think I should learn how to do it, since I also have a few people who would be very much interested to test this feature. Please bear with me, since I only have limited time to work on this.

I'm very certain we will soon have ASCOM support in Stellarium, since I won't stop until this is accepted and agreed by all involved parties.

Cheers
Gion

**Comment by gzotti** [comment] 2019-10-09 09:54
Sounds good. I can hopefully test it next weekend with my NEQ3. Maybe @alex-w could quickly build  trial installers from your sources (or is the "Making the Installer" in the wiki Build instructions for Windows still up-to-date? Then just follow that.), so that Windows users can send you feedback. What about the win32/win64 issues, what is the recommended process now? Does a single 32bit ASCOM driver require you to use Stellarium 32bit, or do you handle all these cross-bittiness properly? (Not sure, are there still 32bit systems in wide use for telescope guiding systems?)

**Comment by gionkunz** [comment] 2019-10-09 20:10
Well, the 32bit / 64bit issue seems to be fine. At least with the EQ ASCOM simulator and the ASCOM.Telescope.Simulator I do not notice any issues with either the 32 or the 64 bit version of my build. However, this could potentially be an issue with other ASCOM drivers which were compiled for a specific architecture. My latest commits include better error tolerance and I guess the effect of such an issue would currently be that the telescope would always show as "connecting..." similar to all the other telescope types, when you enter invalid parameters.

**Comment by gionkunz** [comment] 2019-10-09 22:06
I have managed to build the installer. You can download the installer files for 32 and 64 bit here: https://drive.google.com/drive/folders/1hgTWKgmOgYq2OFNchOLdZxLgpZlKXPi7?usp=sharing

**Comment by alex-w** [comment] 2019-10-10 05:44
On Windows the plugin has issue in the GUI when ASCOM platform is not installed. I think the better choice here will be add the persistent GUI elements and manage enable/disable state for it on Windows.

**Comment by rederikus** [comment] 2019-10-11 00:08
Will this help?  I asked in the ASCOM forum [https://ascomtalk.groups.io/g/Help/topic/34480170?p=Created,,,20,1,0,0::recentpostdate/sticky,,,20,2,0,34480170](url)

**Comment by gionkunz** [comment] 2019-10-11 08:29
@rederikus I think instead of polluting to code even more with windows specific code, we keep it as we have it solved right now. We simply try to connect to the ASCOM.Util COM object and if that fails, we know that there's no ASCOM. Also this is great because it allows us to get the ASCOM version and also fail if it's significantly outdates (< version 6).

**Comment by gionkunz** [comment] 2019-10-11 08:30
But anyways, thanks so much for this clarification and valuable inputs!

**Comment by rederikus** [comment] 2019-10-11 12:49
I can do very little to help this project but I feel some responsibility for having pushed you guys in this direction.  I know it is not true but I kind of feel you are doing this for me.  I am many things but not a coder.  

I understand why you might not wish to put in Windows specific code to poke about in the registry.

**Comment by gionkunz** [comment] 2019-10-11 13:56
I can only speak for myself, but you did certainly not push me into any direction 😄 I wanted this feature since I have installed Stellarium and Stellarium Scope the first time, but never took the initiative to start development. I was re-using this ticket because that's what you should do on Github, instead of opening new tickets for the same topic. Also this issue was originally reported by someone else Mi.Holzner: https://bugs.launchpad.net/stellarium/+bug/1082196 . And I guess there are a bunch of other astronomy people who wish for this feature for a long time 😄 So really nothing you should feel responsible about in a negative way...

**Comment by rederikus** [comment] 2019-10-11 21:00
Oh it is not in any negative sense at all.  I was happy to find another thread. Mi.Holzner's that was also asking for ASCOM.

I am super happy to have helped to precipitate this sub-project.   No wish to push anybody in any direction that they did not already want to go.  This is great,

**Comment by rederikus** [comment] 2019-10-13 18:32
Without asking for even more work to be done, I number of people I know use IP (either via LAN cable or WiFi) to control their telescopes.  I found that I was limited to COMx ports using Stellarium's built-in scope control.

Will it be very hard to include IP address connectivity?  Just askin' , no mor'n that.  Thanks
Pete

**Comment by gzotti** [comment] 2019-10-13 19:14
This is why I asked whether StellariumScope is completely obsolete now. Maybe network connectivity is available by ASCOM? (I never had the need for it.)

**Comment by rederikus** [comment] 2019-10-14 01:42
I know that some ASCOM drivers do support IP connectivity as well as COMx connections.  This is because I have used them on telescopes.

From what I have searched for and read StellariumScope looks, at best, to be  no longer updated or maintained which is a shame.  More I do not know.

**Comment by rederikus** [comment] 2019-10-29 01:00
This amazing.  Whilst I have only tested Stellarium/ASCOM on my bench system it worked perfectly.  I shall try it out this weekend at the club observatory.  Even the TCP/IP connection works along with (obviously) the COM ports.

When do you think this will be released for all to use?  Will there soon be a 32 bit version? I have discovered that some ASCOM drivers are 32bit compatible only and will only run with a 32 bit compile.

**Comment by gionkunz** [comment] 2019-10-29 07:14
Hi

There is still some documentation work and a bit of testing due to some
issues we habe discovered which need clarification. I need to check when I
will find time but its a matter of weeks Id say.

Cheers
Gion

rederikus <notifications@github.com> schrieb am Di., 29. Okt. 2019, 02:00:

**Comment by rederikus** [comment] 2019-10-30 19:40
Great.  Thanks Gion.

This update is going to make a lot of people happy I think.  I am still amazed at how quickly this has been brought to alpha testing stage.  

What a great team.

**Comment by rederikus** [comment] 2019-11-08 19:48
Two night ago I took my 8" Dob on its home made goto mount to the observatory.  I id a 3 star align and turn control over to Stellarium + ASCOM via a HC-05 Bluetooth connection on the scope.  It worked flawlessly.  I used a 32mm eyepiece and every time I did a goto the object appeared in the eyepiece.  It was just the same a using the OnStep hand controller.  I am super impressed.

I know I have said this before but I genuinely believe that you have done the world of amateur astronomy a great favor by putting ASCOM into Stellarium.  Thank you all once more.
Pete

**Comment by gzotti** [comment] 2019-11-08 20:13
Some things take time. See https://sourceforge.net/p/stellarium/feature-requests/60/ for probably the oldest ASCOM request, for version 0.8.0, and Johannes' call for participation.

**Comment by gionkunz** [comment] 2019-11-08 20:29
If all astronomers have one thing in common, it's probably (to be forced to learn to be) patient... :-)

**Comment by gionkunz** [comment] 2019-11-08 20:31
@rederikus that's awesome! So far we have had very good response with the alpha version. I'm writing on the documentation as we speak.

**Comment by rederikus** [comment] 2019-11-08 22:04
@gionkunz I realize that I was not by, far the first to request this but it seems that my little ask came at just the right moment to kick the rock off the cliff and then, of course, there came the splash as the rock hit the water.  Many rocks fall but sometimes, just sometimes the time is right for the splash.  

As to patience, the cry is often, "Give me patience but, I want it now."  Either way, I am really happy that you all did what you did.  I await the official release eagerly.

Cheers
Pete

**Closed** 2019-12-04 02:54 UTC
Labels: in progress, wishlist
