### ISSUE TITLE
Save view settings in profiles and load it again later

### ISSUE THREAD

**Issue by markusd112** [Stellarium/stellarium#2601] opened 2022-08-23 15:30 UTC
I am using different view settings for different occasions. It would be very helpful to save the current view settings to profiles and be able to load them again, so you can easily switch to different view settings without having to toggle all settings manually each time.

Some idea how it could be implemented in the GUI:
- you can save the current view settings and name it
- you have a list with all saved settings and you can select them and activate them

**Comment by alex-w** [comment] 2022-08-23 15:44
Duplicate of #439

**Closed** 2022-08-23 15:52 UTC
Labels: duplicate
