### ISSUE TITLE
Double clicking a solar system object does not follow it

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#3272] opened 2023-06-16 07:44 UTC
I'm not really sure if this is a bug, but it seems this is not intended use.

Double clicking an object centers it. For stars and DSO's it works really well since they are fixed, but for SSO's it only centers the RA/Dec, and does not follow the object as if moves over time. Using space or clicking the center button in the toolbar works, however.

**Comment by gzotti** [comment] 2023-06-16 08:46
Not sure, but this may be intended. There are these two functions: center momentarily and then observe it moving, or center and freeze in center.

**Comment by Atque** [comment] 2023-06-16 10:18
Hm, all right, this may have some use. Should we keep this open anyway?

**Comment by gzotti** [comment] 2023-09-14 14:52
I think we can close this. Not a bug, it's a feature :-)

**Closed** 2023-09-14 14:53 UTC
Labels: opinion, not a bug
