### ISSUE TITLE
Zoom focus is misaligned after centering on object via double-click while vertical viewport offset is non-zero.

### ISSUE THREAD

**Issue by millen85** [Stellarium/stellarium#1523] opened 2021-02-23 03:02 UTC
### Expected Behaviour
Zooming in on centered object should keep object in center of screen while zooming.

### Actual Behaviour
After double-clicking on an object to center it, zooming on that object does not keep it centered.  This will only happen if the "vertical viewport offset" in the "sky and viewing options window" is changed to a non -zero number.  Curiously, if you instead choose to center the object with the space bar instead of mouse double-click then zoom, the object continues to stay centered even with VVO still nonzero. 

### Steps to reproduce
Adjust the "vertical viewport offset" (VVO) to some non-zero number, positive or negative.
Return to the main Stellarium window and double-click on an object in the sky to automatically center it.
Use the mouse wheel to zoom on the centered object.  Zoom will focus below the object if VVO is negative or above the object if VVO is positive.
NOTE: This does not happen when centering using the space bar on the keyboard. Only when centering using mouse double click.

### System
* Stellarium version:    stellarium-0.20.4-win64.exe
* Operating system:   Windows 10 Pro, Version 10.0.19042 Build 19042
* Graphics Card:    NVIDIA GeForce 8800 GT, Driver Version 21.21.13.4201
* Screen type:   LCD 1920x1080 x 60Hz  No scaling (100%)

**Comment by alex-w** [comment] 2021-02-23 06:12
See also #904

**Comment by gzotti** [comment] 2021-02-23 10:01
Really a duplicate of #904.

**Closed** 2021-02-23 10:02 UTC
Labels: bug, confirmed, duplicate
