### ISSUE TITLE
Stellarium 0.18.3 don't start in Ubuntu 18.04 Budgie

### ISSUE THREAD

**Issue by MatthiasRw** [Stellarium/stellarium#650] opened 2019-03-08 11:42 UTC
### Expected Behaviour
Stellarium starts

### Actual Behaviour
Stellarium starts, but hangs. You can see a small program window and in the terminal you can see error information (see below log.txt)
After aborting with Ctrl+C, "Memory access error" also appears. 

### Steps to reproduce
sudo apt remove stellarium
sudo add-apt-repository ppa:stellarium/stellarium-releases
sudo apt update
sudo apt install stellarium

### System
* Stellarium version: 0.18.3
* Operating system: Ubuntu 18.04 LTS Budgie, GNOME 3.28.2
* Graphics Card: GeForce GTX 1050/PCIe/SSE2

### Logfile 
[log.txt](https://github.com/Stellarium/stellarium/files/2945634/log.txt)

**Comment by gzotti** [comment] 2019-03-08 11:55
You are running the Intel graphics driver but you would also have a Geforce card. Is that intended?

**Comment by alex-w** [comment] 2019-03-10 06:21
Could you check our nightly builds?

**Comment by gzotti** [comment] 2019-09-28 18:10
We must assume the OP's system was not set up properly. Without follow-up for six months and any way of reproducing what appears to be a "particular system setup issue", we can close it.

**Closed by gzotti** 2019-09-28 18:10 UTC
Labels: incomplete
