### ISSUE TITLE
"Information Display" for objects defaults to "All" at startup.

### ISSUE THREAD

**Issue by JWPOITH** [Stellarium/stellarium#4002] opened 2024-12-10 01:14 UTC
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by JWPOITH** [comment] 2024-12-10 01:32
I recently deleted my older version of Stellarium and installed version 24.3 on my Windows 11 laptop.    Although I have chosen the "Info" details I wish to display and have saved them, the option to show customized information must be selected every time I open the program.   At program startup, the system defaults to showing "All" information and it is necessary to purposefully re-choose "customized" information.   Once I re-select "customized", the information choices I previously made are in effect for the duration of the session (only).   So, it remembers my choices but does not remember that I prefer to use "customized" instead of "all" information.    This is not how the program used to work.   Logfile attached.
Thank you!

[log.txt](https://github.com/user-attachments/files/18070185/log.txt)

**Comment by alex-w** [comment] 2024-12-10 05:02
Duplicate of #3961

**Closed by alex-w** 2024-12-10 05:02 UTC
