### ISSUE TITLE
Extreme lag on high end MacBook

### ISSUE THREAD

**Issue by radu-florin-marinescu** [Stellarium/stellarium#3370] opened 2023-08-16 10:08 UTC
### Expected Behaviour

Last time I used this software, an year ago it was working with smooth 60fps no matter how many labels or hints were shown.

### Actual Behaviour

The software has extreme lag, it is literally unusable. This is when launching it fresh, If I show labels or hints for galaxies, the software completely freezes in lag. This also reproduces on MacBook Air as well as Asus laptop with Windows 11, which makes me believe it's not a driver issue. 

### System
* Stellarium version: 23.2
* Operating system: MacOS 12.5.1 / MacBook Pro M1 Pro

**Comment by 10110111** [comment] 2023-08-16 10:10
May be a duplicate of #2947 or #2778.

**Comment by radu-florin-marinescu** [comment] 2023-08-16 10:17
> May be a duplicate of #2947 or #2778.

**Closed** 2023-08-16 10:19 UTC
