### ISSUE TITLE
Adding new telescope

### ISSUE THREAD

**Issue by kingstonheath** [Stellarium/stellarium#2718] opened 2022-10-04 09:35 UTC
Running version 1.22.3, I am unable to add new telescopes to the telescope control plugin. No problems with telescopes that were added under the previous version (they are visible and seem to work).  I am able to enter telescope details but hitting save does nothing.  Have selected "load on startup" and then restarted Stellarium.  I have tried on windows 10 and windows 11 with the same result.  I have tried adding Ascom scopes with the HEQ5/6 drivers (EQMOD) and the Ascom simulator.  Neither would save.  Re-installed previous version and no issues adding new scopes.  

Thanks
Steve

**Comment by alex-w** [comment] 2022-10-04 09:37
Duplicate of #2713

**Closed** 2022-10-04 09:37 UTC
Labels: duplicate
