### ISSUE TITLE
Segmentation fault v23.3.356-b1f4eb5 [master] (Raspberry Pi)

### ISSUE THREAD

**Issue by Pavel-II** [Stellarium/stellarium#3569] opened 2023-12-22 21:16 UTC
### Expected Behaviour
run app

### Actual Behaviour
app crushed with Thread 1 "stellarium" received signal SIGSEGV, Segmentation fault.

### Steps to reproduce
Build v23.3.356-b1f4eb5
`$ git pull
Already up to date.

 uname -ra
Linux rpi2 6.2.0-1016-raspi #18-Ubuntu SMP PREEMPT Thu Oct 12 13:26:36 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

$ qmake -v
QMake version 3.1
Using Qt version 5.15.10 in /usr/lib/aarch64-linux-gnu
`

### System
* Stellarium version: v23.3.356-b1f4eb5 [master]
* Operating system: Ubuntu 23.10 (Mantic Minotaur)
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling
* # System Details Report
---

## Report details
- **Date generated:**                              2023-12-23 00:14:16

## Hardware Information:
- **Memory:**                                      7.6 GiB
- **Graphics:**                                    V3D 4.2

## Software Information:
- **OS Name:**                                     Ubuntu 23.10
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.1
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.2.0-1016-raspi

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[stelllog.txt](https://github.com/Stellarium/stellarium/files/13756741/stelllog.txt)

**Comment by Pavel-II** [comment] 2023-12-22 21:19
gdb ./src/stellarium

`
...
Downloading separate debug info for /usr/lib/aarch64-linux-gnu/qt6/plugins/wayland-decoration-client/libbradient.so
QPainter::begin: Paint device returned engine == 0, type: 1                                                                                                                             
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::worldTransform: Painter not active
QPainter::save: Painter not active
QPainter::restore: Unbalanced save/restore
QPainter::setWorldTransform: Painter not active
QPainter::end: Painter not active, aborted

Thread 1 "stellarium" received signal SIGSEGV, Segmentation fault.
QBackingStoreDefaultCompositor::flush (this=0xaaaaac7ce078, backingStore=0xaaaaac8e0100, rhi=0x0, swapchain=0x0, window=0xaaaaac8863b0, sourceDevicePixelRatio=1, region=..., 
    offset=..., textures=0xaaaaac9504e0, translucentBackground=false)
    at /usr/src/qt6-base-6.4.2+dfsg-18/obj-aarch64-linux-gnu/include/QtGui/6.4.2/QtGui/private/../../../../../../src/gui/rhi/qrhi_p.h:1399
Downloading source file /usr/src/qt6-base-6.4.2+dfsg-18/obj-aarch64-linux-gnu/include/QtGui/6.4.2/QtGui/private/../../../../../../src/gui/rhi/qrhi_p.h
1399        QSize currentPixelSize() const { return m_currentPixelSize; }     `

**Comment by gzotti** [comment] 2023-12-22 21:30
Is this an RPi 4 or 5? My RPi4 works on Ubuntu Mate 22.04LTS. However, it should run OpenGL ES 2.0, not desktop OpenGL.

**Comment by 10110111** [comment] 2023-12-22 21:34
May be a duplicate of #3429.

**Comment by Pavel-II** [comment] 2023-12-23 14:57
> RPi 4 or 5?

Raspberry Pi 4 Model B Rev 1.4

**Comment by alex-w** [comment] 2023-12-23 15:43
@Pavel-II could you share a log of configuration?

**Comment by Pavel-II** [comment] 2023-12-23 16:02
@alex-w yep, what files of?

**Comment by alex-w** [comment] 2023-12-23 16:09
> @alex-w yep, what files of?

cmake's output text  - he shouldn't been configures the Stellarium to use OpenGL on RPi

**Comment by Pavel-II** [comment] 2023-12-23 16:18
@alex-w 
[cmakeout.txt](https://github.com/Stellarium/stellarium/files/13759605/cmakeout.txt)

**Comment by alex-w** [comment] 2023-12-23 16:25
I see in the log `-- Building an OpenGL build`, but this is wrong.

Please try run cmake with option `-DENABLE_QT6=Off`

**Comment by Pavel-II** [comment] 2023-12-23 16:32
> I see in the log `-- Building an OpenGL build`, but this is wrong.
> 
> Please try run cmake with option `-DENABLE_QT6=Off`

[failed_stelllog_with_DENABLE_QT6Off.txt](https://github.com/Stellarium/stellarium/files/13759643/failed_stelllog_with_DENABLE_QT6Off.txt)

**Comment by alex-w** [comment] 2023-12-23 16:35
A missing packages - please run `sudo apt install qtbase5-private-dev`

**Comment by Pavel-II** [comment] 2023-12-23 16:42
> A missing package - please run `sudo apt install qtbase5-private-dev`
[cmakeout-DENABLE_QT6Off.txt](https://github.com/Stellarium/stellarium/files/13759664/cmakeout-DENABLE_QT6Off.txt)

Done. make in process

**Comment by Pavel-II** [comment] 2023-12-23 17:29
> > A missing package - please run `sudo apt install qtbase5-private-dev`
> > [cmakeout-DENABLE_QT6Off.txt](https://github.com/Stellarium/stellarium/files/13759664/cmakeout-DENABLE_QT6Off.txt)
> 
> Done. make in process

@alex-w 

builded, but not running successful
[build_and_runlog.txt](https://github.com/Stellarium/stellarium/files/13759765/build_and_runlog.txt)

**Comment by alex-w** [comment] 2023-12-23 17:33
Probably missing packages for Qt5/Wayland - please check list of packages from BUILDING.md

**Comment by alex-w** [comment] 2023-12-23 17:36
Well, partially it’s our problem for Qt6/arm64 environment - see https://github.com/Stellarium/stellarium/blob/21710195e1bc3fb425b5a588a76b03e8eb857104/CMakeLists.txt#L669

**Comment by alex-w** [comment] 2023-12-24 04:56
> May be a duplicate of #3429.

I fear we see combination of 2 separate issues :(

**Comment by alex-w** [comment] 2024-01-01 12:56
Please try run `QT_QPA_PLATFORM=xcb ./stellarium`

**Comment by alex-w** [comment] 2024-01-02 08:06
First, I can confirm crash in Wayland-session on RPi4.

Some details:
1. We have missing packages in BUILDING.md file for Wayland sessions, but this will not help us, because in Wayland session Qt cannot give us correct OpenGL context (at least in Raspberry OS on arm64 devices - but similar problem seen in Fedora/Wayland)
2. We can get some improvements after defining environment variable `QT_QPA_PLATFORM=xcb` - a switching to use xcb QPA
3. In Wayland session Qt5-based package has visible sky, but not GUI; Qt6-based package has a black screen
4. In Wayland session in `--opengl-compat` mode the Qt5-based package is fully working now; Qt6-based package has a black screen again
5. In X11 session in `--opengl-compat` mode the both packages are fully working now

@10110111 @gzotti any ideas?

**Comment by 10110111** [comment] 2024-01-02 08:17
6. What about X11 session without `--opengl-compat`?

Wayland still being rather new (despite being in development for over a decade and being packaged for about 7 years), I think there are some problems to be expected, particularly on Qt side.

**Comment by alex-w** [comment] 2024-01-02 08:26
> 6. What about X11 session without `--opengl-compat`?

Qt5: visible sky, no GUI
Qt6: a black screen

**Comment by 10110111** [comment] 2024-01-02 08:53
What driver is used on RPi?

**Comment by alex-w** [comment] 2024-01-02 09:09
> What driver is used on RPi?

VC4

P.S. Please sent me your ssh-key - I can share access to RPi

**Comment by gzotti** [comment] 2024-01-02 09:25
Raspberries originally came with OpenGL ES and worked with Qt5. I did not try Qt6 so far but expect issues. What are the Mesa switches / envvars to force OpenGL ES2.0, not a possibly flaky OpenGL 2.1+?

**Comment by alex-w** [comment] 2024-01-02 10:08
> Wayland still being rather new (despite being in development for over a decade and being packaged for about 7 years), I think there are some problems to be expected, particularly on Qt side.

See https://docs.mesa3d.org/envvars.html

`MESA_GLES_VERSION_OVERRIDE=2.1`

**Comment by alex-w** [comment] 2024-01-02 10:10
> Raspberries originally came with OpenGL ES and worked with Qt5. I did not try Qt6 so far but expect issues. What are the Mesa switches / envvars to force OpenGL ES2.0, not a possibly flaky OpenGL 2.1+?

See https://docs.mesa3d.org/envvars.html

`MESA_GLES_VERSION_OVERRIDE=2.0`

**Comment by gzotti** [comment] 2024-01-02 10:43
Ah right, I did try it last year according to https://github.com/Stellarium/stellarium/wiki/Raspberry-Pi. Any hints about such extra settings should be collected there. (And maybe we can after all remove outdated info from before 2020 or so. It used to be much harder in earlier years, but the driver did not report full OpenGL compatibility...)

**Comment by alex-w** [comment] 2024-01-03 07:04
Wiki/Raspberry-Pi has been updated

**Comment by gzotti** [comment] 2024-03-11 15:25
@Pavel-II does it work with the instructions from January 2nd?

**Comment by gzotti** [comment] 2024-04-01 11:23
Let's see if we can make it work on Ubuntu 24.4.

**Comment by gzotti** [comment] 2024-05-11 22:08
Trying again with my RPi4. Ubuntu 24.1 provides a snap package of Stellarium 24.1 authored by Tanmoy Saha. However, the GUI does not show up, no buttons, no InfoText. I don't know where the snap version stores log and config files. 
I am ignorant of everything wayland/X11, snap etc and depend on your instructions. I can add our own ppa to install 24.1 or weekly, if that helps.

**Comment by gzotti** [comment] 2024-05-12 15:41
> Please try run `QT_QPA_PLATFORM=xcb ./stellarium --opengl-compat`

This works on RPi4/Ubuntu 24.1 with Stellarium installed from our ppa:stellarium/daily. Before running Stellarium, install raspi-config and activate wayland. 

This now has OpenGL3.1 and runs at 13fps on a smallish (1280x1024) screen.

**Comment by gzotti** [comment] 2024-06-05 20:22
Without @Pavel-II 's input, we can close this as most likely solved on June 20th.

**Comment by gzotti** [comment] 2024-06-20 09:04
Solved by updating Ubuntu.

**Comment by gzotti** [comment] 2024-06-20 09:10
Solved by updating Ubuntu.

**Closed by gzotti** 2024-06-20 09:10 UTC
Labels: bug, state: confirmed, qt
