### ISSUE TITLE
stellarium-1.1.1-qt6-win64.exe show only blank / black screen

### ISSUE THREAD

**Issue by tflyer-rgb** [Stellarium/stellarium#2803] opened 2022-11-01 12:17 UTC
Expected behavior

Show normal sky view after starting the program and not only a blank / black screen

Actual behavior

The application show only a blank / black screen after startup.

Steps to reproduce

Upgrade from version  stellarium-1.22.3-win64.exe  to stellarium-1.1.1-qt6-win64.exe

I try to start the application in normal, MESA and ANGLE mode always with the same result. The same result was with version 1.1, 1.0 works fine.

Stellarium version: stellarium-1.1.1-qt6-win64.exe
Operating system: Windows 10 21H2 (Build 19044.2130)
Graphics card: AMD Radeon HD 6700M
Screen type: Notebook LCD resolution 1366 x 768 
[log.txt](https://github.com/Stellarium/stellarium/files/9909663/log.txt)

**Comment by 10110111** [comment] 2022-11-01 12:38
Does pressing <kbd>F11</kbd> twice make it work?

**Comment by tflyer-rgb** [comment] 2022-11-01 12:58
Pressing F11 twice works, with and without startup option --opengl-compat

**Comment by gzotti** [comment] 2022-11-02 01:25
It seems the Radeon HD is blacklisted from OpenGL use by Qt6, and falls back to Mesa. Use a Qt5-based build (version 0.22.4) for better performance.

**Comment by 10110111** [comment] 2022-11-02 01:50
> It seems the Radeon HD is blacklisted from OpenGL use by Qt6

This would be strange: it isn't present in [the blacklist](https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/windows/openglblacklists/default.json).

**Comment by gzotti** [comment] 2022-11-02 01:57
There must be a reason why the logfile says Mesa/OpenGL3.0. And I agree, we should build a more recent Mesa now that could offer 3.3CoreProfile.

**Comment by zeklh** [comment] 2022-11-02 18:52
I have the same problem. F11 works. But there is another problem. When I zoom into the moon, planets or deep sky objects which are extended like galaxies they disappear at a certain zoom level. There is only the background to be seen. This is  independent whether I activate atmosphere or not.

**Comment by 10110111** [comment] 2022-11-02 20:17
> When I zoom into the moon, planets or deep sky objects which are extended like galaxies they disappear at a certain zoom level.

This is a separate problem, to be treated in another issue.

**Comment by zeklh** [comment] 2022-11-03 10:05
Created a new issue

**Comment by alex-w** [comment] 2022-11-20 08:54
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by zeklh** [comment] 2022-11-22 13:00
Press F11 twice. It's a bug.Hans--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 20.11.22, 09:54 schrieb "Alexander V. Wolf" ***@***.***>:

   
  Please check the fresh version (development snapshot) of Stellarium: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by alex-w** [comment] 2022-11-24 14:06
According [this](https://astronomy.ru/forum/index.php/topic,21983.msg5710893.html#msg5710893) report the issue is fixed now

**Comment by alex-w** [comment] 2022-11-24 14:07
> Press F11 twice. It's a bug.

Please more details

**Comment by zeklh** [comment] 2022-11-24 19:09
On Windows this version starts with black screen. When I press F11 - full screen mode on and off - it works. There is a bug report you may find in the Stellarium forum.--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 24.11.22, 15:07 schrieb "Alexander V. Wolf" ***@***.***>:

   
   
   Press F11 twice. It's a bug. 
   
  Please more details

**Comment by zeklh** [comment] 2022-11-24 19:11
Oh, I did not see your previous mail. Then I was referring to the previous version.Sorry.--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 24.11.22, 15:07 schrieb "Alexander V. Wolf" ***@***.***>:

   
   
   Press F11 twice. It's a bug. 
   
  Please more details

**Comment by alex-w** [comment] 2022-12-14 08:29
@zeklh 

Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by gzotti** [comment] 2022-12-20 21:14
Update on modernizing Mesa:
- Download from https://github.com/pal1000/mesa-dist-win/releases
- copy x64/{libglapi.dll,libgallium_wgl.dll,opengl32.dll} to where the executable stellarium.exe is.
- set environment variables: QT_OPENGL_DLL=opengl32.dll, QT_OPENGL=software, GALLIUM_DRIVER=llvmpipe
- run Stellarium with Mesa 22: OpenGL3.3 core.

**Comment by alex-w** [comment] 2023-03-13 15:28
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by gzotti** [comment] 2023-03-19 19:30
Shall I write these instructions into the wiki, and we close this? Or does sb want to build Mesa with the usual filenames to avoid setting environment variables? (These could be set on the fly when --mesa-mode is called)

**Comment by 10110111** [comment] 2023-03-19 19:50
Why not simply include whatever is needed into the distribution? These instructions are just a kludge that the users shouldn't need.

**Comment by gzotti** [comment] 2023-03-19 20:07
Agreed. There are still 2 options. These existing files as outlined (instead of Qt's outdated opengl32sw.dll), with changes in the --mesa-mode call to set envvars, or build new Mesa libs from sources with the names like opengl32sw.dll. The first is easier IMO and could go into 23.1. We may need to add whatever license/acknowledgment is required to include modern Mesa.  @alex-w ?

**Comment by alex-w** [comment] 2023-03-20 02:01
Probably including modern Mesa into installation package will be best solution

**Comment by gzotti** [comment] 2023-03-20 20:19
Argh, and just now this method above does not work any longer... (tried Mesa 22.3.1 and 23.0.0)

**Comment by gzotti** [comment] 2023-09-12 17:35
Tested with 23.1.17, and it works. Mesa23 delivers OpenGL 4.5 CoreProfile. We can set the envvars in the CLI wrapper. But the 3 relevant DLLs should be placed into the repo somewhere, and the installer creator should pack then those instead of the outdated Mesa which Qt provides.

@alex-w where to put the DLLs?

**Comment by alex-w** [comment] 2023-09-12 17:38
@gzotti please see rules in appveyor.yml file

**Comment by gzotti** [comment] 2023-09-12 19:26
I am afraid I have no idea what to do :-( Please get involved in #3409.

**Closed** 2023-10-14 17:08 UTC
Labels: bug
