### ISSUE TITLE
landscape horizon at high elevations should drop

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1117] opened 2020-06-09 09:04 UTC
### Expected Behaviour
When elevation is risen , stars that are just below the horizon should start to appear.

### Actual Behaviour
no change at all, other than the atmosphere that changes and becomes black/transparant (which is expected).

### Steps to reproduce

1. **select a landscape**
1. stop the time ('K')
1. select a star that is very close to the horizon
1. keep an eye on the altitude of the star
1. open the location dialog (F6)
1. change the elevation (use Page Up to accelerate things, or type in values, note that the limit is 200km)

**Bug: observe that the altitude of the star does not change when the elevation increases.**

This might be the reason why the elevation is limited to 200km.

In fact, if you zoom out sufficiently so that you see the entire ground landscape, you should see what an astronaut can see (unless you are a flat earth believer, of course...).

Note that without landscape this is not an issue, because the "horizon" is set at infinity, in which case objects will not be influenced by relatively small elevation changes (small in terms of the solar system scales).

### System
* Stellarium version: 0.20.1
* Operating system: KUbuntu 18.04
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

(external link: )

**Comment by gzotti** [comment] 2020-06-09 10:18
Duplicate of #740 
The landscape consists of an image taken on and fitting to the location. If you go into the air, the landscape would have to change depending on distances to 3D surface features. You can create a 3D landscape. However, earth curvature is currently not handled. Also, refraction is not handled well below the mathematical horizon.

**Closed** 2020-06-15 13:01 UTC
Labels: duplicate, won't fix

**Comment by axd1967** [comment] 2020-12-14 14:02
the earth curvature issue is mentioned in https://github.com/Stellarium/stellarium/wiki/Research
