### ISSUE TITLE
"Real" view in Stellarium

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#462] opened 2018-09-26 06:53 UTC
_Original report by Tim Robins:_ https://bugs.launchpad.net/stellarium/+bug/1080960

I love Stellarium even though I have several other such programs. Today I do not have astrophotography facilities, and am somewhat frustrated by the beautiful views of nebulae, etc., provided in ocular view. Is there some way now or might it be possible to add as a feature a more realistic view capability in Stellarium?

It would be great if I could visit ocular view and see a realistic depiction of what to expect through my eyepiece, i.e., little or no color, just the "gray smudge" that is more likely. If there is a way to switch Stellarium to such a basically B&W view I have not found it. Perhaps it could be added in a future release?

Thanks for your consideration.

**Comment by gzotti** [comment] 2018-09-26 08:18
Duplicate of #349

**Closed by gzotti** 2018-09-26 08:18 UTC
Labels: duplicate, wishlist
