### ISSUE TITLE
History of Viewed Objects in a Session

### ISSUE THREAD

**Issue by Shavarshk** [Stellarium/stellarium#1190] opened 2020-08-02 11:28 UTC
When using Stellarium, I frequently encountered a situation when I wanted to return to the previous object(s) and could not do it. For example, when selecting a sequence of stars or other objects, I wanted to return to the previously selected object or several ones, I had to select them manually or write the object name in the search box over and over again. 

My suggestion is to add up a feature similar to the one in Ms. Word like "Undo" or "Redo". There should be a history of visited objects that one can choose to go back to it or move forward to it. Let me know, please, if I  explained my point. 

Best regards,

**Comment by gzotti** [comment] 2020-08-02 11:43
Duplicate of #1160 which is solved by using our bookmark feature or #1168.

**Comment by Shavarshk** [comment] 2020-08-02 11:47
Understood. Thank you.

**Closed** 2020-08-02 11:46 UTC
Labels: duplicate, feature request
