### ISSUE TITLE
Markings in the sky for apogee and perigee

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1758] opened 2021-06-22 05:48 UTC
I'm really not sure if this is easy or if there are models, as I have not seen this in any other planetarium softare.

But it would be nice if we could have a point in the sky which represents the apogee and perigee points, so we easily see when the Moon is at its closest and farthest. The points would need to follow the lunar orbit. It may be of interest to those who are searching for supermoons.

**Comment by alex-w** [comment] 2021-06-22 05:54
Duplicate of #850

**Closed** 2021-06-22 05:54 UTC
Labels: duplicate

**Comment by gzotti** [comment] 2021-06-22 06:21
Brrr, "supermoon" is a term coined by some publicity-hungry astrologer. And no other than NASA picked it up in some dead season, and the media of course perpetuate the nonsense with photoshopped giant moonrises (sometimes with Apollo photos with the Moon viewed from space). What counts more? Serious work or being in the media?

**Comment by Atque** [comment] 2021-06-22 06:29
@gzotti I know, but keep in mind that most users are not serious astronomers or researchers. If the media uses the term, it might be of interest to users too, and it might help them understand that a supermoon does not show a detectable difference to the naked eye.

**Comment by axd1967** [comment] 2021-06-22 10:49
I was also thinking of this.

Plus the positions of the nodes - this is an important concept in explaining eclipses.

And even a point that most will reject: the antilunar point. It helps quickly ascertaining where the Moon is when it is not in sight.

**Comment by axd1967** [comment] 2021-06-22 10:55
In relation to the Moon illumination, and to add to the supermoon discussion: the distance Sun-Moon (which is greatly influenced by Earth peri/aphelion) also impacts moonlight. This could be visualised with a perihelion/aphelion mark on the ecliptic.
