### ISSUE TITLE
January 31st Total Lunar Eclipse. Crash bug.

### ISSUE THREAD

**Issue by kyzercube** [Stellarium/stellarium#66] opened 2018-01-03 00:59 UTC
Stellarium 0170 crashes for me every time I go to the morning of January 31st and look at the Moon while eclipsed. The instant the Moon is observed, the program crashes 100% of the time.

**Comment by gzotti** [comment] 2018-01-03 17:47
This is a duplicate of #63.

**Closed by gzotti** 2018-01-03 17:47 UTC
