### ISSUE TITLE
Ver 1.2 crashes when resizing screen (Qt6 + TelescopeControl)

### ISSUE THREAD

**Issue by AstroMikeJoy** [Stellarium/stellarium#2940] opened 2022-12-27 00:08 UTC
Program opens and works to drive telescope using eqmod and ascom etc   however screen starts minimised and upon resizing using mouse wheel or page up/down program crashes and closes completely losing any position and settings. Issue has only arisen ver 1 and after

**Comment by gzotti** [comment] 2022-12-27 00:45
Possible duplicate of #2821.
Does the Qt5-based build work for you?

**Comment by AstroMikeJoy** [comment] 2022-12-27 07:56
I used ver 0.2 for years no problem it’s this version 1 and 1.2 that crash. How do I know which is QT5  I’ve looked at my QuickTime and that’s 7 ?Mike ﻿
Possible duplicate of #2821.
Does the Qt5-based build work for you?

**Comment by gzotti** [comment] 2022-12-27 09:29
Go to https://github.com/Stellarium/stellarium/releases and download a package that includes "qt5" in its name. This is based on Qt5 then. And Qt (Qt) is not QT (QuickTime). Read the foreword of the User Guide for more info.

**Comment by AstroMikeJoy** [comment] 2022-12-28 15:19
> 

I have now downloaded the qt5 version and it seems to be okay and does now zoom in and out with pgup and pgdn without crashing completely. This is indoors though and not connected to telescope as of yet. will do that as soon as i can 
as for the qt  I have a fairly new x64 laptop so not sure why qt6 causes issues and 5 does not

**Comment by gzotti** [comment] 2023-09-13 09:27
Several Qt6/TelescopeControl issues have been solved before 23.3. We tentatively close this as member of a large group of related issue reports for now. In case of re-occurrence of this issue in V23.3, please create a new report with very clear description of circumstances.

**Closed by gzotti** 2023-09-13 09:27 UTC
Labels: help wanted, good first issue
