### ISSUE TITLE
Saturn rings issues

### ISSUE THREAD

**Issue by tranceptor** [Stellarium/stellarium#133] opened 2018-04-10 08:21 UTC
Hi,
I continue having this problem on Saturn rings, but I need to understand if it's an issue or not.
If I press F6 and select Saturn, and edit the following long. and lat. (N 0° 23' 1.71" and E 5° 37' 29") I see a (probable) rendering issue of Saturn rings (see attached image).
The same problem occours if I write a script that move from the Saturn Pole to the Equator.
Could you please give me a feedback? Is there something wrong with my installation or video drivers?

*** Stellarium version with the issue: (at least) v. 0.17.0 and 0.18.0 32-bit on Windows 10 and 7.

![image](https://user-images.githubusercontent.com/5619303/38544842-d59853c4-3ca8-11e8-9cf4-3ac9af5f3cb7.png)

**Comment by gzotti** [comment] 2018-04-10 09:33
Are you running ANGLE mode? There appears currently to be a problem with some versions, but I cannot reproduce your really strange view. Try getting OpenGL to work by installing appropriate drivers, or run in MESA mode to see if that helps.

**Comment by tranceptor** [comment] 2018-04-10 10:27
No, I'm using the regular version. In MESA mode I get flashes all over the disk viewport instead of rings!

To reproduce the issue, try to set Saturn, then 0° 0' 0" as longitude, then change click by click the minutes part until you reach ~ 23' - 25' minutes.


![image](https://user-images.githubusercontent.com/5619303/38551574-d1775d9c-3cb9-11e8-94a7-a5a7936f2cc5.png)

![image](https://user-images.githubusercontent.com/5619303/38551813-7651f52a-3cba-11e8-8142-3b6878e01b3a.png)

**Comment by gzotti** [comment] 2018-04-10 10:46
I did that of course but could not reproduce your views. 
As we keep repeating on each and every channel, the logfile (log.txt in your Stellarium User dir) is the usual first source of problem discovery. 
Given that MESA works on the CPU to emulate a valid GPU, this seems very odd. Mesa should always produce a good result at cost of low framerate and high CPU load. Please show logfiles from a regular OpenGL run and from a MESA run.

**Comment by tranceptor** [comment] 2018-04-10 10:53
Ok, this is the log file obtained by running Stellarium in MESA mode on my Windows 10 o.s.. 

[log.txt](https://github.com/Stellarium/stellarium/files/1894260/log.txt)

**Comment by tranceptor** [comment] 2018-04-10 10:59
This is the log running the OpenGL  diagnostics mode (and this is the screenshot of what I see).


![image](https://user-images.githubusercontent.com/5619303/38553077-6c843d24-3cbe-11e8-858e-3c282d592d79.png)
[log.txt](https://github.com/Stellarium/stellarium/files/1894276/log.txt)

**Comment by gzotti** [comment] 2018-04-10 11:18
Both were run with the native OpenGL graphics from an Intel UHD620. This should not be bad from its specs, but maybe you need to update drivers from Intel (directly, not via Windows Update!)

**Comment by gzotti** [comment] 2018-05-14 21:03
@tranceptor we will close this by around May 20 without further input. I cannot reproduce it, we have no useful logfile from Mesa and ANGLE, but I guess this is a driver issue. Try ANGLE.

**Comment by gzotti** [comment] 2018-09-27 16:32
@tranceptor is this still open in 0.18.2 and after your driver update? If yes, 

- Which projection are you using?
- you mention "disk viewport". Are you running some planetarium mode? 

I cannot reproduce a setting that comes close to your first image, full view of the planet. I find some odd display with "Fisheye" projection, nothing near your green triangles though.

**Comment by gzotti** [comment] 2019-12-21 15:51
Clearly beyond timeout.

**Closed by gzotti** 2019-12-21 15:51 UTC
Labels: incomplete
