### ISSUE TITLE
Stellarium crashing repateadly

### ISSUE THREAD

**Issue by Eric060606** [Stellarium/stellarium#3459] opened 2023-10-11 13:12 UTC
Hi,

Please find attached below the description of the issue I have with Stellarium.

### Expected Behaviour
Stellarium not to freeze and then switch off each time I go back to the Stellarium sofwtare page after using another software

### Actual Behaviour
I am using Stellarium 23.3 on my laptop, and running the Sharpcap image capture programme in parrallel. Each time I go on the Shaprcap software page and then return to the Stellarium page, then Stellarium just freezes and then crashes. 
I have noticed that if I reduce the Sharpcap page using the Windows command at the top right of the screen, and then click on the Stellarium page, then the number of crashes becomes much lower.

### System
* Stellarium version: 23.3 (issue was the same with 23.2)
* Operating system: Windows 10
* Graphics Card: Intel (R) HD Graphic 620, pilot 30.0.101.1338
* Screen type (if applicable):1920x1080, 6bit, 60Hz

### Logfile => this is a log I got a few days ago while still using v23.2, issue was already present:

Log detail at start-up of Stellarium:
2023-09-27T18:44:00

Operating System: Windows 10 Version 22H2

Compiled using MSVC++ 16.10, 16.11 (Visual Studio 2019)

Qt runtime version: 6.4.3

Qt compilation version: 6.4.3

Addressing mode: 64-bit

Total physical memory: 16268 MB

Available physical memory: 8940 MB

Physical memory in use: 45%

Processor speed: 2712 MHz

Processor name: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz

Processor speed: 2712 MHz

Processor name: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz

Processor speed: 2712 MHz

Processor name: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz

Processor speed: 2712 MHz

Processor name: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz

C:\Program Files\Stellarium\stellarium.exe -platform windows:altgr

-------------------------------------------------------------

[ This is Stellarium 23.2 (v23.2.0) - https://stellarium.org/ ]

[ Copyright (C) 2000-2023 Stellarium Developers ]

**Comment by gzotti** [comment] 2023-10-11 17:25
Duplicate of #2821.

**Closed by gzotti** 2023-10-11 17:25 UTC
Labels: duplicate

**Comment by Eric060606** [comment] 2023-10-11 20:45
Yes, I see now that the issue exists. It seems to be a well known and impacting a bunch of users. However I am wondering if the solution exists, I haven't seen any explaination of the issue and any suggestion to solve it in the referred #2821. Or am I missing something?
Many thanks.

**Comment by 10110111** [comment] 2023-10-11 21:05
Apparently, the qt5 version of Stellarium works.

**Comment by Eric060606** [comment] 2023-10-13 08:55
Thanks for the suggestion. I have tried the qt5 yesterday evening. Same issue plus others ones linked to the size of the pop-up windows that pervent me from the possibility to click on some choices.
I am giving up on Stellarium, I have tried, lost many hours, too unstable.
Going back to Carte du Ciel, less fancy interface and graphics but does the job.
