### ISSUE TITLE
Cannot Delete Old Satellite Entry from Object List

### ISSUE THREAD

**Issue by dlwmacgregor** [Stellarium/stellarium#2507] opened 2022-07-07 13:54 UTC
### Actual Behaviour
Unable to delete a satellite from the Object list that has changed its name .
ISS
Name has changed  from ISS (Zarya).
Clicking on ISS (Zarya) does not do anything. It has always worked.
Added ISS and it works.
I can't delete the old name.

### System
* Stellarium version: <stellarium-0.22.1-win64.exe>
* Operating system: <Windows 10 21H2 19044.1766>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data direc
![Screenshot (3446)](https://user-images.githubusercontent.com/67886290/177790693-d116e731-11a6-4721-8fb7-38b6b916dfb5.png)
tory. Look into the Guide for its location.

**Comment by JAY-Githb** [comment] 2022-07-08 05:00
Instead of searching by name, search by catalog #   25544 .
Then click  '  -  '   at bottom of window.

Only way to change a name in the data base is to edit SATELLITES.JSON.
A name comes from your input file. Check the name there before updating your elements.

Jay Respler

**Comment by alex-w** [comment] 2022-07-08 09:21
> Instead of searching by name, search by catalog # 25544 . Then click ' - ' at bottom of window.
> 
> Only way to change a name in the data base is to edit SATELLITES.JSON. A name comes from your input file. Check the name there before updating your elements.

This is related to Search Tool, not to Satellites plugin

**Comment by dlwmacgregor** [comment] 2022-07-08 12:06
Understood.
Thanks for the clarification.
 
Doug

 

 

----- Original Message -----
From: Alexander V. Wolf ***@***.***>
Reply-To: Stellarium/stellarium 
***@***.***>
To: Stellarium/stellarium ***@***.***>
Cc: dlwmacgregor ***@***.***>, Author ***@***.***>
Sent: 7/8/2022 5:21:24 AM
Subject: Re: [Stellarium/stellarium] Cannot Delete Old Satellite Entry from 
Object List (Issue #2507)



Instead of searching by name, search by catalog # 25544 . Then click ' - ' at 
bottom of window.
Only way to change a name in the data base is to edit SATELLITES.JSON. A name 
comes from your input file. Check the name there before updating your elements.
This is related to Search Tool, not to Satellites plugin
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by dlwmacgregor** [comment] 2022-07-08 12:08
Thanks Jay.
I will implement the change going forward.
 
Cheers
Doug

 

 

----- Original Message -----
From: JAY-Githb ***@***.***>
Reply-To: Stellarium/stellarium 
***@***.***>
To: Stellarium/stellarium ***@***.***>
Cc: dlwmacgregor ***@***.***>, Author ***@***.***>
Sent: 7/8/2022 1:00:51 AM
Subject: Re: [Stellarium/stellarium] Cannot Delete Old Satellite Entry from 
Object List (Issue #2507)



Instead of searching by name, search by catalog # 25544 .
Then click ' - ' at bottom of window.
Only way to change a name in the data base is to edit SATELLITES.JSON.
A name comes from your input file. Check the name there before updating your 
elements.
Jay Respler
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by alex-w** [comment] 2022-08-03 09:30
Duplicate of #1470

**Closed** 2022-08-03 09:31 UTC
Labels: duplicate

**Comment by dlwmacgregor** [comment] 2022-10-11 08:20
Thanks Alex.
 
Doug

 

 

----- Original Message -----
From: Alexander V. Wolf ***@***.***>
Reply-To: Stellarium/stellarium 
***@***.***>
To: Stellarium/stellarium ***@***.***>
Cc: dlwmacgregor ***@***.***>, Author ***@***.***>
Sent: 7/7/2022 3:46:52 PM
Subject: Re: [Stellarium/stellarium] Cannot Delete Old Satellite Entry from 
Object List (Issue #2507)



Please see “Options” tab
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>
