### ISSUE TITLE
Build failure for release 0.20.3 on i586 architecture

### ISSUE THREAD

**Issue by ghost** [Stellarium/stellarium#1291] opened 2020-09-28 10:37 UTC
When building stellarium-0.20.3 on openSUSE Tumbleweed, the x86_64 target builds correctly, but the i586 fails consistently with the following error message:

[ 1160s] cd /home/abuild/rpmbuild/BUILD/stellarium-0.20.3/build/po/stellarium-planetary-features && /usr/lib/qt5/bin/lconvert -i /home/abuild/rpmbuild/BUILD/stellarium-0.20.3/po/stellarium-planetary-features/af.po -o /home/abuild/rpmbuild/BUILD/stellarium-0.20.3/build/translations/stellarium-planetary-features/af.qm
[ 1162s] terminate called after throwing an instance of 'std::bad_alloc'
[ 1162s]   what():  std::bad_alloc

Full log on https://build.opensuse.org/public/build/Education/openSUSE_Tumbleweed/i586/stellarium/_log

This is a humongous .po file, so my first hunch is that lconvert is just running out of memory. I upped the memory available for the build to 4 GB to no avail, so this might be yet another issue and/or internal to the Qt 5.15.1 we use for the build.

**Comment by gzotti** [comment] 2020-09-28 10:54
Duplicate of #1131. For reasons we don't understand, Qt5.15's lconvert uses several gigabytes of memory during translation.

**Comment by arjendekorte** [comment] 2020-10-04 09:13
There is one slight difference why I don't think this makes it a duplicate of #1131.

If you add enough memory and/or limit the number of parallel builds, eventually you'll be able to build Stellarium on Qt 5.15+ for 64-bit systems. This is not the case here. No matter how much free memory is available, you'll always get `terminate called after throwing an instance of 'std::bad_alloc'` when attempting to build on a 32-bit system since 0.20.3. This appears to be a limitation on the amount of memory that can be addressed by `lconvert` and has nothing to do with the actual free amount available.

We had to switch off translations on i586 by adding `-DENABLE_NLS=OFF` in order to get something to build, which is kind of sad.

**Comment by gzotti** [comment] 2020-10-04 11:12
lconvert cannot get what it thinks it needs, which seems to become more than addressable space on 32 bit, which is downright ridiculous. The reason is the same, a severe allocation bug in lconvert. Therefore it's classified a duplicate.

**Comment by gzotti** [comment] 2020-10-18 23:14
Closing this. The main issue (in lconvert) has been solved by Qt.

**Closed by gzotti** 2020-10-18 23:14 UTC
Labels: duplicate
