### ISSUE TITLE
Search for Abell 31 points to wrong RA/Dec location

### ISSUE THREAD

**Issue by Mickod5** [Stellarium/stellarium#1486] opened 2021-01-29 21:36 UTC
When performing Find for Abell 31, Stellarium centers to a point within Andromeda Galaxy, with incorrect RA/Dec information. Abell 31 is within the constellation of Cancer. 
A search for Abell 31 using different catalogue details i.e. PK 219+31.1 does pinpoint the correct area with corresponding image.

**Comment by gzotti** [comment] 2021-01-29 21:41
Duplicate of #1473. This is a different Abell catalog...

**Closed** 2021-01-30 03:14 UTC
Labels: data

**Comment by Mickod5** [comment] 2021-02-01 23:43
Can you please explain how or why there's more than one Abell catalogue? I thought these objects were numbered per a particular catalogue and that was that? I've so far been unable so find any reference to Abell 31 in Andromeda constellation...

**Comment by alex-w** [comment] 2021-02-02 02:03
Hint: http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Abell+31&NbIdent=1&Radius=2&Radius.unit=arcmin&submit=submit+id

**Comment by alex-w** [comment] 2021-02-02 02:05
The Abell’s planetary catalog was removed by 2 reasons: 1) all 6 different Abell’s catalogs has same designation prefix - Abell - and this is nightmare 2) professionals ask me why planetary catalog has Abell designation and suggested me that catalog of galaxies groups is more familiar and frequently used.

SIMBAD use Abell and ACO designations for gal. groups and PN A66 for catalog of planetary nebulae

**Comment by Ishtar66** [comment] 2021-02-25 01:57
So how do I find this PN in Stellarium? Zooming near mu Orionis doesn't show anything

**Comment by alex-w** [comment] 2021-02-25 02:22
PN A66 12?

**Comment by Ishtar66** [comment] 2021-02-25 03:54
PK 198-06.1

**Comment by Ishtar66** [comment] 2021-02-25 03:57
yes PK 198-06.1 and PN A66 12 are the same object.

Dan
