### ISSUE TITLE
Stellarium 0.21.2 for Macintosh isn’t working.

### ISSUE THREAD

**Issue by Hardthought** [Stellarium/stellarium#2109] opened 2021-12-17 20:53 UTC
### Actual Behaviour
Describe or maybe attach a screenshot?  Won’t open on this Mac 

Mini running
Model Name:	Mac mini
  Model Identifier:	Macmini6,2
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	424.0.0.0.0
  SMC Version (system):	2.8f0
  Serial Number (system):	C07K90JQDY3J
  Hardware UUID:	D359AFC0-DB3E-52B8-9E88-378CC18A416F

### Steps to reproduce
Load a Mac Mini and download the latest OS for the Mac mini described above.

### System
* Stellarium version: <Name of downloaded installable file?>0.21.2.zip
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>Intel Graphics 4000
* Screen type (if applicable): Resolution, HighDPI, scalingHDMI TV

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
2021-12-05T14:29:02
Operating System: Darwin 19.6.0 x86_64
Compiled using Clang 11.0.0
Qt runtime version: 5.12.9
Qt compilation version: 5.12.9
Addressing mode: 64-bit
Model Name: Mac mini
Model Identifier: Macmini6,2
Processor Name: Quad-Core Intel Core i7
Processor Speed: 2.6 GHz
Number of Processors: 1
Memory: 16 GB
Chipset Model: Intel HD Graphics 4000
VRAM (Dynamic, Max): 1536 MB
/private/var/folders/gc/0fpqnb1569n6qtxnv34r0rsr0000gp/T/AppTranslocation/6570A45C-42A6-46F3-83A8-7DD0B129C9AE/d/Stellarium 3.app/Contents/MacOS/stellarium -psn_0_315469 
 -----------------------------------------------------
[ This is Stellarium 0.21.2 - https://stellarium.org/ ]
[ Copyright (C) 2000-2021 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "/Users/Oscar/Library/Application Support/Stellarium/log.txt"
File search paths:
  0 .  "/Users/Oscar/Library/Application Support/Stellarium"
  1 .  "/private/var/folders/gc/0fpqnb1569n6qtxnv34r0rsr0000gp/T/AppTranslocation/6570A45C-42A6-46F3-83A8-7DD0B129C9AE/d/Stellarium 3.app/Contents/Resources"
Config file is:  "/Users/Oscar/Library/Application Support/Stellarium/config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 0, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "2.1 INTEL-14.7.20"
Current Format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 0, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
StelMainView::init
Driver version string: "2.1 INTEL-14.7.20"
GL vendor is "Intel Inc."
GL renderer is "Intel HD Graphics 4000 OpenGL Engine"
GL Shading Language version is "1.20"
Sky language is  "en_US"
Planetary features language is  "en_US"
Application language is  "en_US"
Empty translation file for language  "en_US" in section "stellarium-scripts"
Scripts language is  "en_US"
Cache directory is:  "/Users/Oscar/Library/Caches/stellarium/stellarium"
Loaded 252 countries
Loaded 193 regions
Loading Solar System data (1: planets and moons) ...
Loading from : "/private/var/folders/gc/0fpqnb1569n6qtxnv34r0rsr0000gp/T/AppTranslocation/6570A45C-42A6-46F3-83A8-7DD0B129C9AE/d/Stellarium 3.app/Contents/Resources/data/ssystem_major.ini"
SolarSystem has  83 entries.
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "/Users/Oscar/Library/Application Support/Stellarium/data/ssystem_minor.ini"
SolarSystem has  190 entries.
Loaded 107 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15747 / 15749 items of planetary surface nomenclature
WARNING - The next planets to assign nomenclature items is not found: "Dactyl"
Loading star data ...
"Loading /private/var/folders/gc/0fpqnb1569n6qtxnv34r0rsr0000gp/T/AppTranslocation/6570A45C-42A6-46F3-83A8-7DD0B129C9AE/d/Stellarium 3.app/Contents/Resources/stars/default/stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading /private/var/folders/gc/0fpqnb1569n6qtxnv34r0rsr0000gp/T/AppTranslocation/6570A45C-42A6-46F3-83A8-7DD0B129C9AE/d/Stellarium 3.app/Contents/Resources/stars/default/stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading /private/var/folders/gc/0fpqnb1569n6qtxnv34r0rsr0000gp/T/AppTranslocation/6570A45C-42A6-46F3-83A8-7DD0B129C9AE/d/Stellarium 3.app/Contents/Resources/stars/default/stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading /private/var/folders/gc/0fpqnb1569n6qtxnv34r0rsr0000gp/T/AppTranslocation/6570A45C-42A6-46F3-83A8-7DD0B129C9AE/d/Stellarium 3.app/Contents/Resources/stars/default/stars_3_1v0_4.cat: 3_1v0_4; 425807"
Finished loading star catalogue data, max_geodesic_level:  3
Loading scientific star names from "/private/var/folders/gc/0fpqnb1569n6qtxnv34r0rsr0000gp/T/AppTranslocation/6570A45C-42A6-46F3-83A8-7DD0B129C9AE/d/Stellarium 3.app/Contents/Resources/stars/default/name.fab"
Loaded 31141 / 31141 scientific star names
Loading variable stars from "/private/var/folders/gc/0fpqnb1569n6qtxnv34r0rsr0000gp/T/AppTranslocation/6570A45C-42A6-46F3-83A8-7DD0B129C9AE/d/Stellarium 3.app/Contents/Resources/stars/default/gcvs_hip_part.dat"
Loaded 6862 / 6862 variable stars
Loading double stars from "/private/var/folders/gc/0fpqnb1569n6qtxnv34r0rsr0000gp/T/AppTranslocation/6570A45C-42A6-46F3-83A8-7DD0B129C9AE/d/Stellarium 3.app/Contents/Resources/stars/default/wds_hip_part.dat"
Loaded 22992 / 22992 double stars
Loading cross-identification data from "/private/var/folders/gc/0fpqnb1569n6qtxnv34r0rsr0000gp/T/AppTranslocation/6570A45C-42A6-46F3-83A8-7DD0B129C9AE/d/Stellarium 3.app/Contents/Resources/stars/default/cross-id.dat"
Loaded 108378 / 108378 cross-identification data records for stars
Loading parallax errors data from "/private/var/folders/gc/0fpqnb1569n6qtxnv34r0rsr0000gp/T/AppTranslocation/6570A45C-42A6-46F3-83A8-7DD0B129C9AE/d/Stellarium 3.app/Contents/Resources/stars/default/hip_plx_err.dat"
Loaded 117703 / 117703 parallax error data records for stars
Loading proper motion data from "/private/var/folders/gc/0fpqnb1569n6qtxnv34r0rsr0000gp/T/AppTranslocation/6570A45C-42A6-46F3-83A8-7DD0B129C9AE/d/Stellarium 3.app/Contents/Resources/stars/default/hip_pm.dat"
Loaded 117955 / 117955 proper motion data records for stars
StelCore: Invalid timezone name: ""  -- not setting timezone.
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.13 (standard edition)"
Loaded 94668 DSO records
Loading DSO outline data ...
Loaded 95 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from "/private/var/folders/gc/0fpqnb1569n6qtxnv34r0rsr0000gp/T/AppTranslocation/6570A45C-42A6-46F3-83A8-7DD0B129C9AE/d/Stellarium 3.app/Contents/Resources/skycultures/western/star_names.fab"
Loaded 1098 / 1098 common star names
Loading DSO name data ...
Loaded 1142 / 1169 DSO name records successfully
WARNING - No position data for 27 objects: "NGC 3184, NGC 5907, NGC 5907, NGC 5907, PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 44750, PGC 54559, PGC 59117, PGC 59858, PGC 59953, PGC 69018, PGC 69877, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230, PGC 1000714, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  88 for culture "western"
Loaded 81 / 82 asterism records successfully for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
Loaded 71 / 72 asterism names
Got location "Savannah, Missouri, United States (39.9168, -94.8267; America/Chicago)" for IP "192.81.201.68"
stel.OpenGLArray: Disabling VAO usage because of Intel driver bugs
stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)
Initializing basic GL shaders... 
Creating GUI ...

**Comment by Hardthought** [comment] 2021-12-17 20:54
Doesn’t work on the Mac.  Works on a Dell with Ubuntu

**Comment by alex-w** [comment] 2021-12-17 20:57
Probably duplicate of #2048. Please install Security Update 2021-008 and check it again.

**Comment by Hardthought** [comment] 2021-12-30 14:42
Reinstalled the security update.  Works now.

**Closed** 2022-01-23 15:11 UTC
Labels: grading
