### ISSUE TITLE
skyculture greek_almagest : Search window: Specifications of lowercase and uppercase

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3942] opened 2024-10-09 02:29 UTC
### Expected Behaviour
Leo 33 is selected.

### Actual Behaviour
leo 33 is selected.

### Steps to reproduce

1. Select skyculture greek_almagest.
![20241008_3-1](https://github.com/user-attachments/assets/2d1d184c-f930-402e-9860-76715fd46ab0)

2. Show search window.

3. input "Leo 33" and Enter key.
![20241008_3-2](https://github.com/user-attachments/assets/79a6d81f-141a-473a-90d6-15d1e4c6a616)
![20241008_3-3](https://github.com/user-attachments/assets/b7d0935f-eb37-4472-9007-8cb45a15c7f2)

Maybe, this issue is related.
https://github.com/Stellarium/stellarium/issues/3800

### System
* Stellarium version: stellarium-24.3-qt5-win32.exe
* stellarium-24.3-600edc8-patch-qt5-win32.exe

* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by alex-w** [comment] 2024-10-09 17:13
Duplicate of #3800

**Closed** 2024-10-09 17:14 UTC
Labels: duplicate
