### ISSUE TITLE
Stellarium v0.20.2 will not auto connect to ASCOM Temma mount. Can only do it manually. Is there a fix for this ?

### ISSUE THREAD

**Issue by TomPickett671** [Stellarium/stellarium#1243] opened 2020-09-01 03:52 UTC
Stellarium v0.20.2 will not auto connect to ASCOM Temma mount. Can only do it manually. Is there a fix for this ?

**Comment by alex-w** [comment] 2020-09-01 08:09
Duplicate of #1164

**Closed by alex-w** 2020-09-01 08:09 UTC

**Comment by alex-w** [comment] 2020-09-17 16:17
Please check 0.20.3RC2
