### ISSUE TITLE
location map wrong 

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1026] opened 2020-03-29 23:04 UTC
### Expected Behaviour
the location pointer on the mini map corresponds to the current location info

### Actual Behaviour

The desired location is Ghent, but the pointer (and the list of locations) is more to the east.
![image](https://user-images.githubusercontent.com/3529789/77863368-1bdacc80-7222-11ea-99f6-89ccd42bd2b3.png)

when I click on a location on the map, the pointer is moved to an offset location. There seems to be  constant offset of few hundred pixels to the right of the clicked location.

### System
* Stellarium version: 0.20 (but already earlier)
* Operating system: Kubuntu 18
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/4402483/log.txt)

**Comment by gzotti** [comment] 2020-03-30 07:50
Again you did not tell us that you are running Stellarium (1) on Linux  and (2) on a HiDPI device. These things are essential.

**Comment by axd1967** [comment] 2020-03-30 08:03
yes, sorry. this issue is not related to 0.20, I noticed it a few releases back.
(I was not aware of the HiDPI thing)

**Comment by alex-w** [comment] 2020-03-30 08:04
This is not exactly HiDPI device - looks like 110% scaling was enabled

**Comment by axd1967** [comment] 2020-03-30 08:18
You are right:
![image](https://user-images.githubusercontent.com/3529789/77889722-97626b00-726e-11ea-8540-dbd7cf3d021c.png)

workaround is to select scale 1.

**Comment by gzotti** [comment] 2020-03-30 08:37
FYI "it works on Windows". I can even reset scaling while running Stellarium. This changes pixel size but keeps the button bars where they belong. We just need more testers-who-can-also-fix-small-nuisances caused by all kinds of settings here and there on more OS/GUI variants and the ever growing hardware zoo.

**Comment by alex-w** [comment] 2020-03-30 08:40
In any way I cannot reproduce the issue on my linux

**Comment by gzotti** [comment] 2020-03-30 08:43
OK, @axd1967 please edit the report above and write your system specs accurately. e.g. Kubuntu?

**Comment by axd1967** [comment] 2020-03-30 11:56
> ... all kinds of settings here and there on more OS/GUI variants and the ever growing hardware zoo.

I understand your problem.

**Comment by alex-w** [comment] 2021-06-09 15:32
@axd1967 please check the master

**Comment by alex-w** [comment] 2021-06-16 20:00
@axd1967 any news for the issue status?

**Comment by alex-w** [comment] 2021-06-18 13:22
I think the issue is fixed now, at least I cannot reproduce it on my MacBook (Retina display)

**Closed by alex-w** 2021-06-18 13:22 UTC
Labels: bug

**Comment by axd1967** [comment] 2021-06-18 19:51
Sorry can't reproduce this for now, but will keep an eye on it.
