### ISSUE TITLE
[0.14.3] [Linux Mint 18.3] Incorrect Planetary Moon Transits

### ISSUE THREAD

**Issue by Flexico** [Stellarium/stellarium#864] opened 2019-11-28 07:13 UTC
While watching Phobos and Deimos orbit Mars, I noticed that Phobos passes *behind* Mars twice on its orbit, where it should be once in front and once behind. I checked Jupiter, and the same thing happens with Europa, Ganymede, Io and Callisto. Not sure if this is considered a bug or a feature, but I would love to see the transits work realistically!

[Edit] Upon further inspection, I realize that the moons' images do transit the planets correctly, but the glow added to them when viewed from fairly far away diminishes greatly, making it seem to pass behind the planet. Is there a way to adjust this behavior?

**Comment by alex-w** [comment] 2019-11-28 07:48
Looks like double of #82

**Comment by Flexico** [comment] 2019-11-28 07:55
Ah dangit I searched for a duplicate but apparently used the wrong keywords. XD

**Comment by gzotti** [comment] 2019-11-28 11:03
I cannot confirm this on Win10/Geforce960M. The moons are properly rendered in front or behind the parent planet. 

However, the overbright white halo of e.g. Phobos is not drawn when the moon is in front of Mars. Zoom in to see the tiny sphere. You will also not see a white point going over the disk of Mars in your telescope.

Not a duplicate of #82, I also just commented on that, there.

**Comment by gzotti** [comment] 2019-11-28 20:32
Please don't edit your issue report on top to add new thoughts to the discussion. This breaks the timeline. 

The implementation: _hide moon's halo when the moon is in front of the planet_ is intentional and cannot be switched away. When Io transits Jupiter, you don't see a white extra spot. Likewise, you should have a pretty hard time to spot Phobos in front of Mars, there is no white spot in transit. We might want to have a white spot when Phobos is in front of the shadowed side of Mars. This is just a bit trickier to implement...

**Closed** 2019-12-14 07:52 UTC
Labels: invalid
