### ISSUE TITLE
Stellarium 1.1 Crash

### ISSUE THREAD

**Issue by w5pny** [Stellarium/stellarium#2800] opened 2022-10-31 18:01 UTC
Expected Behaviour

No Crash

Actual Behaviour

QMetaProperty::read: Unable to handle unregistered datatype 'DitheringMode' for property 'StelCore::ditheringMode'
StelProperty StelCore.ditheringMode can not be read. Missing READ or need to register MetaType?
Aborted (core dumped)

Steps to reproduce

Compile stellarium -- No errors

run stellarium

System

* Stellarium version: stellarium-1.1.tar.gz
* Operating system: Linux maui 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Graphics Card: Nvidia Quadro P4000 Driver Version: 515.65.01

Logfile 

2022-10-31T11:43:57
Operating System: Ubuntu 20.04.5 LTS
Compiled using GCC 9.4.0
Qt runtime version: 5.12.8
Qt compilation version: 5.12.8
Addressing mode: 64-bit
MemTotal:       32562720 kB
MemFree:          313240 kB
MemAvailable:   24146384 kB
SwapTotal:      134217724 kB
model name	: Intel(R) Xeon(R) W-2125 CPU @ 4.00GHz
cpu MHz		: 1199.998
model name	: Intel(R) Xeon(R) W-2125 CPU @ 4.00GHz
cpu MHz		: 3919.830
model name	: Intel(R) Xeon(R) W-2125 CPU @ 4.00GHz
cpu MHz		: 1200.022
model name	: Intel(R) Xeon(R) W-2125 CPU @ 4.00GHz
cpu MHz		: 3899.254
model name	: Intel(R) Xeon(R) W-2125 CPU @ 4.00GHz
cpu MHz		: 1200.017
model name	: Intel(R) Xeon(R) W-2125 CPU @ 4.00GHz
cpu MHz		: 3528.468
model name	: Intel(R) Xeon(R) W-2125 CPU @ 4.00GHz
cpu MHz		: 1200.122
model name	: Intel(R) Xeon(R) W-2125 CPU @ 4.00GHz
cpu MHz		: 3529.660
0000:65:00.0 VGA compatible controller: NVIDIA Corporation GP104GL [Quadro P4000] (rev a1) (prog-if 00 [VGA controller])
Kernel driver in use: nvidia
Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia
stellarium 
 ------------------------------------------------------------
[ This is Stellarium 1.1 (v0.22.4) - https://stellarium.org/ ]
[ Copyright (C) 2000-2022 Stellarium Developers              ]
 ------------------------------------------------------------
Writing log file to: "/home/hgm/.stellarium/log.txt"
File search paths:
  0 .  "/home/hgm/.stellarium"
  1 .  "/usr/local/share/stellarium"
Attempting to use an existing older config file.
Cleared cache and updated config.ini...
Config file is:  "/home/hgm/.stellarium/config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
OpenGL module type: 0
Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
Default surface format:  QSurfaceFormat(version 3.3, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::CoreProfile)
OpenGL module type: 0
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "3.3.0 NVIDIA 515.65.01"
Current Format:  QSurfaceFormat(version 3.3, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 0, stencilBufferSize 0, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::CoreProfile)
StelMainView::init
Luminance textures are not supported
Detected: OpenGL "3.3"
Driver version string: "3.3.0 NVIDIA 515.65.01"
GL vendor is "NVIDIA Corporation"
GL renderer is "Quadro P4000/PCIe/SSE2"
GL Shading Language version is "3.30 NVIDIA via Cg compiler"
GLSL Version Number detected:  3.3
GLSL version is fine, we should not see a graphics problem.
stel.OpenGLArray: Vertex Array Objects are supported
Sky language is  "en_US"
Empty translation file for language  "en_US" in section "stellarium-planetary-features"
Planetary features language is  "en_US"
Application language is  "en_US"
Scripts language is  "en_US"
Cache directory is:  "/home/hgm/.cache/stellarium/stellarium"
Loaded 252 countries
Loaded 193 regions
StelLocationMgr::loadCitiesBin(): TimeZone for  "Berehove"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Khust"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Mukachevo"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Rakhiv"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Svalyava"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Uzhgorod"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): TimeZone for  "Vynohradiv"  not found:  "Europe/Uzhgorod"
StelLocationMgr::loadCitiesBin(): Summary of unknown TimeZones:
"Europe/Uzhgorod"
Please report these timezone names (this logfile) to the Stellarium developers.
Loading Solar System data (1: planets and moons) ...
Loading from : "/usr/local/share/stellarium/data/ssystem_major.ini"
SolarSystem has  83 entries.
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "/home/hgm/.stellarium/data/ssystem_minor.ini"
SolarSystem has  190 entries.
Loaded 107 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15833 / 15835 items of planetary surface nomenclature
WARNING - These planets to assign nomenclature items were not found: "Dactyl"
Loading star data ...
"Loading /usr/local/share/stellarium/stars/default/stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading /usr/local/share/stellarium/stars/default/stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading /usr/local/share/stellarium/stars/default/stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading /usr/local/share/stellarium/stars/default/stars_3_1v0_4.cat: 3_1v0_4; 425807"
"Loading /home/hgm/.stellarium/stars/default/stars_4_1v0_2.cat: 4_1v0_4; 1692779"
"Loading /home/hgm/.stellarium/stars/default/stars_5_2v0_1.cat: 5_2v0_1; 7083058"
"Loading /home/hgm/.stellarium/stars/default/stars_6_2v0_1.cat: 6_2v0_1; 24670782"
Finished loading star catalogue data, max_geodesic_level:  6
Loading scientific star names from "/usr/local/share/stellarium/stars/default/name.fab"
Loaded 4942 / 4942 scientific star names
Loading scientific star extra names from "/usr/local/share/stellarium/stars/default/extra_name.fab"
Loaded 26200 / 26200 scientific star extra names
Loading variable stars from "/usr/local/share/stellarium/stars/default/gcvs_hip_part.dat"
Loaded 6862 / 6862 variable stars
Loading double stars from "/usr/local/share/stellarium/stars/default/wds_hip_part.dat"
Loaded 22992 / 22992 double stars
Loading cross-identification data from "/usr/local/share/stellarium/stars/default/cross-id.dat"
Loaded 108378 / 108378 cross-identification data records for stars
Loading parallax errors data from "/usr/local/share/stellarium/stars/default/hip_plx_err.dat"
Loaded 117703 / 117703 parallax error data records for stars
Loading proper motion data from "/usr/local/share/stellarium/stars/default/hip_pm.dat"
Loaded 117955 / 117955 proper motion data records for stars
navigation/preset_sky_time is a double - treating as jday: "2459884.25764"
QMetaProperty::read: Unable to handle unregistered datatype 'DitheringMode' for property 'StelCore::ditheringMode'
StelProperty StelCore.ditheringMode can not be read. Missing READ or need to register MetaType?

**Comment by alex-w** [comment] 2022-10-31 18:02
Duplicate of #2799

**Closed** 2022-10-31 18:03 UTC
Labels: duplicate
