### ISSUE TITLE
Objects not selectable at higher zoom level

### ISSUE THREAD

**Issue by StarFlea** [Stellarium/stellarium#3832] opened 2024-07-30 14:12 UTC
Hello folks!

To select an object (e.g. star, asteroid, ...) in Stellarium, you simply click on it. But at a higher zoom level, the same object is not selectable anymore.

Example: Pluto - At this level there is no problem. Pluto is selected
![Pluto_1](https://github.com/user-attachments/assets/3337cf16-d043-4193-a10c-1a06c6ec1df5)

But if you zooming in, Pluto is not selected by mouseclick on it but the star on the right. You can click furthermore, but Pluto is unreachable...
![Pluto_2](https://github.com/user-attachments/assets/15ded254-9767-464b-8104-2b694bfb84ec)

The same problem exists with other objects, e.g. stars. At a higher zoom-level you have not to click directly to the object, but a little bit away to select it.

Version 24.2.197-623f996 [HEAD]
Based on Qt 5.12.6
Windows : 10

Best regards!
StarFlea

**Comment by gzotti** [comment] 2024-07-30 14:21
Duplicate of https://github.com/Stellarium/stellarium/issues/3733

**Closed by gzotti** 2024-07-30 14:21 UTC
Labels: duplicate
