### ISSUE TITLE
getSelectedObjectInfo issue

### ISSUE THREAD

**Issue by pincopazzino** [Stellarium/stellarium#1483] opened 2021-01-24 01:21 UTC
Hello.
I need to retrieve all the names of a selected object. If I use the attribute "name" by getSelectedObjectInfo, I just obtain the main English name, but not the long names list (from the diverse catalogues) I see on the screen. Which class/method have I to use?
Thanks.

**Comment by alex-w** [comment] 2021-01-26 13:47
Duplicate of #1477

**Closed** 2021-01-26 13:48 UTC
Labels: duplicate
