### ISSUE TITLE
Saving the current data to a file

### ISSUE THREAD

**Issue by psknick** [Stellarium/stellarium#2245] opened 2022-02-06 10:05 UTC
Good day! I am engaged in historical research at the intersection of history and astronomy. With the help of the program, I build tracks of the planets, analyze the relative position of the planets in different years and epochs. But each time after turning off the program and then turning it on, to resume work from the interrupted place, all the data on the monitor screen has to be restored again.

For example, in the figure Marker 1 and Marker 2 are the extreme points of the Jupiter loop, Marker 3 and Marker 4 are the extreme points of the Saturn loop. Also, the tracks of the loops of Mercury and Venus are drawn. The goniometer shows the angular distance between Venus and Mars. Esna Egypt coordinates, date and time. After shutting down the program, all data is lost...

**Wish**. Is it possible to save the image on the program screen to a file? What would later, to continue working from the interrupted place, load data into the program and receive on the monitor screen at the saved date and time: markers, the location of planets and stars, planet tracks, observation site coordinates, angle of view, goniometer readings.
Thanks! 
![2022-02-06_12-31](https://user-images.githubusercontent.com/44753018/152675925-77d7868d-c4d6-4a48-aeb1-b1ebe215dbbd.png)

**Comment by gzotti** [comment] 2022-02-06 10:31
You can store your location in the location dialog. You could probably write the markers in a script once you have found their locations. It is not possible o have something like a "work sheet" where you could resume a "session".

**Comment by freebrowser1** [comment] 2022-04-21 05:45
That is a strong limitation that Stellarium is not able to save the current state in a file. Apps like Starrynight or SkySafari do have this useful option.
Why not adding an option 'Save as' which saves the current configuration to just another file than the standard 'ssettings.ini' or ''config.ini' ?

**Comment by alex-w** [comment] 2022-06-09 14:38
Duplicate of #439

**Closed** 2022-06-09 14:39 UTC
Labels: duplicate, wishlist
