### ISSUE TITLE
Dark lanes & Star Chains in GC

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#1093] opened 2020-05-15 06:07 UTC
Some objects worth to be observe are the Dark lanes and Star Chains inside Globular clusters (Maybe also can be found inside Open Clusters).
One popular example is the Propeller inside M13, which can be seen in Rosse’s sketch. We can find much more in _Dark Nebulae, Dark Lanes, and Dust Belts_.
Is that possible for realizing those as a feature?

**Comment by alex-w** [comment] 2020-05-15 06:44
Sorry, but this is task for some booklet or guide - I think we shouldn't add very specific details of some objects into main database of DSO. Maybe it can be part of plugin, which you proposed early.

**Comment by alex-w** [comment] 2020-05-15 06:46
As some solution - you can expand current Stellarium User Guide and add new chapter for part IV of SUG.

**Comment by ultrapre** [comment] 2020-05-26 12:42
> As some solution - you can expand current Stellarium User Guide and add new chapter for part IV of SUG.

Adding into the User Guide is good, and how can I participate in the work?

**Comment by alex-w** [comment] 2020-05-26 13:15
Are you know LaTeX (See example: https://github.com/Stellarium/stellarium/blob/master/guide/ch_sky_guide.tex)?

**Comment by gzotti** [comment] 2020-06-21 16:05
This is basically a duplicate of #1075.

**Closed** 2020-09-30 06:55 UTC
Labels: duplicate, opinion
