### ISSUE TITLE
Rise, transit and setting time changes during the same day

### ISSUE THREAD

**Issue by lucaberti** [Stellarium/stellarium#2024] opened 2021-11-10 10:18 UTC
Rise, transit and set times of an object should remain constant during the same day. But in Stellarium if you fast forward of some hours, the rise, transit and set time change two or more times in the same day.

### To reproduce
Select an object (e.g. the Moon) when it's just rised over the horizon. Start forwarding time  by hitting the +1 hour button. Monitor the rise, set and transit time in the information list: they will change a couple of times during the same day.

### Discussion
While it could be argue that after an event (e.g. after an object has rised over the horizon) that information could be refered to the next event (the one from the day after), this is not a suitable behaviour in my opinion, since people would like to know when is the time of that event in that specific day. But even so, these times should not change more than one time per dey.

### System
* Stellarium version: 0.21.0
* Operating system: W11
* Graphics Card: Nvidia

**Comment by alex-w** [comment] 2021-11-10 10:23
Duplicate of #554

**Comment by lucaberti** [comment] 2021-11-10 10:35
Sorry for the duplicate, I did actually check, without finding anything.

**Comment by gzotti** [comment] 2021-11-10 11:41
Please update and check whether the issue still persists for you in the latest version, 0.21.2, where exactly this issue has been solved.

**Comment by lucaberti** [comment] 2021-11-10 13:16
Yes, the issue is very much still present in 0.21.2

**Comment by alex-w** [comment] 2021-11-10 13:20
Please check it with any other object (not Moon)

**Comment by A-j-K** [comment] 2021-11-11 14:00
I tried to reproduce. I found the errant behaviour is seen on the Moon. It was **not** observed on the Sun, any planet or star.

**Comment by A-j-K** [comment] 2021-11-11 14:11
My guess here is that the changing time is due to the close orbit of the Moon and its actual movement across the sky. The rise/transit/set times are continuously calculated at "now" as "now" progresses and therefore change as the Moon orbits "close by".

**Comment by gzotti** [comment] 2021-11-13 23:47
Answered in https://github.com/Stellarium/stellarium/pull/1852#issuecomment-925272123

Provide us with a better algorithm!

**Closed** 2022-02-04 13:38 UTC
Labels: enhancement, help wanted, low importance
