### ISSUE TITLE
Position coordinate entry in search window not working correctly on latest version

### ISSUE THREAD

**Issue by Mogwai77** [Stellarium/stellarium#2346] opened 2022-03-13 09:36 UTC
### Expected Behaviour
Select search window, select position tab, use EQ(J2000.0)
Enter co-ords, retical move to position.

### Actual Behaviour
Doing above RA co-ords move but DEC do not

### Steps to reproduce
Issue was consistent, shut down and reboot, uninstalled latest version still faulted.
Compared operation using same process on a PC with older version (0.20.04) and worked as it should.
Uninstalled latest version from laptop and installed version 0.20.04, worked perfectly.

Coordinates being used to test were: RA 11:11:17 DEC: -61deg 43Mins 51Sec (nothing in particular, just center of a plate solved image)

### System
* Stellarium version: stellarium-0.21.3-win64
* Operating system: Win10 Version 10.0.19043 Build 19043
* Graphics Card: Intel(R) HD Graphics
* Screen type (if applicable): Resolution	1920 x 1280 x 60 hertz

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment] 2022-03-13 09:42
Duplicate of #2205 and several others.

**Closed** 2022-03-13 09:43 UTC
Labels: duplicate
