### ISSUE TITLE
Mutual occultations and eclipses of the Galilean satellites

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium#2413] opened 2022-04-20 15:05 UTC
https://skyandtelescope.org/astronomy-news/mutual-event-season-heats-up-at-jupiter/

It seems that it can't calculate and predict the mutual occultations and eclipses of the Galilean satellites, adding satellites list to Phenomena may be good. 
And further, do you know whether there is a website to predict them? Same for other satellites like Titan etc, because their mutual occultations and eclipses seem to be rare but predictable in long time, unlike asteroids.

**Comment by alex-w** [comment] 2022-04-20 16:47
Duplicate of #1739

**Closed** 2022-04-20 16:48 UTC
Labels: duplicate
