### ISSUE TITLE
Adding the perihelion and aphelion calculations of the planets to AstroCalc's ephemeris

### ISSUE THREAD

**Issue by Ironman65** [Stellarium/stellarium#874] opened 2019-12-10 05:31 UTC
Is it possible to add to the AstroCalc’s ephemeris the planets Perihelion and Aphelion?  like it calculates the conjunctions and oppositions. This would be a nice feature if possible and would be great for calculating the future observations of Mars especially to see if it’s at Perihelion is around its opposition. I do understand as a non programmer that adding a new feature can ether slowdown or even cause the program to crash and burn depending on the code of the program which it is written in, in such cases no feature is worth it specially if it causes it to crash. Again thanks for all that you do.

**Comment by gzotti** [comment] 2019-12-10 09:56
This is a duplicate of your #850. Again: Stellarium does not compute the orbital elements from which apices could be directly derived and shown in either the main screen or a table, but uses series of cosine terms for the planets' positions.
You should be able to make a Curve plot showing just the distance to Mars and run this over 15 years or so to get an idea when Mars is best visible. 
@alex-w Maybe you could enrich the Curve panel with a larger date range?

**Comment by alex-w** [comment] 2019-12-10 10:51
It's not full duplicate of request. For question of graphs - yes, we can extend the graphs, but how much it should be enlarged? 1..10 years since 1 January of current year?

**Comment by gzotti** [comment] 2019-12-10 12:30
Well, either 1-30 (~Saturn year?) full years or fully free start and end dates? Clearly, labeling will be a challenge.

**Closed** 2019-12-10 12:39 UTC
Labels: duplicate, enhancement

**Comment by alex-w** [comment] 2019-12-10 13:25
@gzotti please check the English terms in latest changes - I hope this is acceptable and understandable

**Comment by gzotti** [comment] 2019-12-10 14:14
A few changes please:
- "Graphs since January 1st of the current year"
- "Duration (years):"  or "Duration: [SPINBOX] years" (and add a spacer between that and ["draw curves"]
- The interval spacing is odd (already in the graph for 1 year). Depending on actual duration, could be months, 3-months, 6-months or even full years. The labels *must* also give years. If partitions are full months, you could omit the day number instead.

**Comment by alex-w** [comment] 2019-12-10 15:20
In the our current version of QCustomPlot changing labels type for temporal axis is very problematic. Yes, we can ask authors of newest version of QCustomPlot to allow for us obtain that new version under GPLv2 again, but I don't want refactor all parts for graphs after upgrading QCustomPlot at the moment (if we'll got permission). In any way I've added obvious visual workaround for the borders of the years.

**Comment by gzotti** [comment] 2019-12-10 16:54
OK, I did not know these details of QCustomPlot. The year separators are also OK. Now I just rediscovered the 15-year pattern for Mars :-)
As great as AstroCalc has evolved, CodeFactor complains already about its complexity. Take care to keep it maintainable!
