### ISSUE TITLE
Problems with geographical coordinates

### ISSUE THREAD

**Issue by victorman1998** [Stellarium/stellarium#2210] opened 2022-01-24 11:55 UTC
When I try to manually type a specific coordinate in Stellarium v0.21.3, latitude and/or longitude won't change as I please, unless I use the arrows on the right side of the coordinate box. This hasn't happened to me within previous versions of Stellarium. I even tried uninstalling and reinstalling the program, but the result was the same. Please, help me fix this bug, because I seriously need to check the sky in some places that aren't specifically listed.

**Comment by alex-w** [comment] 2022-01-24 11:57
Duplicate of #2209 probably

**Comment by victorman1998** [comment] 2022-01-24 11:59
> Duplicate of #2209 probably

I didn't notice that issue. It seems to be the same for other people too. Thank you!

**Comment by gzotti** [comment] 2022-01-24 12:02
I usually click into one of the numbers and change the value via mouse wheel. The change takes place immediately. For fine-tuning (sub-arcsecond) I edit the number. Does that not work for you?

**Comment by alex-w** [comment] 2022-01-24 12:04
@gzotti after switching to new RegualExression class some special chars from old RegExp class didn't work properly. I've fixed it today.

**Closed** 2022-01-24 12:07 UTC

**Comment by gzotti** [comment] 2022-01-24 12:12
I just tried it out, and it works in 0.21.3. At least on Win10.

**Comment by victorman1998** [comment] 2022-01-24 15:30
> Hello @victorman1998! Please check the fresh version (development snapshot) of Stellarium: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

Thank you! Now it seems to work fine whatever values I enter for coordinates.
