### ISSUE TITLE
Search do not works in new version 1.0 

### ISSUE THREAD

**Issue by gperuzzo** [Stellarium/stellarium#2768] opened 2022-10-22 23:31 UTC
In the new version 1.0, when you get in the Search menue, you can find objects but when you select on one of them, the software do not goes to the objet selected, and the search windows remains opend.
Thanks

**Comment by alex-w** [comment] 2022-10-22 23:34
Cannot confirm the issue, please more details

**Comment by gzotti** [comment] 2022-11-21 17:09
We cannot reproduce the issue, and OP did not react for a month. I close this.

**Closed by gzotti** 2022-11-21 17:09 UTC
Labels: need more info
