### ISSUE TITLE
Inaccurate cursor position in High DPI display

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#386] opened 2018-09-26 04:11 UTC
_Original report by Khalid AlAjaji:_ https://bugs.launchpad.net/stellarium/+bug/1715048

Stellarium recent builds
Windows 10
High DPI system

The issue happens in window mode only. Full screen mode is fine.

The upper part of Stellarium display is hidden and cursor clicks are inaccurate.

The following link has a small clip demonstrating the issue:
https://drive.google.com/open?id=0BxpVQFfkq8NSMXQzZ1l4MWU0aVE

The issue happens even if the resolution is reduced to 1920 X1080

a sample log is here:
https://drive.google.com/file/d/0BxpVQFfkq8NSUnBpTkdoVF9VUDA/view?usp=sharing

Thanks

**Comment by gzotti** [comment] 2018-09-27 13:11
I cannot reproduce this in FullHD/windowed mode. Is it still unsolved in current betas?

**Comment by kajaji** [comment] 2018-11-25 19:34
This issue is fixed in recent releases. Thanks

**Closed** 2018-11-25 19:41 UTC
Labels: bug, incomplete
