### ISSUE TITLE
Display the object symbol instead of the full name

### ISSUE THREAD

**Issue by salarmehr** [Stellarium/stellarium#3255] opened 2023-06-02 06:47 UTC
To see less clutter, could you please add an option to display the object symbol when available instead or in addition to the object name? (particularly for planets and constellations)
https://en.wikipedia.org/wiki/Astronomical_symbols
https://solarsystem.nasa.gov/resources/680/solar-system-symbols/

**Comment by alex-w** [comment] 2023-06-02 07:19
Duplicate of #1628

**Closed** 2023-06-02 07:20 UTC
Labels: duplicate
