### ISSUE TITLE
Screen goes black for a brief moment then image reappears, flickering

### ISSUE THREAD

**Issue by omikron24** [Stellarium/stellarium#2484] opened 2022-06-07 12:28 UTC
### Steps to reproduce

Start any Stellarium executable, click on any object, scrollin in a bit and screen flickers after that.

### System
* Stellarium version: 0.22.1
* Operating system: Win 10 Pro, 21H2, build 19044.1706
* Graphics Card: Nvidia gtx 1080ti, driver 512.15, no overclocking.
* Screen type (if applicable): LG C9 TV, resolution 1920:1080, HDMI, 120Hz, 12 bpc, RGB signal, no HDR,  scaling 150% (changed scaling - no effect)

### Logfile 
File attached
[log.txt](https://github.com/Stellarium/stellarium/files/8853144/log.txt)

**Comment by omikron24** [comment] 2022-06-07 14:33
I didn't notice issues in windowed mode in any executable, typically issue arises in first couple of minutes - in windowed mode I wasn't able to reproduce it

**Comment by alex-w** [comment] 2022-06-08 06:42
Probably same issue as #2166

**Comment by alex-w** [comment] 2022-06-08 06:47
Hmm... this issue (according to video) may be related with bug #2240

**Comment by omikron24** [comment] 2022-06-08 07:00
I've checked if the moon is triggering the bug in full screen mode and it seems it does, because sometimes I can poke around for a quite a while until moon gets in the view, after that flickering start as described in the first message.

**Comment by alex-w** [comment] 2022-06-13 16:42
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by omikron24** [comment] 2022-06-14 05:27
Hello, tried a fresh build - 0709c62, Moon still triggers black screen flashing.

**Comment by gzotti** [comment] 2022-06-14 07:48
The video shows just one flash. Is this only once, or does a regular flashing pattern evolve as soon as the Moon entered the scene? The planet shader gets uploaded to the GPU only when needed, this may probably cause a short hickup, but with a Geforce I would be surprised.

Can you try with a different physical screen, not a TV set?

**Comment by omikron24** [comment] 2022-06-14 09:23
There are two different patterns that I've seen so far - one that was recorder - black screen with intermittent white flash -this one is related to the Moon. Otherwise the program sometimes gives me very different black screen - it is black screen that is divided in about 30 squares, each square has a green artifact in  left upper corner, it flashes for a split second but I don't have camera around to catch it every time.

Regarding display - no, only one screen, can't test on another.

**Comment by gzotti** [comment] 2022-06-15 20:55
The green artifacts are nothing we will be able to solve. GPU driver (unlikely), TV or maybe even the HDMI cable, all can play a role here.

**Comment by 10110111** [comment] 2022-06-19 12:58
> 12 bpc

Is this a setting you can set in the Windows' screen configuration GUI? Does the problem reproduce in 8 bpc mode?

> I didn't notice issues in windowed mode in any executable, typically issue arises in first couple of minutes - in windowed mode I wasn't able to reproduce it

What if you maximize the window? It might happen when the window is "large".

**Comment by omikron24** [comment] 2022-06-20 08:49
8 bpc - same result, still flashing. Couldn't reproduce flashing in any windowed size. Only flashes in full screen mode.

**Comment by alex-w** [comment] 2022-06-30 04:52
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by omikron24** [comment] 2022-07-07 10:50
Hello there, close but no cigar - the flashing still occurs in full screen mode

**Comment by omikron24** [comment] 2022-07-07 10:52
> Please check the fresh version (development snapshot) of Stellarium: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

Hello there, close but no cigar - the flashing still occurs in full screen mode

**Comment by omikron24** [comment] 2022-07-07 13:15
Let me check that in one hour

**Comment by omikron24** [comment] 2022-07-15 14:08
> Let me check that in one hour

That was one long hour, however I wasn't able to reproduce the bug on my work notebook.

**Comment by gzotti** [comment] 2022-07-18 10:02
@omikron24 Can we close this then?

**Comment by omikron24** [comment] 2022-07-20 07:08
> @omikron24 Can we close this then?

One last attempt - maybe this info will be useful, I've noticed that even though I've forced the program to run at 120 FPS from NVIDIA control panel and set minimum FPS to 120 in stellarium config.ini - when I select the Moon, after couple of seconds screen flashes and FPS drops dramatically to 70~ish or even lower as if renderer disconnects, I've reinstalled windows 10 pro, latest build and updates, reinstalled Nvidia drivers with DDU to check if they have any impact.

**Comment by gzotti** [comment] 2022-07-20 08:02
I think you cannot force the program to higher frame rates than the CPU loop allows. Usually we recommend low rates: The sky does not move so fast, and setting to e.g. 25fps takes less energy. Usually when the user moves the screen framerate goes as high as possible, then goes down again. This is intended. Screen flashing is of course not intended, and it would take an expert plagued with a flickering system to analyze and hopefully fix this issue then.

**Comment by alex-w** [comment] 2022-08-02 18:09
Could you test our Qt6 (v1.22.2-3d47d9a) [weekly snapshot](https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot) also?

**Closed** 2022-09-03 15:03 UTC
Labels: help wanted, importance: low
