### ISSUE TITLE
Telescope control via RS232 USB broken

### ISSUE THREAD

**Issue by Baudouin0** [Stellarium/stellarium#3006] opened 2023-01-19 17:31 UTC
### Expected Behaviour
Connects to telescope
### Actual Behaviour
Does not connect. Shows as COM4 on GUI connect to skywatcher syncscan controller. Does not connect.
Works fine if you roll back to last version 1,1 and 0,22.2

### System
* Stellarium version: 1.2 latest
* Operating system: Windows 64 bit
* Graphics Card:  NVidia
* Screen type (if applicable): HD

**Comment by gzotti** [comment] 2023-01-19 18:02
Duplicate of #2934?

**Comment by gzotti** [comment] 2023-01-19 18:04
Did it work with a Qt6-based 1.1? I wonder whether we have yet another new error between 1.1 and 1.2. Reportedly a Qt5-based build of 1.2 works.

**Comment by TonyBhargav** [comment] 2023-01-22 12:18
hi @gzotti  , I would like to work on this issue as a part of academic course work ,It would be a great opportunity for me to learn about the project architecture and design as well. Could you please assign it to me

**Comment by gzotti** [comment] 2023-01-22 12:25
Thanks. Please have a look into all these reports since September around telescope plugin, Qt6 and failed connections. It may be just a small thing, but I think you need the actual hardware to test and fix this. 

Start with cloning our repo, creating a branch, build with Qt5.12 and Qt6 (6.4 or later), and then you can go after fixing the issues.

**Comment by TonyBhargav** [comment] 2023-01-22 12:34
Sure, i will look into it .
Thank you

**Comment by Baudouin0** [comment] 2023-01-23 10:30
Cheers for looking into this. You can test just with the controller EQ6 handset only without the mount, that how I regression tested.



Charles Baudouin
Chief Technical Architect

Email: ***@***.******@***.***>
Mobile / WhatsApp: +44 7973 146 671
Telephone: +44 1489 884 430
Skype / Teams: ***@***.***


DOMO TACTICAL COMMUNICATIONS (DTC) LTD TRADING AS DTC
Registered office Fusion 2, 1100 Parkway, Whiteley, Hampshire, PO15 7AB, United Kingdom
Registered in England and Wales, company number 1456922
[cid:dtclogo203x88_8fe7e5cd-210b-49fc-b334-f34189be7d63.png]
[cid:dtcbanner310x28_238a1048-71d6-4715-a939-5711d6112998.png]<https://www.domotactical.com> [cid:dtclinkedin_a3728679-7599-4be1-b6de-f3d4ef39d277.png] <https://www.linkedin.com/company/domo-tactical-communications-dtc-ltd/>   [cid:dtctwitter_cdec30e7-2e23-4f9d-818a-2c6988db3154.png] <https://twitter.com/domobroadcast>   [cid:dtcyoutube_6705831e-f9e4-476e-a851-6f7da307562d.png] <https://www.youtube.com/channel/UC0nBUhsZ9iakjODp9nYRDSw>


[cid:dtcbanner422x60_21bb8f55-b378-4df3-bd7e-5be7a3b4c503.png]
PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS EMAIL
This e-mail and any files transmitted with it is intended solely for the addressee(s) and may contain information that is proprietary, privileged, company confidential and/or exempt from disclosure under applicable law. If you are not the intended addressee(s), any disclosure, reproduction, copying, distribution or other use of the E-mail is strictly prohibited. In the event this document(s) contains technical data within the definition of the International Traffic in Arms Regulations, it is subject to the export control laws of the U.S. Government. Transfer of this data by any means to a foreign person, whether in the United States or abroad, without an export license or other approval from the U.S. Department of State, is prohibited. Neither the company nor any subsidiary, affiliate or associated company nor any individual sending this E-mail accepts any liability in respect of the content (including errors and omissions).

**Comment by gzotti** [comment] 2023-07-04 14:06
@TonyBhargav any updates from your side? Does #3301 solve this issue?

**Comment by alex-w** [comment] 2023-07-05 19:52
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by gzotti** [comment] 2023-09-13 09:28
Several Qt6/TelescopeControl issues have been solved before 23.3. We tentatively close this as member of a large group of related issue reports for now. In case of re-occurrence of this issue in V23.3, please create a new report with very clear description of circumstances.

**Closed by gzotti** 2023-09-13 09:28 UTC
Labels: help wanted, good first issue
