### ISSUE TITLE
transit time incorrect on days changing from/to daylight saving time

### ISSUE THREAD

**Issue by CodeBiene** [Stellarium/stellarium#1482] opened 2021-01-26 12:55 UTC
### Expected Behaviour
calculation of the transit times of a whole year of the sun from a location on earth

### Actual Behaviour
To my honest opinion the two transit times on the days changing from normal to summer time and vice versa are incorrect.

### Steps to reproduce
1. Start Stellarium
   The location is Earth, Graz (Austria), 363m
2. Select the sun
3. press F10
4. select tab "Transits"
5. select start date 1st January 2021 and end date 31st December 2021
6. press "Calculate transits"
7. Save transits

Attached you can find a LibreOffice table with two sheets and two graphs
[transit.zip](https://github.com/Stellarium/stellarium/files/5873346/transit.zip)
.
One containing the results of version 0.20.2 and the other of version 0.20.4
In order to make the calculation error visible I added the colums H and I and the graph.
In case the functions are not part of the table I also attached the macro code.

### System
* Stellarium version: stellarium-0.20.2-win64.exe, stellarium-0.20.4-win64.exe
* Operating system: Windows 10 Pro, 2004, OS build 19041.746
* Graphics Card: NVIDIA GeForce GT 640M
* Screen type (if applicable): 1920x1080

### Logfile
no

Kind regards,
Willy

**Comment by alex-w** [comment] 2021-01-26 13:51
Duplicate of #554

**Comment by alex-w** [comment] 2021-01-26 15:05
Please share info about your time zone settings in Stellarium.

**Comment by CodeBiene** [comment] 2021-01-26 15:23
> 
> 
> Please share info about your time zone settings in Stellarium.

The time zone is "Europe/Vienna", which seems to be the standard setting for Graz Austria

**Comment by alex-w** [comment] 2022-09-16 12:41
@CodeBiene the issue is still exist for you in latest versions of Stellarium?

**Comment by CodeBiene** [comment] 2022-10-10 05:24
Hi Alex,
today I installed the latest version stellarium-1.22.3-win64.exe.
As described above I created a table with the transits.
The results you can find in the attached LibreOffice Calc table "RTS.ods".
The graph shows that the big difference of an hour vanished.
But now there are some strange smaller spikes, which don't make sense to me.
Sorry for the delayed reply.

Kind regards,
Willy
[RTS.ods](https://github.com/Stellarium/stellarium/files/9743471/RTS.ods)

**Comment by CodeBiene** [comment] 2022-10-10 05:47
Now I added the "Rise" and "Set" times to the graph.
What a surprise. Rise and Set times don't show the spikes!


Kind regards,
Willy
[RTS.ods](https://github.com/Stellarium/stellarium/files/9743564/RTS.ods)

**Comment by alex-w** [comment] 2022-10-10 06:38
This is fun!

**Closed** 2023-02-03 18:33 UTC
Labels: bug, importance: medium

**Comment by CodeBiene** [comment] 2023-11-03 06:24
Hi, thanks for your efforts.
The times are ok now.
