### ISSUE TITLE
Stellarium 0.18.1 crashing on Windows 10

### ISSUE THREAD

**Issue by wsbz001** [Stellarium/stellarium#224] opened 2018-07-24 15:22 UTC
I have a Windows 10 computer. I just recently downloaded Stellarium off the website. It downloads fine, but when I open the program, it runs for about 15 seconds, then crashes and closes the program. I have downloaded both the 32-bit and 64-bit versions of this program, and neither work. My friend, on a different computer, but the same operating system, is having the same trouble. I noticed one other person as already reported this issue on this website, but did not receive help. Is there something I need to update on my computer or is this an issue with Stellarium? Should I download a different version of Stellarium, such as an earlier version of the program?

Thank you,
Spencer

Below is a picture of my computer settings, which I believe meet the system requirements for running Stellarium:

![settings](https://user-images.githubusercontent.com/41640010/43148466-55bceaa6-8f33-11e8-994f-4f345682e190.PNG)

**Comment by sonic1243** [comment] 2018-07-24 15:48
Same for me, crashing as soon as it tries to update the TLE or whatever its called; you see it bottom right; as soon as the update dialogue shows it crashes. Have tried changing to https and no change ..

**Comment by Echo51** [comment] 2018-07-24 16:02
Can confirm same issue with Windows 8.1, changing to https://www. fixed the issues.

**Comment by chboing** [comment] 2018-07-24 17:30
Same problem, crashes after 10 15 secondes on both my computers ... it was working perfectly (on both) yesterday.
Window application event says ucrtbase.dll is the defective module ...
Just installed from 0.17 to 0.18 -> same result.
no config.ini in the "just installed" directory, and data/defaut-config.ini does not contains "http"

**Comment by sonic1243** [comment] 2018-07-24 17:34
Config file is in: C:/Users/YOURNAME/AppData/Roaming/Stellarium
Need to show hidden files/folders under YOURNAME .. or something to that effect ... .

**Comment by marmiter** [comment] 2018-07-24 17:40
Same problems as others. Win 10 v.1803. 64 bit. only seems to have been a problem since today. Tried changing the config.ini but no better. Problem exists on two different computers an HP Z200 workstation and a Lenovo laptop, just prior to crash there were problems with the ocular plugin not responding as expected such as showing a grid in one ocular that was not there before but I doubt that is relevant, just a noted unexpected behavior.

**Comment by chboing** [comment] 2018-07-24 17:44
Allright, it's solved after switching all url to https://www.stellarium ...

**Comment by wsbz001** [comment] 2018-07-24 17:54
Below is my config.ini file. I cannot find http://www,stellarium. Am I looking in the wrong place (I included where I found my config file and also the only http I find in the config file)?

![config](https://user-images.githubusercontent.com/41640010/43156681-d04ebb9a-8f48-11e8-87c5-d71a101c8f30.PNG)

**Comment by sonic1243** [comment] 2018-07-24 17:55
Thats not your config.ini .. see address above ^^^

**Comment by marmiter** [comment] 2018-07-24 18:06
I've changed occurrences of http to https in stellarium lines in C:\users\uname\AppData\Roaming\Stellarium this has not solved the problem for me. The is a note in the log file "Error transferring http://freegeoip.net/json/ is that relevant?

**Comment by sonic1243** [comment] 2018-07-24 18:08
It's the absence of "www." which is causing the crash from my experience, not the https.

**Comment by marmiter** [comment] 2018-07-24 18:11
That it! thanks sonic1243, my mistake I thought https change was needed. The addition of www does the trick.

**Comment by monkeyhybrid** [comment] 2018-07-24 18:54
This issue occurs on Linux and MacOS versions too. As mentioned above, changing `http://stellarium` to `https://www.stellarium` in `config.ini` fixes it.

One-liner fix for Linux:

`sed -i.bak 's#http://stellarium.org#https://www.stellarium.org#g' ~/.stellarium/config.ini`

And for MacOS:

`sed -i .bak 's#http://stellarium.org#https://www.stellarium.org#g' ~/Library/Application\ Support/Stellarium/config.ini`

**Comment by Anthrwpos** [comment] 2018-07-24 19:43
Hi, same here and it works by changing the www thanks. But now it's too heavy when i move the cursor, moving like almost frame by frame. Anyone knows why? Thanks.

**Comment by guillaumechereau** [comment] 2018-07-25 04:15
Its a problem due a reconfiguration of the server that now redirect http requests to the https version, and some plugins didn't support that. @alex-w fixed the code already! But I think we should also configure the server not to use a redirection for http traffic if possible, so that it still work for people who don't update.  I sent a message to @xalioth to ask him to have a look.

**Comment by xalioth** [comment] 2018-07-25 06:55
Sorry for that guys.. it seems GitHub automatically redirected
http://stellarium.org to http://www.stellarium.org instead of dealing with
both domains separately..

I changed a setting and it should be ok, but www.stellarium.org may have
issues

**Closed** 2018-07-25 10:17 UTC

**Comment by Anthrwpos** [comment] 2018-07-25 21:50
So, how to solve the frame by frame problem after the change www? Because is too heavy after this.

**Comment by gzotti** [comment] 2018-07-25 22:00
There should be no further slowdown. How many satellites do you have, how many minor bodies? You can try to rename config.ini to force a reset.

**Comment by monkeyhybrid** [comment] 2018-07-25 22:01
@Anthrwpos You should open a new issue for that.

**Comment by bigyin362** [comment] 2018-07-26 20:10
In Win 7, I set up a search on my C drive and indexed config.ini.  Took a while to find it but by using "Find and Replace" in the editor Find http, Replace all https, it did the trick.  Can't think why it changed in the first place though as the old version was working fine one day and not the next ?

**Comment by Anthrwpos** [comment] 2018-07-30 01:01
@gzotti There wasn't slow down before crashing. After the solution (adding the "www") the problem occured.

**Comment by gzotti** [comment] 2018-07-30 07:56
@Anthrwpos feel free to read the messages in this thread and understand that you can revert the URLs to stellarium.org. There was some temporary misconfiguration.
