### ISSUE TITLE
Solar apex

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1406] opened 2020-12-11 22:43 UTC
It would be nice to see a point in the sky that represents the direction in which the solar system is moving.

Read more here:
https://en.wikipedia.org/wiki/Solar_apex

**Comment by gzotti** [comment] 2020-12-11 23:42
Duplicate of #850. It is just a boring marker without any motion in our local model in which the sun does not move.

**Closed** 2020-12-11 23:42 UTC
Labels: duplicate
