### ISSUE TITLE
Umbra and Penumbra based on custom distance

### ISSUE THREAD

**Issue by Carz10** [Stellarium/stellarium#2360] opened 2022-03-23 19:43 UTC
**Is your feature request related to a problem? Please describe.**
The Problem with the current implementation is that it seems fixed for the distance to the Moon. We operate Satellites in geostationary orbit and it would be interesting to see the umbra/penumbra based on the distance to those satellites to assess when they enter the shadow during eclipse time (March-April/September-October).

**Describe the solution you'd like**
I would like to be able to set a value for the distance the umbra-calculatuion will be based on. Alternatively, a checkbox to add the umbra lines for 36,000km distance in addition to the existing umbra indicators.

**Describe alternatives you've considered**
None possible for me

**Additional context**
I am chair of the Astronomy Club at EUMETSAT and we are very keen to observe the GEO satellites just before they enter the shadow, as they do flare up for a minute or so and become visible, whie otehrwise they never are (way too dark without direct sunlight reflection)

Would that not be an easy and interesting additional feazure? Should be quite easy to programm, as code should be same as for the other umbra circles, just with different base value for distance. Or?

We all thank you for this awesome tool!

Carsten

**Comment by alex-w** [comment] 2022-03-23 19:49
Duplicate of #1246

**Comment by Carz10** [comment] 2022-03-23 20:44
It is similar to #1246, I agree, but I do not want to select a satellite and see a cone. The cone of the earth's shadow is always there. I only need to see anotehr ring indicating the GEO distance slice of the cone, OR a customisable distance of any slice (e.g. the ISS). 
Maybe I am being naive, but it feels it just a 2nd set of umbra/penumbra calculated rings on top or alternatively to the Moon-one.
I'd really love this extra one and I would appreciate a consideration

**Comment by alex-w** [comment] 2022-03-23 20:47
Just adding code from core as new one method into Satellites plugin with 3 parameters - 2 flags and value of distance.

**Comment by gzotti** [comment] 2022-03-23 22:53
Somebody can draw a ring (like umbra traces for the Moon) for the currently selected satellite, in the current distance of the currently selected satellite. Or you just work with satellite icons and their "shadowed" color.

**Closed** 2022-05-22 10:30 UTC
Labels: feature request, good first issue

**Comment by Carz10** [comment] 2022-06-18 09:34
Thank you SOOO much for implementing! Super great work! Heavily appreciated.

All the best, Cars10!
