### ISSUE TITLE
Crash when selecting certain dates in 1 AD

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#594] opened 2019-01-15 07:25 UTC
### Expected Behaviour
Shows dates of year 1 as normal.

### Actual Behaviour
Crashes once you select a date between 0001-01-01 and 0001-03-25.

### Steps to reproduce
1. Start Stellarium.
2. Select a date in the given interval.
3. Crash!

### System
Windows 10
GTX GeForce 1070
Latest beta (Although I think this happens in the stable 0.18.3 too)

I tried loading the default solarsys file, but it didn't solve the problem.

**Comment by alex-w** [comment] 2019-01-15 07:57
Cannot confirm the issue. Please attach the log from Stellarium.

**Comment by Atque** [comment] 2019-01-15 08:21
[log.txt](https://github.com/Stellarium/stellarium/files/2758649/log.txt)

**Comment by gzotti** [comment] 2019-01-16 10:39
Cannot confirm either. I wheeled through all dates and entered some manually. No crash, all fine. How do you set your date, exactly?
Do you have any old settings from a very old config file? Can you rename your config.ini to start with default values and try again?

**Comment by Atque** [comment] 2019-01-16 16:50
@gzotti Thank you. Renaming the config file and thus returning to the default one solved the problem. I can't understand what went wrong though...

Let's close this!

**Comment by alex-w** [comment] 2019-01-16 16:54
Please attach your old config.ini file

**Comment by Atque** [comment] 2019-01-16 17:37
@alex-w Sure.


[config.zip](https://github.com/Stellarium/stellarium/files/2765393/config.zip)

**Comment by Atque** [comment] 2019-01-16 19:05
Allright, I know how to trigger this:

1. Start Stellarium
2. Open locations window (F6)
3. Uncheck "Use custom time zone".
4. Open time window (F5)
5. Select a date between 0001-01-01 and 0001-03-25.
6. Crash.

The config now has a new line with your time zone. That line probably causes the crash (something about DST I would guess).

**Comment by alex-w** [comment] 2019-01-17 04:08
Could you attach the log after crash?

**Comment by gzotti** [comment] 2019-01-17 09:04
"Use custom time zone" is disabled, using system TZ. Still cannot reproduce it. But what is *your* "system standard" time zone?

Anyway, I see the logic is still not perfect. We had said there were no timezones, so also "default" times should display LMST before 1848 or so.

**Comment by Atque** [comment] 2019-01-18 13:07
@alex-w Here's the log after the crash has been triggered:
[log.txt](https://github.com/Stellarium/stellarium/files/2772988/log.txt)

@gzotti My time zone is Europe/Stockholm. If I check "Use custom time zone", the line
time_zone = Europe/Stockholm
is written in my config.cfg, under [localization]. This will trigger the crash, and erasing that line will solve the problem. But why is this problem only occuring at year 1? Why not at year 2 or any other year pre-1846?

**Comment by alex-w** [comment] 2019-01-18 13:14
Thanks for the log - I don't see the problems in the log. And I cannot reproduce the crash on my system with your settings.

**Comment by Atque** [comment] 2019-01-18 13:15
@alex-w This is weird... Can you reproduce it by manually adding that line in your config file?

time_zone = Europe/Stockholm

**Comment by alex-w** [comment] 2019-01-18 13:18
I've used your config.ini and pass your steps to reproduce the crash - nothing

**Comment by gzotti** [comment] 2019-01-18 14:58
Clicking on the map MUST set LMST by design as long as we don't have a location->TZ lookup. Clicking on a city should set its time zone correctly.

But while it would totally make sense to allow only LMST or LTST for dates before 1848 or so (back in times when the concept of time and longitude was clear to more people than today), we still allow anachronistic time zone settings. Admittedly, with so many settings around location and time that interdepend, there seem to be some quirks which GUI element is auto-updated, blocked, auto-filled etc.

**Comment by gzotti** [comment] 2019-01-18 15:23
Wow, this is odd. With Europe/Stockholm I just wheeled back the years from 10 to 1 (or wanted), and when it should jump to 1 it went to 69 instead. 

wow^2! Wheeling the months I can also do that in Europe/Vienna and others. From 0-12-6 to 69-1-24

And setting time to 0-12-31 and let the time run fast (no date panel interaction!) we go to -68-12-14.

Still no crash but OK, there is something very strange going on here.

**Comment by Atque** [comment] 2019-01-18 15:34
@gzotti Very strange indeed.

It is also strange how it doesn't change to LMST even though it says it has (by clicking on the map). See this screenshot. LMST officially set, but the time is still given in UTC+1.
![strange](https://user-images.githubusercontent.com/37028368/51396192-e840e480-1b3e-11e9-9140-da6fe86ce6b4.PNG)

**Comment by alex-w** [comment] 2019-01-18 15:41
@Atque The LMST issue has been fixed in the master

**Comment by Atque** [comment] 2019-01-18 15:55
@alex-w That's great! Maybe that will fix this strange problem.

**Comment by jamjam77** [comment] 2019-01-22 10:14
I have got the same in windows 7. My version is 0.18,3 .
I tried to go to date BC 7 (even possible in this app?) 
Firs I deleted 09 out from 2019 at time setting window, so I got to year 29.
Then I pressed the "down" arrow several times, until I get down to year 2. Then stopped, frozen.
No response, cannot close window, if I clicking around with the mouse, it crashed.

**Comment by gzotti** [comment] 2019-01-22 10:33
I have no trouble with 7BC (which must be set as -6) in either "system default" or LMST. What is your timezone setting? This seems to be the troublemaker. I could reproduce a crash with manually selected zones Europe/Stockholm, and even Europe/Vienna (which should be my system default!). Try setting your timezone to LMST, then set the date.

**Comment by gzotti** [comment] 2019-01-22 12:47
Alright, it seems to work in general with UTC+/-n zones, but not with many named zones. Not sure about the reason yet, just a further observation. Maybe all zones with DST rules?

**Comment by alex-w** [comment] 2019-01-22 14:00
Please check the latest beta - I hope it contains some improvements for this issue (for example in version 0.18.3 LMST cannot be selected).

**Comment by gzotti** [comment] 2019-01-22 14:12
Really? I can select LMST or TMST in 0.18.3 without problem (WIn10). However I see I cannot select UTC-9 or earlier, UTC+8 and later, or UTC+4:30 and other intermediate zones. This is getting weird, really. I will have a look into it, but likely in February only. Probably TZ behaviour and handling is really different between Windows and Linux so that we need more different code paths.

**Comment by alex-w** [comment] 2019-01-22 14:19
@gzotti you may select LMST in Location dialog, but the LMST time zone won't be selected within planetarium, because check-point in StelCore::setCurrentTimeZone() always return false for LSMT due LMST, LTST and system_default timezones was forget in StelLocationMgr::getAllTimezoneNames().

Plus see bug #602 - seems couple last refactoring (scripting + simplification) introduced few hidden bugs.

**Comment by gzotti** [comment] 2019-01-22 14:34
Sorry, how do you interpret this? 
![2019-01-22 15_25_35-stellarium 0 18 3_timezoneweirdness](https://user-images.githubusercontent.com/18099873/51541941-5e548c80-1e5a-11e9-8738-dafec0679361.png)

Screenshot from 0.18.3. LMST behaviour is correct in this case. 
I cannot go into code in the next few days, sorry. But yes, there are probably several interrelated bugs. And given the reported weirdness I now even suspect different results on Windows and Linux.

**Comment by Atque** [comment] 2019-01-22 15:53
@alex-w Still crash, but somehow inverted from before. It now crashes if you select a city and go to the given date. But the LMST works! And the crash can easily be avoided by simply unselecting the always re-selected "Use custom time zone".

**Comment by alex-w** [comment] 2019-01-22 15:55
@Atque Could you share log from Stellarium immediately after crash?

**Comment by Atque** [comment] 2019-01-22 16:06
@alex-w This is very odd. I could trigger the crash yesterday (with the latest beta released yesterday), but today it seems a lot harder to trigger. I had to play around a LOT with the settings to trigger a crash. But anyway, here's the log from a successful crash:

[log.txt](https://github.com/Stellarium/stellarium/files/2783581/log.txt)

**Comment by gzotti** [comment] 2019-03-20 00:52
OK, something weird is happening in StelCore::getUTCOffset(). Sometimes offset (seconds) becomes MIN_INT, and these are almost 70 years, which explains the date jump. We must investigate this further.

**Comment by gzotti** [comment] 2019-03-20 18:24
I identified what we must assume is a QTBUG on Windows. It seems we can at least circumnavigate it.

**Comment by gzotti** [comment] 2019-03-20 22:50
A solution is included in #654.

**Closed** 2019-03-21 16:12 UTC
Labels: bug, fix committed, incomplete
