### ISSUE TITLE
my apple IOS will not allow installation of latest version

### ISSUE THREAD

**Issue by jbmcmath** [Stellarium/stellarium#1020] opened 2020-03-28 22:13 UTC
my apple IOS will not allow installation of the latest version on grounds it cannot verify the source.  Please advise.

**Comment by alex-w** [comment] 2020-03-28 23:59
iOS? Maybe macOS?

**Comment by gzotti** [comment] 2020-03-29 00:14
#1003, #931, https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#unsigned-installer-dangerous-to-download-malware

**Comment by jbmcmath** [comment] 2020-03-29 03:34
Yes, sorry, mac OS

On Mar 28, 2020, at 6:59 PM, Alexander Wolf <notifications@github.com<mailto:notifications@github.com>> wrote:



iOS? Maybe macOS?

**Comment by alex-w** [comment] 2020-03-29 03:36
The problem is fixed in beta, plus we will release version 0.20.0 later today.

**Closed by alex-w** 2020-03-29 03:36 UTC
Labels: FAQ, duplicate
